const pinyins = {
  黑崎一护: ['Kurosaki', 'Ichigo'],
  井上织姬: ['Inoue', 'Orihime'],
  朽木露琪亚: ['Kuchiki', 'Rukia'],
  阿散井恋次: ['Abarai', 'Renji'],
  魂: ['Kon'],
  石田雨龙: ['Ishida', 'Uryuu'],
  朽木白哉: ['Kuchiki', 'Byakuya'],
  涅茧利: ['Kurotsuchi', 'Mayuri'],
  斑目一角: ['Madarame', 'Ikkaku'],
  葛力姆乔·贾卡杰克: ['Grimmjow', 'Jaegerjaques '],
  乌尔奇奥拉·西法: ['Ulquiorra', 'cifer'],
  雏森桃: ['Hinamori', 'Momo'],
  茶渡泰虎: ['Sado', 'Yasutora'],
  露比·安特诺尔: ['Luppi', 'Antenor'],
  艾多拉德·里欧尼斯: ['Edorad', 'Leones'],
  萧隆库方: ['Shawlong', 'Koufang'],
  伊尔弗特·古兰兹: ['Yylfordt', 'Granz'],
  市丸银: ['Ichimaru', 'Gin'],
  浦原喜助: ['Urahara', 'Kisuke'],
  四枫院夜一: ['Shihouin', 'Yoruichi'],
  黑崎一心: ['Kurosaki', 'Isshin'],
  石田龙弦: ['Ishida', 'Ryuken'],
  妮莉艾露·杜·欧德修凡克: ['Neliel', 'Tu', 'Oderschvank'],
  诺伊特拉·吉尔加: ['Nnoitra', 'Gilga'],
  更木剑八: ['Zaraki', 'Kenpachi'],
  志波海燕: ['Shiba', 'Kaien'],
  黑刀: ['Kokutō'],
  吉良伊鹤: ['Kira', 'Iziru'],
  缇鲁蒂·桑达薇琪: ['Cirucci', 'Thunderwitch'],
  天锁斩月: ['Tensa', 'Zangetsu'],
  黑崎真咲: ['Kurosaki', 'Masaki'],
  志波一心: ['Shiba', 'Isshin'],
  松本乱菊: ['Matsumoto', 'Rangiku'],
  牙密·里亚尔戈: ['Yammy', 'Llarg'],
  刚腾拜恩·莫司克达: ['Gantenbein'],
  平子真子: ['Shinji', 'Hirako'],
  大前田希千代: ['Omaeda', 'Marechiyo'],
  阿比拉玛·勒达: ['Avirama', 'Leda'],
  碎蜂: ['Soi', 'Fon'],
  蓝染惣右介: ['Aizen', 'Sousuke'],
  爱川罗武: ['Aikawa', 'Love'],
  凤桥楼十郎: ['Ōtoribashi', 'Rōjūrō'],
  东仙要: ['Tousen', 'Kaname'],
  蒂雅·赫利贝尔: ['Tier', 'Halibel'],
  浮竹十四郎: ['Ukitake', 'Jūshirō'],
  京乐春水: ['Kyoraku', 'Shunsui'],
  日番谷冬狮郎: ['Hitsugaya', 'Toushirou'],
  狛村左阵: ['Komamura', 'Sajin'],
  芬朵尔·凯利亚司: ['Findorr'],
  山本元柳斋重国: ['Yamamoto', 'Genryuusai', 'Shigekuni'],
  桧佐木修兵: ['Hisagi', 'Shuuhei'],
  草冠宗次郎: ['Kusaka', 'Sojiro'],
  卯之花烈: ['Unohana', 'Retsu'],
  柯雅泰·史塔克: ['Coyote', 'Starrk'],
  亚罗尼洛·艾鲁鲁耶利: ['Aaroniero', 'Arruruerie'],
  白一护: ['White', 'Ichigo'],
  拜勒冈·鲁伊森邦: ['Baraggan', 'Louisenbairn'],
  嘉蒂丝·卡特尼普: ['Candice', 'Catnipp'],
  葛雷密·托缪: ['Gremmy', 'Thoumeaux'],
  雨葛兰·哈斯沃德: ['Jugram', 'Haschwalth'],
  阿西多: ['Ashido', 'Kanō'],
  '四枫院夜一&碎蜂': ['Shihouin', 'Yoruichi', 'Soi', 'Fon'],
  卯之花八千流: ['Unohana', 'Yachiru'],
  朱莲: ['Shuren'],
  萨尔阿波罗·古兰兹: ['SzayelAporro', 'Granz'],
  佐马利路鲁: ['Zommari', 'Rureaux'],
  雀部长次郎: ['Sasakibe', 'Chōjirō'],
  阿兹基尔罗·伊邦: ['Asguiaro', 'Ebern'],
  旺达怀斯·马尔杰拉: ['Wonderweiss', 'Margera'],
  贾姬: ['Jackie', 'Tristan'],
  茜雫: ['Senna'],
  荪荪: ['Sung-Sun'],
  六车拳西: ['Muguruma', 'Kensei'],
  基力安: ['Gillian'],
  修多罗千手丸: ['Shutara', 'Senjumaru'],
  斩月: ['Zangetsu'],
  草鹿八千流: ['Kusajishi', 'Yachiru'],
  多利斯克·贝尔希: ['Driscoll', 'Berci'],
  久南白: ['Kuna', 'Mashiro'],
  白: ['White'],
  艾斯诺特: ['As', 'Nodt'],
  洛伊德罗伊德: ['Royd', 'Lloyd'],
  友哈巴赫: ['Yhwach'],
  新桥诺艾尔: ['Niihashi', 'Noel'],
  妮妮·斯庞柯尔: ['Ninny', 'Spangcole'],
  布鲁诺·邦古耐夫: ['Bruno', 'Bangnyfe'],
  约翰威克: ['John', 'Wick'],
  红莲骑士兽: ['Dukemon'],
};
export default pinyins;
