const characterSort = {
  //——————————————————————————————————————————————————————BLEACH——————————————————————————————————————————————————————//
  bleach_death_strawberry: ['bleach_xiumuluqiya', 'bleach_arena_heiqiyihu', 'bleach_jingshangzhiji', 'bleach_shitianyulong', 'bleach_chad', 'bleach_hun'],
  bleach_memorles_in_the_rain: ['bleach_heiqiyihu', 'bleach_zhibohaiyan', 'bleach_re_jingshangzhiji'],
  bleach_a_star_and_a_stray_dog: ['bleach_abarai', 'bleach_xiumubaizai', 'bleach_re_xiumuluqiya'],
  bleach_in_the_name_of_gotei: ['bleach_niejianli', 'bleach_shiwanyin', 'bleach_banmu', 'bleach_chusentao', 'bleach_gengmu', 'bleach_jiliang', 'bleach_songben', 'bleach_daqiantian', 'bleach_suifeng', 'bleach_lanran', 'bleach_dongxian', 'bleach_fuzhu', 'bleach_jingle', 'bleach_dongshilang', 'bleach_shanben', 'bleach_maozhihualie', 'bleach_sp_liuche'],
  bleach_blue: ['bleach_grimmjow', 'bleach_aiduolade', 'bleach_xiaolong', 'bleach_yylfordt', 'bleach_re_banmu'],
  bleach_truth: ['bleach_heiqiyixin', 'bleach_shitianlongxian', 'bleach_grandfisher'],
  bleach_conquistadores_and_violador: ['bleach_wuerqiaola', 'bleach_puyuanxizhu', 'bleach_sifengyuanyeyi', 'bleach_lubi'],
  bleach_family: ['bleach_pingzi', 'bleach_aichuanluowu', 'bleach_fengqiao', 'bleach_liuche', 'bleach_jiunanbai'],
  bleach_black_and_white: ['bleach_baiyihu', 'bleach_re_heiqiyihu'],
  bleach_revolt: ['bleach_sp_lanran', 'bleach_yeyisuifeng'],
  bleach_opera: ['bleach_tiludi', 'bleach_gangtenbaien', 'bleach_re_chad', 'bleach_ashido'],
  bleach_fear: ['bleach_abirama', 'bleach_findorr'],
  bleach_chimaera_chord: ['bleach_sunsun'],
  bleach_belle_are_blue: ['bleach_re_dongxian', 'bleach_bocun', 'bleach_hisaki', 'bleach_wonderweiss', 'bleach_sb_lanran'],
  bleach_dead: ['bleach_starrk', 'bleach_harribel', 'bleach_nelliel', 'bleach_nnoitra', 'bleach_re_grimmjow', 'bleach_re_wuerqiaola', 'bleach_yami', 'bleach_yaluoniluo', 'bleach_baraggan', 'bleach_sazayelaporro', 'bleach_zommari'],
  bleach_kami: ['bleach_tensa', 'bleach_hougyoku_lanran', 'bleach_re_lanran'],
  bleach_the_soul_pantheism: ['bleach_jiaji'],
  bleach_blood_war_foundation_stones: ['bleach_2022_shitianyulong', 'bleach_2022_chad', 'bleach_yibang'],
  bleach_desolate: ['bleach_tybw_quebu', 'bleach_tybw_shanben'],
  bleach_inheritance: ['bleach_maozhihuabaqianliu', 'bleach_caolubaqianliu', 'bleach_tybw_gengmu'],
  bleach_norain: ['bleach_heiqizhenxiao', 'bleach_zhiboyixin', 'bleach_tybw_shitianlongxian', 'bleach_bai'],
  bleach_the_blade_and_me: ['bleach_zangetsu', 'bleach_8th_heiqiyihu'],
  bleach_the_last_9days: ['bleach_zombie_dongshilang', 'bleach_jiadisi', 'bleach_gremmy', 'bleach_haschwalth', 'bleach_driscoll', 'bleach_asnodt', 'bleach_royd', 'bleach_yhwach'],
  bleach_the_fundamental_virulence: ['bleach_tybw_pingzi', 'bleach_tybw_liuche'],
  bleach_theater: ['bleach_heidao', 'bleach_sp_xiumuluqiya', 'bleach_caoguan', 'bleach_xina', 'bleach_zhulian'],
  bleach_diy: ['bleach_senjumaru'],
  bleach_test: ['bleach_jilian', 'bleach_tybw_pingzi'],
  //——————————————————————————————————————————————————————Brave Souls——————————————————————————————————————————————————————//
  bravesouls_cfyow: ['bleach_hougyoku_wuerqiaola'],
  bravesouls_safwy_untold_stories: ['bleach_5th_heiqiyihu', 'bleach_5th_xiumubaizai', 'bleach_us_dongshilang'],
  bravesouls_burnthewitch: ['burnthewitch_xinqiao', 'burnthewitch_nini', 'burnthewitch_bruno'],
  bravesouls_bravesouls: ['bleach_quincy_heiqiyihu', 'bleach_7th_heiqiyihu', 'bleach_7th_shitianyulong'],
  bravesouls_swimsuit: ['bleach_swimsuit_jiadisi'],
  bravesouls_cacao_society: ['bleach_cacao_wuerqiaola'],
  bravesouls_machine_society: ['bleach_machine_jiliang'],
  bravesouls_spirit_society: ['bleach_yk_grimmjow', 'bleach_yk_baiyihu', 'bleach_yk_shiwanyin'],
  bravesouls_future_society: ['bleach_future_nnoitra']
};
const characterSortTranslate = {
  //——————————————————————————————————————————————————————BLEACH——————————————————————————————————————————————————————//
  bleach_death_strawberry: '死神&草莓',
  bleach_memorles_in_the_rain: '雨中的回忆',
  bleach_a_star_and_a_stray_dog: '星星与野狗',
  bleach_in_the_name_of_gotei: '以护庭二字',
  bleach_conquistadores_and_violador: '征服与侵袭',
  bleach_black_and_white: '黑与白',
  bleach_belle_are_blue: '丧钟',
  bleach_the_soul_pantheism: '灵魂泛神论',
  bleach_blood_war_foundation_stones: '血战、基石',
  bleach_the_blade_and_me: '刀锋与我',
  bleach_the_last_9days: '最后的9日',
  bleach_the_fundamental_virulence: '根源之毒',
  bleach_blue: '神之蓝调',
  bleach_truth: '告诉孩子们真相',
  bleach_family: '成为我的同类吧',
  bleach_revolt: '月夜的反叛',
  bleach_opera: '尖锐的歌剧',
  bleach_fear: '对战斗的恐惧',
  bleach_chimaera_chord: '混兽神',
  bleach_dead: '死亡',
  bleach_kami: '弑神',
  bleach_desolate: '荒凉',
  bleach_inheritance: '传承',
  bleach_norain: '万物无雨',
  bleach_theater: '剧场版',
  bleach_diy: "群友DIY",
  bleach_test: "测试",
  //——————————————————————————————————————————————————————Brave Souls——————————————————————————————————————————————————————//
  bravesouls_cfyow: 'CFYOW',
  bravesouls_safwy: 'SAFWY',
  bravesouls_safwy_untold_stories: 'Untold Stories',
  bravesouls_burnthewitch: 'Burn The Witch',
  bravesouls_bravesouls: 'Brave Souls',
  bravesouls_swimsuit: '烈日炎炎',
  bravesouls_cacao_society: '可可界',
  bravesouls_machine_society: '机械界',
  bravesouls_spirit_society: '妖魔界',
  bravesouls_future_society: '未来世界'
};
export { characterSort, characterSortTranslate };