const translates = {
  bleach_off: '减益',
  bleach_heiqiyihu: '黑崎一护',
  bleach_yuechong: '月衝',
  bleach_yuechong_info: '摸牌阶段,你可以视为使用一张无视距离的【杀】.若如此做,你少摸一张牌.',
  bleach_bankai: '卍解',
  bleach_bankai_info: "觉醒技,当你体力值或手牌数减少至1时,你减1点体力上限,获得1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>并回复1点体力或摸两张牌,你获得【连迅】【本能】且你使用的下两张实体【杀】不能被响应.",
  bleach_lianxun: '连迅',
  bleach_lianxun_info: '当你成为其他角色使用牌目标时,你可以展示其一张手牌,若两张牌花色相同,此牌对你无效.',
  bleach_shunbu: '瞬步',
  bleach_shunbu_info: '锁定技,你计算与其他角色的距离时始终-1.',
  bleach_benneng: '本能',
  bleach_benneng_info: '觉醒技,当你即将死亡时,你进入「半虚化状态」并强制托管,期间你免疫死亡,此状态下你的第二个回合开始时,你对一名其他角色造成1点伤害,解除此状态.',
  bleach_jingshangzhiji: '井上织姬',
  bleach_zhandun: '斩盾',
  bleach_zhandun_info: '你可以将红色牌当【杀】使用或打出且每回合你使用的首张【杀】无距离和次数限制.',
  bleach_guidun: '归盾',
  bleach_guidun_info: '出牌阶段限一次,你可以与一名其他角色各重铸一张手牌,体力值较小的角色回复1点体力.',
  bleach_jiedun: '结盾',
  bleach_jiedun_info: "每轮限一次,当一名角色成为另一名其他角色使用的伤害牌的唯一目标后,你可以令其获得1层<a style='color: #808080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_shield');\">护盾</a>直到回合结束,若其未失去此护盾,其摸一张牌.",
  bleach_xiumuluqiya: '朽木露琪亚',
  bleach_fusai: '缚塞',
  bleach_fusai_info: '出牌阶段限一次,你可以将一张牌当【塞】使用,摸一张牌.',
  bleach_fuling: '赋灵',
  bleach_fuling_info: "限定技,出牌阶段,若你已受伤且体力值为全场最小,你可以将至少一半手牌(向下取整)交给一名其他角色,令其使用一张随机武器牌并获得1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>,且本局内其每回合首次造成伤害后,你摸一张牌;其于此回合结束后执行一个额外回合.",
  bleach_abarai: '阿散井恋次',
  bleach_sheyao: '蛇咬',
  bleach_sheyao_info: "出牌阶段限一次,你可以将一张牌当无距离限制且附加<a style='color: #FF6666' href=\"javascript:window.bleachIntroduceBuff('bleachMark_lieshang');\">裂伤</a>的【杀】使用.你使用【杀】的限制次数+2.",
  bleach_feiwang: '狒王',
  bleach_feiwang_info: "觉醒技,结束阶段,若你的装备区有武器牌,或武器栏已被废除,你回复1点体力或摸两张牌,获得【狒炮】和1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>.",
  bleach_feipao: '狒炮',
  bleach_feipao_info: "出牌阶段一次,你可以弃置一张牌对一名其他角色造成1点火焰伤害,其与其邻家各获得1层<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>.",
  bleach_hun: '魂',
  bleach_yihun: '义魂',
  bleach_yihun_info: '每轮限一次,其他角色结束阶段,其可以展示并交给你一张手牌,你可以弃置一张其他牌令其执行一个额外的回合.',
  bleach_haose: '好色',
  bleach_haose_info: '锁定技,每回合限一次,当你使用牌指定女性角色或成为女性角色使用牌的目标后,你摸两张牌.',
  bleach_shitianyulong: '石田雨龙',
  bleach_feilian: '飞镰',
  bleach_feilian_info: '锁定技,你于出牌阶段内首次使用某种花色的牌没有距离限制.',
  bleach_jiling: '汲灵',
  bleach_jiling_info: '当你需要使用或打出牌时(回合内限一次),你可以观看牌堆顶三张牌,可以使用或打出你需要的牌.',
  bleach_sanling: '散灵',
  bleach_sanling_info: '限定技,回合开始时,你可以:弃置判定区内的牌;获得【圣闪】并摸X张牌(X为你使用过的非手牌数),将等量张牌置于武将牌上,称为「灵」.',
  bleach_shengshan: '圣闪',
  bleach_shengshan_info: '当你使用【杀】指定目标后,你可以移去任意张「灵」令伤害值+X(X为移去的「灵」数).',
  bleach_tiankui: '天傀',
  bleach_tiankui_info: '锁定技,你可以使用禁用的牌;你即将受到的伤害延迟在每回合结束时依次计算.',
  bleach_xiumubaizai: '朽木白哉',
  bleach_shanhua: '闪花',
  bleach_shanhua_info: "限定技,出牌阶段,你可以插入至一名其他角色的下家,并视为对其使用一张【杀】,若其受到了伤害,其废除武器栏并获得1层<a style='color: #FF0000' href=\"javascript:window.bleachIntroduceBuff('bleachMark_down');\">灵衰</a>.此回合结束后,因此跳过回合的角色执行一个额外回合.",
  bleach_yingren: '樱刃',
  bleach_yingren_info: '出牌阶段限X次,若你的装备区内有武器牌,你可以展示牌堆顶的一张牌并使用之.(X为该牌的攻击范围)',
  bleach_jingyan: '景严',
  bleach_jingyan_info: '觉醒技,准备阶段,若你武器栏内有牌,你减少1点体力上限,获得【刃景】且本局内你失去装备区内不为【千本樱】的牌后,你置于武将牌上,称为「樱」.',
  bleach_renjing: '刃景',
  bleach_renjing_info: '出牌阶段限一次,你可以依次获得以下技能:【吭景】/【歼景】/【终景】并失去上次以此法获得技能,你回复1点体力或摸两张牌.',
  bleach_kengjing: '吭景',
  bleach_kengjing_info: '锁定技,【樱刃】改为出牌阶段限一次,当你对其他角色造成伤害后,重置次数;你对与你距离为1的邻家使用实体【杀】的目标包含自己.',
  bleach_jianjing: '歼景',
  bleach_jianjing_info: '锁定技,你会在合适的时机移去一张「樱」并装备【千本樱】;出牌阶段限两次,你可以弃置一张武器牌并弃置一名角色区域内的一张牌.',
  bleach_zhongjing: '终景',
  bleach_zhongjing_info: '出牌阶段,你可以将所有「樱」当不计入次数限制且附带破防的【杀】使用,此牌伤害值为「樱」的数量,结算完成后你失去所有技能.',
  bleach_niejianli: '涅茧利',
  bleach_keyan: '科研',
  bleach_keyan_info: '出牌阶段开始时,你可以猜测牌堆顶的牌的颜色、花色和类型并展示,若你猜中:颜色,你使用牌没有距离限制至回合结束;类型,获得1枚「肉爆弹」;花色,获得1枚「补肉剂」.你摸三张牌,并弃置猜错项等量张手牌.',
  bleach_pisha: '疋杀',
  bleach_pisha_info: "当你使用【杀】造成伤害后,你可以对其附加1层<a style='color: #9400D3' href=\"javascript:window.bleachIntroduceBuff('bleachMark_du');\">中毒</a>.",
  bleach_dizang: '地藏',
  bleach_dizang_info: "限定技,出牌阶段,你可以将【疋杀】的限制取消且<a style='color: #9400D3' href=\"javascript:window.bleachIntroduceBuff('bleachMark_du');\">中毒</a>改为2层直到回合结束.",
  bleach_banmu: '斑目一角',
  bleach_xiangzhan: '享战',
  bleach_xiangzhan_info: '锁定技,当你造成或受到伤害后,你获得1枚「享战」标记(可抵挡等量伤害),当你造成伤害后,若你的「享战」标记大于1,你移去1枚「享战」并获得一张非同名伤害牌.你的手牌上限为体力上限.',
  bleach_tongming: '通名',
  bleach_tongming_info: '限定技,回合开始时,你可以令一名【决斗】合法目标观看你的手牌以视为对其使用之,结算完成后,其选择一项:1.令你观看其的手牌以视为对你使用之;2.与你各摸一张牌.',
  bleach_grimmjow: '葛力姆乔·贾卡杰克',
  bleach_grimmjow_ab: '葛力姆乔',
  bleach_shoulie: '狩猎',
  bleach_shoulie_info: '锁定技,每轮开始时,你选择一名其他角色,本轮你计算与其的距离时视为1.',
  bleach_xunjie: '迅捷',
  bleach_xunjie_info: '每回合每项各限一次,当你因使用或打出而失去手牌后,你可以:1.摸一张牌,你本回合使用相同花色的牌不能被响应;2.获得「狩猎」目标一张牌并弃置一张牌,你本回合内使用与该牌和弃置牌相同花色的牌没有次数限制.',
  bleach_wuerqiaola: '乌尔奇奥拉·西法',
  bleach_wuerqiaola_ab: '乌尔奇奥拉',
  bleach_gongyan: '共眼',
  bleach_gongyan_info: '出牌阶段限一次,你可以失去1点体力并观看一名其他角色的手牌,你弃置其中一张牌且本回合手牌上限+2.',
  bleach_zaisheng: '再生',
  bleach_zaisheng_info: '结束阶段,你可以弃置一张牌,回复1点体力.',
  bleach_gangpi: '钢皮',
  bleach_gangpi_info: '锁定技,你受到手牌数小于你的角色造成的伤害-1.',
  bleach_xinheiyi: '黑翼',
  bleach_xinheiyi_info: "觉醒技,每回合结束时,若你的手牌数与体力值至少相差2,你减1点体力上限,获得1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>和【虚闪】.",
  bleach_heixushan: '虚闪',
  bleach_heixushan_info: '你可以将一张黑色牌当【虚闪】使用;你以装备牌转化的【虚闪】伤害值+1.',
  bleach_chusentao: '雏森桃',
  bleach_feimei: '飞梅',
  bleach_feimei_info: '弃牌阶段开始时,你可以将一张牌名与「飞梅」均不同的非装备牌暗置于武将牌上,当其他角色使用或打出牌时,你可以移去相同名称的「飞梅」牌,对其造成1点火焰伤害.',
  bleach_guidao: '鬼道',
  bleach_guidao_info: '当你发动【飞梅】后,你可以摸一张牌,可以将一张牌当鬼道牌使用.',
  bleach_chad: '茶渡泰虎',
  bleach_lingbi: '灵臂',
  bleach_lingbi_info: '转换技,阳:当一名你与其距离为1以内的角色受到伤害时,你可以重铸一张黑色牌,防止该伤害;阴:当一名与你距离1以内的角色对其他角色造成伤害时,其可以令你选择是否重铸一张红色牌,令伤害值+1.',
  bleach_grandfisher: 'GrandFisher',
  bleach_miaoshi: '藐视',
  bleach_miaoshi_info: '每回合限两次,当你使用牌指定唯一目标后,你可以将手牌数摸/弃至与其手牌数相同(至多为5),其视为对你/你视为对其使用一张【杀】.',
  bleach_lubi: '露比·安特诺尔',
  bleach_lubi_ab: '露比',
  bleach_niaoniang: '茑娘',
  bleach_niaoniang_info: '每回合限X次,①你使用基本牌或非指向型普通锦囊牌时,你可以多指定至多两名角色为目标.②当你使用牌时,若此牌的目标数不大于二,你可以令一名目标结算两次.(X为你装备区里的牌数+1)',
  bleach_aiduolade: '艾多拉德·里欧尼斯',
  bleach_aiduolade_ab: '艾多拉德',
  bleach_gangyan: '刚炎',
  bleach_gangyan_info: "当你使用非转化的伤害基本牌或黑色锦囊牌指定目标后,你可以失去1点体力,弃置一名目标角色一张牌,若此牌与弃置牌颜色相同,你将弃置牌当<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>火【杀】对其使用.",
  bleach_xiaolong: '萧隆库方',
  bleach_jieduan: '截断',
  bleach_jieduan_info: '出牌阶段限一次,你可以弃置一张牌对一名其他角色造成1点伤害,你弃置其一张牌或摸一张牌.',
  bleach_yylfordt: '伊尔弗特·古兰兹',
  bleach_yylfordt_ab: '伊尔弗特',
  bleach_shanji: '闪击',
  bleach_shanji_info: '当你使用牌指定唯一目标后,你可以受到1点伤害以令此牌不能被响应并摸一张牌.',
  bleach_cangjiao: '苍角',
  bleach_cangjiao_info: "限定技,当你受到伤害后,你可以回满体力,获得【撞碎】和1层<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>,若你手牌数不大于当前回合角色,你摸两张牌.",
  bleach_zhuangsui: '撞碎',
  bleach_zhuangsui_info: "每轮限一次,当你造成或受到伤害后,你可以:1.回复1点体力;2.对其施加1层<a style='color: #FF6666' href=\"javascript:window.bleachIntroduceBuff('bleachMark_lieshang');\">裂伤</a>.",
  bleach_shiwanyin: '市丸银',
  bleach_shetu: '蛇突',
  bleach_shetu_info: '隐匿.锁定技,你检索一张【杀】并选择是否无视距离使用之.',
  bleach_huiya: '虺牙',
  bleach_huiya_info: '每轮限一次,每回合结束时,若本回合未使用过牌的类型有:基本牌,你可以视为使用一张【杀】;非基本牌,你可以摸一张牌.',
  bleach_puyuanxizhu: '浦原喜助',
  bleach_xuexia: '血霞',
  bleach_xuexia_info: '每回合限一次,你可以将手牌数调整至体力值以视为使用一张【无懈可击】.你因此弃牌的【无懈可击】不能被响应.',
  bleach_lianfu: '连缚',
  bleach_lianfu_info: '当你使用牌指定其他角色为目标时,你可以摸一张牌执行并移除首项(若其为上次本技能的目标,额外执行前一项):1.令其不能响应此牌;2.横置其;3.弃置其一张牌;4.对其造成1点火焰伤害.',
  bleach_sifengyuanyeyi: '四枫院夜一',
  bleach_fangui: '反鬼',
  bleach_fangui_info: '当其他角色使用牌时,你可以使用一张相同花色的牌并摸一张牌(每种花色限一次),该牌无效.',
  bleach_shunhong: '瞬鬨',
  bleach_shunhong_info: '其他角色计算与你的距离+1;每回合结束时,若你本回合使用或打出过牌,你可以视为使用一张无距离限制的雷【杀】.',
  bleach_arena_heiqiyihu: '黑崎一护',
  bleach_newjianya: '剑压',
  bleach_newjianya_info: '你获得过牌的阶段结束时,你可以对攻击范围内一名其他角色造成1点伤害.',
  bleach_heiqiyixin: '黑崎一心',
  bleach_ege: '颚割',
  bleach_ege_info: '当你使用【杀】指定一名角色为目标后,你可以展示其一张手牌,若这两张牌颜色相同,则此【杀】不计入次数、不可被响应且伤害+1,否则其弃置此牌且你摸一张牌.',
  bleach_shitianlongxian: '石田龙弦',
  bleach_xinjiling: '汲灵',
  bleach_xinjiling_info: '出牌阶段限两次,你可以观看牌堆顶一张牌,你可以使用此牌(无距离限制).',
  bleach_lingshi: '灵矢',
  bleach_lingshi_info: '当你使用不以此法使用牌后,若你手牌数没有变化,你可以视为使用一张无距离限制的【杀】.',
  bleach_nelliel: '妮莉艾露·杜·欧德修凡克',
  bleach_nelliel_ab: '妮莉艾露',
  bleach_chongzou: '重奏',
  bleach_chongzou_info: '每轮限一次,当你使用锦囊牌或【虚闪】指定你距离1以内的角色为目标时,你可以弃置一张同颜色牌将使用者改为你,将目标改为原使用者,若该牌为伤害牌,则伤害值+1.',
  bleach_lingqi: '羚骑',
  bleach_lingqi_info: '限定技,出牌阶段,你可以减1点体力上限(若你因此扣减了体力,你摸两张牌),获得【翠枪】和【马术】且本回合手牌上限-X(X为你本回合造成伤害值).',
  bleach_cuiqiang: '翠枪',
  bleach_cuiqiang_info: '出牌阶段,你可以将一张牌置于一名其他角色的武将牌上(须场上没有「翠枪」牌)并摸一张牌,当你对其使用与「翠枪」牌同花色的牌时,你移去其的「翠枪」牌并令其失去一点体力.每回合限两次.',
  bleach_nnoitra: '诺伊特拉·吉尔加',
  bleach_nnoitra_ab: '诺伊特拉',
  bleach_kuangxiao: '狂嚣',
  bleach_kuangxiao_info: "当你使用【杀】造成伤害后,你可以获得其区域内的一张牌,其视为对你使用一张【决斗】且失败的角色弃置一张牌.你的黑色【杀】造成伤害后,于回合结束时对其施加1层<a style='color: #FF6666' href=\"javascript:window.bleachIntroduceBuff('bleachMark_lieshang');\">裂伤</a>.",
  bleach_daogao: '祷告',
  bleach_daogao_info: '觉醒技,当你受到其他角色造成的伤害后,若你对其造成过伤害且体力值为全场最小,你减少1点体力上限,回满体力并摸等量张牌,获得【钢皮】【圣哭】并废除非武器栏且获得5个额外武器栏.',
  bleach_shengku: '圣哭',
  bleach_shengku_info: '锁定技,你的装备牌均视为【杀】且无次数限制,武器牌转化的【杀】结算后置入装备区;你的手牌上限＋X(X为你手牌中装备牌副类别数).',
  bleach_gengmu: '更木剑八',
  bleach_jianya: '剑压',
  bleach_jianya_info: '锁定技,当你使用【杀】指定其他角色为目标后,你弃置其一张牌.当你使用【杀】后,若未造成过伤害,你下一次【杀】造成的伤害+1.',
  bleach_douzhi: '斗志',
  bleach_douzhi_info: "觉醒技,当一名角色回复体力后,若你与其互相使用过【杀】,你摸其体力值张牌,本局内你的【杀】和【决斗】造成的伤害翻倍,获得〖享战〗和1层<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>并失去〖封印〗.",
  bleach_fengyin: '封印',
  bleach_fengyin_info: '锁定技,你的手牌上限减半(向下取整).当你首次受到一名角色【杀】的伤害时,此伤害值-1.',
  bleach_zhibohaiyan: '志波海燕',
  bleach_liehua: '捩花',
  bleach_liehua_info: '当你每回合首次使用一种花色的牌指定唯一目标后,你可以摸一张牌并弃置一张牌,若这两张牌花色相同,你可以弃置其区域内的一张牌.',
  bleach_nijuan: '逆卷',
  bleach_nijuan_info: '当你一次失去至少两张牌或每回合第一次失去最后的手牌后,你可以为一名其他角色选择一项:1.弃置等量的牌;2.受到1点伤害.',
  bleach_heidao: '黑刀',
  bleach_jiusuo: '䓘锁',
  bleach_jiusuo_info: '锁定技,当你死亡时,你于9回合后复活;你始终横置.',
  bleach_zuie: '罪恶',
  bleach_zuie_info: '当你造成或受到伤害后,你可以横置其或伤害来源并摸两张牌,你可以将两张手牌当无次数限制的【杀】使用.',
  bleach_jiliang: '吉良伊鹤',
  bleach_chazhu: '侘助',
  bleach_chazhu_info: '当你使用牌指定其他角色为目标后,你可以令其手牌上限－1(有技能效果则翻倍),其因此多弃牌后,回复以此法减少的等量手牌上限;当你造成伤害后,你可以令其攻击范围－1,直到其的武器栏发生变化.',
  bleach_gehou: '割喉',
  bleach_gehou_info: '每回合限一次,当一名你攻击范围内的角色脱离濒死状态后,或其的回合结束时,其没有手牌,你可以对其造成1点伤害.',
  bleach_tiludi: '缇鲁蒂·桑达薇琪',
  bleach_tiludi_ab: '缇鲁蒂',
  bleach_duanyi: '断翼',
  bleach_duanyi_info: '锁定技,当你受到伤害或因♣️️牌造成伤害后,你摸一张牌.',
  bleach_yisan: '翼散',
  bleach_yisan_info: '每回合结束时,你可以将一张牌当弃牌堆顶的即时牌使用(无视距离).',
  bleach_tensa: '天锁斩月',
  bleach_yuexi: '月息',
  bleach_yuexi_info: '每阶段结束时,若你于此阶段获得过至少两张牌,你可以重铸两张牌视为使用一张无距离限制的【杀】.',
  bleach_xinren: '心刃',
  bleach_xinren_info: '锁定技,当你摸牌阶段外非因本技能摸牌后,你令一名角色摸一张牌;当你于弃牌阶段外非因本技能弃牌后,你弃置一名其他角色一张牌.',
  bleach_heiqizhenxiao: '黑崎真咲',
  bleach_yuanshi: '援矢',
  bleach_yuanshi_info: '每回合限一次,当一名其他角色使用【杀】或【虚闪】指定另一名其他角色为目标后,你可以对其使用一张牌并取消其使用牌的目标.',
  bleach_youji: '诱击',
  bleach_youji_info: '每轮限一次,其他角色的出牌阶段开始时,你可以令其将一张牌当【杀】对你使用,若你未响应此牌,你对其造成1点伤害,否则你摸一张牌.',
  bleach_xuezhuang: '血装',
  bleach_xuezhuang_info: '转换技,回合开始时,你可以摸一张牌.阳:你使用牌无距离限制;阴:你每次至多受到1点伤害,你的手牌上限为体力上限.',
  bleach_zhiboyixin: '志波一心',
  bleach_yanyue: '剡月',
  bleach_yanyue_info: "出牌阶段限一次,你可以弃置一张牌对一名其他角色造成1点火焰伤害,你使用的下一张【杀】无距离限制且改为附带<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>的火【杀】.",
  bleach_isyuechong: '月衝',
  bleach_isyuechong_info: "蓄势技,当一名角色成为另一名其他角色伤害牌的唯一目标后,你可以视为对使用者使用一张<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>火【杀】并取消其使用牌的目标.",
  bleach_tybw_shitianlongxian: '石田龙弦',
  bleach_jishi: '即矢',
  bleach_jishi_info: '当你使用牌时,若此牌点数不小于你本回合内使用的所有牌,你可以摸一张牌.',
  bleach_lingshe: '灵射',
  bleach_lingshe_info: '出牌阶段限一次,你可以将一张牌当本轮进入过弃牌堆的基本牌或普通锦囊牌使用.',
  bleach_songben: '松本乱菊',
  bleach_huimao: '灰猫',
  bleach_huimao_info: '结束阶段,你可以重铸装备区的牌以视为使用一张无距离限制的【杀】.',
  bleach_jiuhao: '酒豪',
  bleach_jiuhao_info: '当你每回合首次使用♠️️牌后,你可以摸一张牌视为使用一张【酒】.你的【酒】效果不会因回合结束消失且减少等量手牌上限.',
  bleach_yami: '牙密·里亚尔戈',
  bleach_yami_ab: '牙密',
  bleach_jinu: '积怒',
  bleach_jinu_info: '锁定技,当你受到伤害或【杀】被抵消后,你获得1枚「怒气」标记并摸一张牌.',
  bleach_fenshou: '愤兽',
  bleach_fenshou_info: '限定技,准备阶段,你可以回复X点体力(X为你半数取下的「怒气」标记数),你获得【巨撼】【崩坏】和【怒盈】.',
  bleach_nuying: '怒盈',
  bleach_nuying_info: '觉醒技,当你受到伤害后,若你本局已受到过10点伤害,你回满体力.',
  bleach_juhan: '巨撼',
  bleach_juhan_info: '锁定技,当你使用【杀】时,你移去2枚「怒气」标记令伤害值+1;当你成为【杀】的目标后,你不能响应之且下次【积怒】摸牌数+1.',
  bleach_gangtenbaien: '刚腾拜恩·莫司克达',
  bleach_gangtenbaien_ab: '刚腾拜恩',
  bleach_longquan: '龙拳',
  bleach_longquan_info: '出牌阶段限一次,你可以拼点任意次:赢的次数较多的角色可以依次使用X张拼点牌(X为其赢的次数),另一名角色摸一张牌.',
  bleach_pingzi: '平子真子',
  bleach_nifu: '逆抚',
  bleach_nifu_info: '你可以将【杀】或【闪】互相转化使用或打出并摸一张牌.你的【杀】或【决斗】改为选择「顺」或「逆」且目标打出一张对应或相反的牌,否则此牌依然对其造成伤害.',
  bleach_jiamian: '假面',
  bleach_jiamian_info: "出牌阶段,你可弃置一张【虚闪】令任意名同势力角色获得1层<a style='color: #808080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_shield');\">护盾</a>.若你拥有<a style='color: #808080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_shield');\">护盾</a>,你视为有1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>;你计算与其他角色距离的时-1.",
  bleach_junshi: '军势',
  bleach_junshi_info: '主公技,限定技,出牌阶段,你可以选择一名其他角色并令所有同势力其他角色依次选择是否对其使用一张【杀】,你与响应的角色各摸一张牌.',
  bleach_daqiantian: '大前田希千代',
  bleach_daqiantian_ab: '大前田',
  bleach_liancai: '敛财',
  bleach_liancai_info: '出牌阶段限一次,你可以展示至多三张手牌,交给一名其他角色或重铸,以此法获得牌的角色下个/当前回合内视为拥有【瞬步】且使用【杀】的限制次数+1.',
  bleach_abirama: '阿比拉玛·勒达',
  bleach_abirama_ab: '阿比拉玛',
  bleach_wuli: '舞励',
  bleach_wuli_info: '当你一次性获得至少两张牌后,你可以将至多两手张牌交给其他角色.',
  bleach_zhanjiu: '战鹫',
  bleach_zhanjiu_info: '觉醒技,当你失去最后的手牌后,将手牌数摸至4并获得【翼炮】.',
  bleach_yipao: '翼炮',
  bleach_yipao_info: '出牌阶段,你可以令手牌上限-1直到受到伤害,视为使用一张【决斗】.',
  bleach_suifeng: '碎蜂',
  bleach_fengwen: '蜂纹',
  bleach_fengwen_info: '当你因牌对没用与此牌相同花色「蜂纹华」标记的角色造成伤害后,你可以摸一张牌并其获得之.',
  bleach_juesha: '决杀',
  bleach_juesha_info: '锁定技,当你使用与「蜂纹华」相同花色的牌对其他角色造成伤害时,移去该标记,令此伤害+1;你使用的偶数张牌没有距离限制.',
  bleach_leibian: '雷鞭',
  bleach_leibian_info: "限定技,出牌阶段,你可以对一名其他角色造成1点<a style='color: #FFA500' href=\"javascript:window.bleachIntroduce('damagekill');\">斩杀</a>火焰伤害.",
  bleach_lanran: '蓝染惣右介',
  bleach_chengfu: '城府',
  bleach_chengfu_info: '隐匿,当你于回合外登场后,你可以对当前回合角色造成1点伤害;每回合各限一次,当其他角色获得你的牌或受到你造成的伤害后,你可以令其失去1点体力或弃置一张牌.',
  bleach_chengfu_append: '<span style="font-family: yuanli">从今往后,由我立于天上!</span>',
  bleach_jinghua: '镜花',
  bleach_jinghua_info: '每轮限一次,当其他角色使用牌指定你为目标时,你可以弃置一张牌,令此牌仅对一名非目标角色生效.',
  bleach_sp_xiumuluqiya: 'SP朽木露琪亚',
  bleach_sp_xiumuluqiya_prefix: 'SP',
  bleach_qieyi: '切忆',
  bleach_qieyi_info: '锁定技,你即将造成的伤害均视为体力流失;当其他角色因此即将流失体力时,其技能失效至回合结束并随机获得1层<font color=red>异常</font>状态.',
  bleach_xiangzhuan: '响转',
  bleach_xiangzhuan_info: '每轮限一次,当你使用即时牌时,你可以令此牌不能被响应.你计算与你距离为1的角色距离-1.',
  bleach_aichuanluowu: '爱川罗武',
  bleach_chichui: '炽锤',
  bleach_chichui_info: "出牌阶段限一次,你可以为一名攻击范围内的角色选择一项:1.令其摸一张牌,视为对其使用一张附带<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>效果的【杀】;2.横置其,视为对其使用一张火【杀】.",
  bleach_fengqiao: '凤桥楼十郎',
  bleach_zongyue: '纵乐',
  bleach_zongyue_info: '当你使用非装备牌指定目标后,你可以将牌堆顶的牌置于一名目标角色的武将牌上(至多四张),若这些牌花色均不同,你选择一项:1.获得这些牌.2.对其造成2点伤害,移去这些牌;出牌阶段限两次,你可以移动场上一张「纵乐」牌,若移动目标有相同花色的「纵乐」,随机移去一张牌.',
  bleach_re_chad: '茶渡泰虎',
  bleach_moji: '魔击',
  bleach_moji_info: '锁定技,当你拼点或决斗胜利/造成或受到1点伤害后,你获得1枚「蓄势」标记,你每有3枚此标记,你的【杀】伤害便+1.',
  bleach_relingbi: '灵臂',
  bleach_relingbi_info: '转换技,阳:当你受到伤害后,你可以摸两张牌或回复1点体力;阴:当你造成伤害时,你可以重铸一张牌令伤害值+1;你的攻击范围和手牌上限+1.',
  bleach_dongxian: '东仙要',
  bleach_qingchong: '清虫',
  bleach_qingchong_info: '隐匿.当你于回合外登场后,你可以结束当前回合.',
  bleach_feihuang: '飞蝗',
  bleach_feihuang_info: '摸牌阶段,你可以改为展示牌堆顶三张牌并获得其中一种颜色的牌,你可以将剩余牌依次当无距离限制的【杀】对本阶段未以此法受到过伤害的角色使用.',
  bleach_yanmo: '阎魔',
  bleach_yanmo_info: '限定技,出牌阶段,若你武器栏有牌,你可以选择一名其他角色:其不能响应你使用的非手牌【杀】且每回合开始随机附加1层<font color=red>异常</font>,此回合结束后其与你轮流进行回合,直到一方死亡或各进行四个回合为止,所有回合结算完毕后,你须失去X点体力(X为双方体力值之和).',
  bleach_harribel: '蒂雅·赫利贝尔',
  bleach_harribel_ab: '赫利贝尔',
  bleach_jianpao: '剑炮',
  bleach_jianpao_info: '出牌阶段,你可以失去1点体力,弃置本阶段未以此法选择过的至多两名角色共计两张牌.',
  bleach_jiaohou: '鲛后',
  bleach_jiaohou_info: '限定技,出牌阶段,你可以减少1点体力上限,你失去【剑炮】并获得【战雫】和【断瀑】,最后你可以弃置一张装备牌.',
  bleach_duanpu: '断瀑',
  bleach_duanpu_info: '出牌阶段限一次,你可以选择一名其他角色并亮出牌堆顶X张牌(X为你已损失体力值+1),若至少亮出了两张牌,你可以获得其中的一张牌,其须弃置剩余花色各一张牌,否则失去1点体力.',
  bleach_zhanna: '战雫',
  bleach_zhanna_info: "每阶段限一次,当你因弃置失去牌后,你可以视为使用一张无距离限制的<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰</a>【杀】.",
  bleach_fuzhu: '浮竹十四郎',
  bleach_shuangli: '双鲤',
  bleach_shuangli_info: '当你距离1以内的角色受到伤害时,你可以失去1点体力和前X个技能直到你使用本回合未使用过的伤害牌(X为伤害值),防止该伤害,你进行【闪电】判定并获得伤害牌.',
  bleach_leiren: '雷刃',
  bleach_leiren_info: '出牌阶段,你可以重铸至少两张伤害牌(每种牌名每回合限一次),使用其中一张.',
  bleach_shengua: '神卦',
  bleach_shengua_info: '当一名角色的判定牌生效前,你可以打出一张不同颜色的牌替换之.',
  bleach_jingle: '京乐春水',
  bleach_tongxi: '童戏',
  bleach_tongxi_info: '当你使用【杀】指定目标后,你可以与唯一目标各摸一张牌,改为执行一项「孩童的游戏」,当你成为其使用【杀】唯一目标时,你与其各摸一张牌并改为执行上次的「孩童的游戏」.',
  bleach_qianying: '潜影',
  bleach_qianying_info: '当你受到牌造成的伤害后,你可以令你不能被使用、使用或打出牌且不计入距离计算直到回合结束,你于回合结束时对其发动「影鬼」.',
  bleach_dongshilang: '日番谷冬狮郎',
  bleach_dongshilang_ab: '冬狮郎',
  bleach_binglong: '冰龙',
  bleach_binglong_info: '出牌阶段限一次,你可以拼点:若你赢:其不能对其他角色使用牌直到下回合结束或扣减体力;若你没赢,你移去1枚「冰莲华」标记.',
  bleach_juekong: '绝空',
  bleach_juekong_info: "其他角色回合结束时,若其回合内未使用牌且未造成伤害,你可以对其造成1点<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰冻</a>伤害.",
  bleach_honglian: '红莲',
  bleach_honglian_info: '觉醒技,当你拥有12枚「冰莲华」标记时,你回复1点体力或摸两张牌,获得【龙霰】和【花葬】【冰晶】;当你于「始解」时扣减体力或失去手牌后,你获得双倍/等量枚的「冰莲华」标记(至多12枚).',
  bleach_bingjing: '冰晶',
  bleach_bingjing_info: '锁定技,当你受到伤害或因弃置失去牌后,你摸一张牌并弃置1枚「冰莲华」标记,若你没有「冰莲华」,你失去因【红莲】获得的技能并令【红莲】视为未发动.',
  bleach_longxian: '龙霰',
  bleach_longxian_info: "当你使用【杀】指定唯一目标后,你可以移去2枚「冰莲华」标记,令此【杀】对其造成伤害后,其获得1层<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_ice');\">冻伤</a>.",
  bleach_huazang: '花葬',
  bleach_huazang_info: "出牌阶段,若你至少拥有5枚「冰莲华」标记,你可以移去3枚「冰莲华」标记令一名处于<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_ice');\">冻结</a>状态的角色弃置一张牌.其的手牌/体力/武将状态/异常变化时,其获得等量/1枚「冰花」标记,十位数发生变化时获得1层冻伤,当其获得第100枚时,其死亡.",
  bleach_bocun: '狛村左阵',
  bleach_myouou: '黑绳天谴明王',
  bleach_tianqian: '天谴',
  bleach_tianqian_info: '出牌阶段,若你装备区有武器牌且不为斩魄刀,你可以观看牌堆顶的五张牌,获得其中任意与该牌颜色相同的牌并装备【天谴】.',
  bleach_mingwang: '明王',
  bleach_mingwang_info: "限定技,出牌阶段,你可以失去至多3点体力并与一名其他角色各获得等量层<a style='color: #808080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_shield');\">护盾</a>且直到你进入濒死前:1.其受到伤害后,你受到伤害来源等量伤害;2.你造成伤害后,其对受伤角色造成等量伤害.",
  bleach_re_jingshangzhiji: '井上织姬',
  bleach_reguidun: '归盾',
  bleach_reguidun_info: '每名角色的结束阶段,若你于此回合内失去过牌,你可以为一名角色选择(选项号至多为你失去牌数):1.回复1点体力上限或移去1层异常状态;2.回复1点体力或摸两张牌;3.复活并将体力回复至1;4.复原一个限定技.',
  bleach_rejiedun: '结盾',
  bleach_rejiedun_info: '每回合限一次,当一名其他角色使用伤害牌指定唯一目标时,你可以与其拼点:若你赢,取消所有目标.',
  bleach_hougyoku_lanran: '崩蓝染惣右介',
  bleach_hougyoku_lanran_prefix: '崩',
  bleach_lingya: '灵压',
  bleach_lingya_info: '每轮开始时,你可以令一名体力值不小于你的角色失去1点体力,若其体力值小于你或为1,改为你弃置其的一张牌,若其为你,你摸已损体力张牌.',
  bleach_diehua: '蝶化',
  bleach_diehua_info: "觉醒技,当你因其他角色,或失去体力而进入濒死状态时,你减少1点体力上限,将体力回复至2,你的灵溢改为永续状态,你获得1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>和【光瞬】【黑棺】【意志】,并将任意区域的【崩玉】移出游戏且你视为装备之.",
  bleach_heiguan: '黑棺',
  bleach_heiguan_info: "限定技,出牌阶段,你可以拼点:没赢的角色受到对方造成1点<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>伤害,若为你赢则概率即死且附带<a style='color: #FFA500' href=\"javascript:window.bleachIntroduce('damagekill');\">斩杀</a>效果.",
  bleach_guangshun: '光瞬',
  bleach_guangshun_info: '你计算与其他角色的距离时-1;每回合限一次,当你受到伤害后,你可以令其他角色计算与你的距离时+2,直到你下回合开始.',
  bleach_yizhi: '意志',
  bleach_yizhi_info: '觉醒技,结束阶段,若你体力值为1且为全场最低或本回合内受到过伤害,你将体力上限调整至3,回满体力,获得【再生】和【辐破】.',
  bleach_newzaisheng: '再生',
  bleach_newzaisheng_info: "<spanstyle='font-family:yuanli'>「完全再生」</span>锁定技,当你受到大于1的伤害/濒死状态回复体力时,此值-1/+1.",
  bleach_fupo: '辐破',
  bleach_fupo_info: '出牌阶段限一次,你可以弃置一张武器牌并对一名其他角色造成1点火焰伤害.',
  bleach_findorr: '芬朵尔·凯利亚司',
  bleach_findorr_ab: '芬朵尔',
  bleach_pomian: '破面',
  bleach_pomian_info: '出牌阶段,你可以废除一个有牌的装备栏,摸三张牌并弃置一张牌.',
  bleach_zhedao: '蜇刀',
  bleach_zhedao_info: '出牌阶段限一次,你可以交给一名其他角色一张装备牌并视为对其使用一张【虚闪】.',
  bleach_shanben: '山本元柳斋重国',
  bleach_shanben_ab: '山本元柳斋',
  bleach_tianding: '天顶',
  bleach_tianding_info: '准备阶段,你可以将至多两张牌当【杀】使用(无距离限制),此牌目标角色不能使用或打出与此牌颜色相同的手牌至回合结束,若你以此法使用了:两张牌,此牌伤害值+1;一张武器牌,你令一名其他角色失去1点体力.',
  bleach_huozang: '火葬',
  bleach_huozang_info: "出牌阶段限一次,若你已损失体力值不小于4,你可以减少1点体力上限对一名其他角色造成1点<a style='color: #FFA500' href=\"javascript:window.bleachIntroduce('damagekill');\">斩杀</a>火焰伤害.",
  bleach_huting: '护庭',
  bleach_huting_info: '主公技,锁定技,其他尸势力角色攻击范围内的角色均视为在你攻击范围内.',
  bleach_hisaki: '桧佐木修兵',
  bleach_fengsi: '风死',
  bleach_fengsi_info: '出牌阶段限两次,当你使用基本牌或普通锦囊牌指定目标后(两次牌名不得相同),你可以将此牌额外结算一次并置于牌堆顶.',
  bleach_caoguan: '草冠宗次郎',
  bleach_bingxi: '冰袭',
  bleach_bingxi_info: "每回合限一次,当你使用【杀】或普通锦囊牌指定唯一目标后,你可以改为对其造成1点<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰冻</a>伤害.",
  bleach_wangyin: '王印',
  bleach_wangyin_info: "限定技,出牌阶段,你可以弃置任意张副类别不同的装备牌,对任意名其他角色造成共计等量点附带<a style='color: #A67D3D' href=\"javascript:window.bleachIntroduceBuff('bleachMark_zhongshang');\">重伤</a>的<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰冻</a>伤害.",
  bleach_maozhihualie: '卯之花烈',
  bleach_nasha: '雫唼',
  bleach_nasha_info: '摸牌阶段,你可以改为视为对至多四名角色使用一张【五谷丰登】.',
  bleach_huidao: '回道',
  bleach_huidao_info: '出牌阶段限一次,你可以令一名角色摸两张牌或回复1点体力,若其的体力值与手牌数相同,本阶段本技能限两次.',
  bleach_starrk: '柯雅泰·史塔克',
  bleach_starrk_ab: '史塔克',
  bleach_fenhun: '分魂',
  bleach_fenhun_info: '锁定技,当你使用装备牌后,你摸一张牌或弃置其他角色一张牌;你的手牌上限为你的体力上限.',
  bleach_wxxushan: '虚闪',
  bleach_wxxushan_info: '出牌阶段限两次,你可以将伤害牌当【虚闪】使用.',
  bleach_wxxushan1: '修改一',
  bleach_wxxushan1_info: '出牌阶段限两次,你可以将伤害或装备牌当【虚闪】使用;你使用【虚闪】无次数限制且非转化的【虚闪】结算两次.',
  bleach_qunlang: '群狼',
  bleach_qunlang_info: '限定技,回合开始时,你可以减1点体力上限并:1.获得【狼魂】和X+1枚「狼」标记并回复等量点体力;2.修改【虚闪】并摸X张牌(至多为5).你获得一个基础*灵魂*(X为你本局内使用过的装备牌数).',
  bleach_langhun: '狼魂',
  bleach_langhun_info: '当你受到致命或至少2点伤害时,你须移去2枚「狼」(不足则全弃),防止此伤害.当你不因本技能造成伤害后,你可以移去1枚「狼」并对其造成1点雷电伤害.',
  bleach_re_banmu: '斑目一角',
  bleach_manre: '慢热',
  bleach_manre_info: '锁定技,当你造成或受到伤害后,或每回合第一次因弃置失去不含【杀】的牌后,你摸一张牌.',
  bleach_longwen: '龙纹',
  bleach_longwen_info: '觉醒技,当你受到致命伤害时,若你已因【慢热】获得了至少11张牌且与你距离1以内的其他角色数不大于2,则你防止该伤害,回复1点体力值并摸两张牌且本局内你造成伤害+X.(X为你因【慢热】获得的牌数除以9,向下取整)',
  bleach_re_grimmjow: '葛力姆乔·贾卡杰克',
  bleach_re_grimmjow_ab: '葛力姆乔',
  bleach_rexunjie: '迅捷',
  bleach_rexunjie_info: '转换技,每回合限两次,当你使用或打出一张牌后,你可以:阳:摸一张牌;阴:弃置一名角色一张牌,你弃置一张牌,若此次弃置牌中包含2种颜色,你对一名其他角色造成1点伤害.',
  bleach_baowang: '豹王',
  bleach_baowang_info: '觉醒技,当被【迅捷】过的其他角色回复体力或摸牌阶段外获得至少两张牌后,你减少1点体力上限并获得【豹爪】,被【迅捷】过的其他角色依次弃置一张牌.',
  bleach_baozhua: '豹爪',
  bleach_baozhua_info: "当你受到伤害后,你可以视为使用一张无距离限制且附带<a style='color: #FF6666' href=\"javascript:window.bleachIntroduceBuff('bleachMark_lieshang');\">裂伤</a>与<a style='color: #A67D3D' href=\"javascript:window.bleachIntroduceBuff('bleachMark_zhongshang');\">重伤</a>效果的<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>【杀】并废除一个装备栏,若你因此失去了牌,你摸两张牌.",
  bleach_re_wuerqiaola: '乌尔奇奥拉·西法',
  bleach_re_wuerqiaola_ab: '乌尔奇奥拉',
  bleach_zhengfu: '征服',
  bleach_zhengfu_info: '隐匿.当你登场后,你可以令一名角色选择:1.令你观看其的手牌并获得其中一张;2.你对一名与其距离1以内的另一名其他角色造成1点伤害.其执行一个结束阶段.',
  bleach_heiyi: '黑翼',
  bleach_heiyi_info: "觉醒技,每回合结束时,若你的手牌数与体力值相差2或更多,你减1点体力上限,获得1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>与【光锐】和【再生】,所有其他角色须依次弃置一张牌,或失去1点体力.",
  bleach_guangrui: '光锐',
  bleach_guangrui_info: '当你每轮首次使用一种花色的牌后,你可以弃置攻击范围内的一名角色一张牌;当你第四次发动本技能时,你获得【虚无】.',
  bleach_xuwu: '虚无',
  bleach_xuwu_info: '限定技,出牌阶段,你可以摸两张牌或回复1点体力并修改【再生】,获得【雷枪】且失去【光锐】.',
  bleach_rezaisheng: '再生',
  bleach_rezaisheng_info: '每回合限一次,当你的手牌于回合内因弃置而进入弃牌堆时,你可以回复1点体力;当你处于濒死时,你可以移去本段描述并将体力回复至3,每个回合结束时,你失去1点体力.',
  bleach_leiqiang: '雷枪',
  bleach_leiqiang_info: '出牌阶段,你可以选择一名其他角色并展示手牌,你弃置其中一种花色的牌,展示其一张手牌,若这两张牌花色不同,你对其造成雷电1点伤害,若你未以此法造成伤害,此技能失效至回合结束.',
  bleach_yaluoniluo: '亚罗尼洛·艾鲁鲁耶利',
  bleach_yaluoniluo_ab: '亚罗尼洛',
  bleach_tongzhi: '同知',
  bleach_tongzhi_info: '隐匿.当你于回合外登场后,你可以令当前回合角色展示手牌并交给你一张牌.',
  bleach_tunshi: '吞噬',
  bleach_tunshi_info: '回合开始或回合结束时,你可以:将「吞噬」牌补至两张;更换置顶「吞噬」牌以视为拥有对应技能.当「破面」死亡后,你可以将其的武将牌置入「吞噬」并加1点体力上限且回复1点体力.',
  bleach_canxu: '喰虚',
  bleach_canxu_info: '觉醒技,结束阶段,若你体力值为1,你回满体力,失去【吞噬】并获得「吞噬」与随机两张「破面」武将牌中的获得至多两个技能,执行一个额外回合.',
  bleach_2022_shitianyulong: '石田雨龙',
  bleach_guangyu: '光雨',
  bleach_guangyu_info: '出牌阶段限一次,你可以展示牌堆顶四张牌,并使用其中的牌(无距离和次数限制).结算完毕前,【杀】的目标+1.',
  bleach_re_xiumuluqiya: '朽木露琪亚',
  bleach_yuebai: '月白',
  bleach_yuebai_info: "限定技,出牌阶段,你可以将座次移动至一名其他角色的下家,视为对其使用一张附带<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_ice');\">冻伤</a>的<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰</a>【杀】,此回合结束后,因此跳过回合的角色执行一个额外回合.",
  bleach_bailian: '白涟',
  bleach_bailian_info: "每轮结束时,你可以对一名其他角色造成X点<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰冻</a>伤害且冻伤值改为X(X为你本轮失去牌满足项数:1.最后的手牌;2.三种不同类型;3.四种不同花色).",
  bleach_bairen: '白刃',
  bleach_bairen_info: "限定技,出牌阶段,你可以重铸至多两张牌,装备【袖白雪】并获得1层<a style='color: #00FFFF' href=\"javascript:window.bleachIntroduceBuff('bleachMark_up');\">灵溢</a>.",
  bleach_2022_chad: '茶渡泰虎',
  bleach_newmoji: '魔击',
  bleach_newmoji_info: '当你使用【杀】或【决斗】首次指定目标后,你可以对一名手牌数不小于你的目标角色造成1点伤害.',
  bleach_newlingbi: '灵臂',
  bleach_newlingbi_info: '你可以重铸两张同名牌或装备牌视为使用一张与本轮未以此法使用过的基本牌.',
  bleach_baiyihu: '白一护',
  bleach_zhanyue: '斩月',
  bleach_zhanyue_info: '你使用的普通【杀】可以视为火【杀】;你使用火【杀】指定目标后,其技能失效至回合结束.',
  bleach_xuanren: '旋刃',
  bleach_xuanren_info: '出牌阶段限一次,你可以令一名其他角色秘密猜测你使用的下一张牌的类型,若其猜错且此牌的目标中:有其,其不能响应此牌;没有其,其弃置一张牌.',
  bleach_newbankai: '卍解',
  bleach_newbankai_info: "觉醒技,当你体力值或手牌数减少至1时,你减少1点体力上限,回复1点或摸两张牌,你获得【月衝】和【本能】且使用的下一张【杀】改为对目标造成等量<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>伤害.",
  bleach_newyuechong: '月衝',
  bleach_newyuechong_info: '摸牌阶段结束时,你可以将一张牌当无视距离的【杀】使用.',
  bleach_newbenneng: '本能',
  bleach_newbenneng_info: '每轮限一次,当你成为【杀】的目标后,你可以弃置X张牌,令此【杀】无效(X为对应的实体牌数量);你于一回合内使用第偶数张牌时,若为伤害牌,你摸一张牌.',
  bleach_re_heiqiyihu: '黑崎一护',
  bleach_reyuechong: '月衝',
  bleach_reyuechong_info: '摸牌阶段结束时,你可以将一张牌当无视距离的【杀】使用.每回合你使用的首张【杀】需两张【闪】才能抵消且此牌目标角色本回合仅锁定技标签的技能和防具失效(转化牌、虚拟牌除外).',
  bleach_hollow: '虚化',
  bleach_hollow_info: "限定技,结束阶段,若你本回合造成的伤害值:大于等于3点,你可以获得【完虚】;小于等于3,你可以获得1层<a style='color: #808080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_shield');\">护盾</a>且本局内有护盾时使用【杀】的伤害值+1.你回复1点体力或摸两张牌.",
  bleach_wanxu: '完虚',
  bleach_wanxu_info: "觉醒技,当你即将死亡时,你防止之并将体力回复至3,【月衝】失效且获得以下效果直到你令一名角色进入濒死状态:出牌阶段开始/结束时,你视为使用一张附带<a style='color: #A67D3D' href=\"javascript:window.bleachIntroduceBuff('bleachMark_zhongshang');\">重伤</a>的【虚闪】/随机目标且不能被响应的【杀】.",
  bleach_sp_lanran: 'SP蓝染惣右介',
  bleach_sp_lanran_prefix: 'SP',
  bleach_spjinghua: '镜花',
  bleach_spjinghua_info: '限定技,出牌阶段,你可以摸一张牌并将一张牌置于牌堆任意位置:当其他角色失去该牌时,你对其造成1点伤害并令其使用的同类牌均失效直到下回合开始.',
  bleach_duankong: '断空',
  bleach_duankong_info: '你可以将一种类型手牌当【断空】或【无懈可击】使用并摸三张牌(每种类型限一次).',
  bleach_yeren: '夜刃',
  bleach_yeren_info: '当你使用单目标牌指定目标后,你可以:若其没有「夜刃」牌,你可以将其一张手牌置于其武将牌上;若其有「夜刃」牌,你可以令一名角色获得其的「夜刃」牌.',
  bleach_baraggan: '拜勒冈·鲁伊森邦',
  bleach_baraggan_ab: '拜勒冈',
  bleach_zhiyue: '掷钺',
  bleach_zhiyue_info: '当你受到1点伤害或死亡时,你可以令一名其他角色判定并将【灭亡之斧】置入装备区/其装备区,若结果为黑色,你对其造成1点伤害.',
  bleach_fuxiu: '腐朽',
  bleach_fuxiu_info: '出牌阶段限一次,你可摸一张牌,将一张手牌交给一名其他角色.一名角色获得你的牌时,其须弃置两张其他牌,否则失去1点体力.',
  bleach_dulou: '髑髅',
  bleach_dulou_info: '限定技,出牌阶段,若你装备区有牌且为最多,你可以减1点体力上限,将【腐朽】的<体力>改为<体力上限>.',
  bleach_xuye: '虚夜',
  bleach_xuye_info: '主公技,当你获得其他虚势力角色的牌后,你可以令其摸一张牌.',
  bleach_zombie_dongshilang: 'SP日番谷冬狮郎',
  bleach_zombie_dongshilang_ab: 'SP冬狮郎',
  bleach_zombie_dongshilang_prefix: 'SP',
  bleach_renfeng: '刃锋',
  bleach_renfeng_info: "当你造成伤害时,你可以失去1点体力令伤害+1且改为<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰冻</a>伤害.",
  bleach_shilian: '尸莲',
  bleach_shilian_info: '锁定技,你进入濒死状态时,将手牌数摸至4,若为本轮第一次进入濒死状态,则你回复1点体力.',
  bleach_jiadisi: '嘉蒂丝·卡特尼普',
  bleach_jiadisi_ab: '嘉蒂丝',
  bleach_leiting: '雷霆',
  bleach_leiting_info: '当你使用或打出基本牌后,你可以判定,若结果与此牌花色相同,你摸两张牌,否则你将之置于武将牌上.',
  bleach_shenting: '神霆',
  bleach_shenting_info: '觉醒技,准备阶段,若你有至少三张「雷霆」,你加1点体力上限并回复1点体力,获得【电刑】.',
  bleach_dianxing: '电刑',
  bleach_dianxing_info: '出牌阶段限一次,你可以移去任意张「雷霆」并对一名其他角色造成等量点雷电伤害,若其因此死亡,你可以对其的邻家造成1点雷电伤害.',
  bleach_gremmy: '葛雷密·托缪',
  bleach_gremmy_ab: '葛雷密',
  bleach_mengxiang: '梦想',
  bleach_mengxiang_info: '你可以将一张牌当你上轮至今未使用过的基本牌或普通锦囊牌使用(每回合每种类型各限一次).',
  bleach_funeng: '赋能',
  bleach_funeng_info: '「硬化」:当你每回合首次受到伤害时,若你的手牌数大于体力,你令伤害-1.你的手牌上限始终为3.<br>「陨石」:出牌阶段限一次,若此回合内置入弃牌堆的牌包含四种花色,你可以对一名其他角色与其邻家各造成1点伤害.<br>「空间」:洗牌回合结束时,你可以令一名成为过「陨石」目标的角色猜测牌堆顶的首张牌的花色,若其猜错,其失去1点体力并重复此流程.',
  bleach_haschwalth: '雨葛兰·哈斯沃德',
  bleach_haschwalth_ab: '哈斯沃德',
  bleach_tiaohe: '调和',
  bleach_tiaohe_info: '出牌阶段,每名角色限一次,你可以为一名角色选择一项: <li>①其的「幸运」标记数较多:<br>&nbsp;&nbsp;&nbsp;1.其随机弃置一张牌并移去1枚「幸运」标记.<br>&nbsp;&nbsp;&nbsp;2.其摸一张牌并移去1枚「不幸」标记.<li>②你的「幸运」标记数较多:<br>&nbsp&nbsp;&nbsp;1.你弃置其一张牌并移去其1枚「不幸」标记.<br>&nbsp&nbsp;&nbsp;2.其摸两张牌并移去1枚「幸运」标记.<li>③你们「幸运」标记数相等:<br>&nbsp&nbsp;&nbsp;1.移去其1枚「幸运」令其弃置一张牌.<br>&nbsp;&nbsp;&nbsp;2.移去其1枚「不幸」令其摸两张牌',
  bleach_tiaohe_append: '<span style="font-family:yuanli">游戏规则:当一名角色造成或受到伤害后,其获得1枚「幸运」或「不幸」标记.</span>',
  bleach_zuidun: '罪盾',
  bleach_zuidun_info: '出牌阶段限一次,你可以:1.弃置一张防具牌将体力回复至上限并获得等量枚「不幸」;2.弃置四张不同花色的牌并移去所有「不幸」对一名其他角色造成与移去标记数等量点伤害.',
  bleach_ashido: '阿西多',
  bleach_dunfan: '盾反',
  bleach_dunfan_info: '当一名你距离1以内的角色成为伤害牌的目标后,你可以声明一种花色并判定,若结果与声明花色的:相同,使用者改为你,目标改为原使用者;不同,你获得判定牌并交给其一张牌或令其获得该牌,本技能失效至回合结束.',
  bleach_xinyang: '信仰',
  bleach_xinyang_info: '每回合限一次,你使用的【杀】或普通锦囊牌可以额外指定一名与你不同势力的角色为目标.',
  bleach_yeyisuifeng: '四枫院夜一&碎蜂',
  bleach_yeyisuifeng_ab: '夜一碎蜂',
  bleach_congshu: '从属',
  bleach_congshu_info: '出牌阶段限一次,你可以拼点:若你赢:你可以使用一张拼点牌(无距离限制);你获得【瞬哄】或【蜂纹华】直到回合结束.',
  bleach_re_dongxian: '东仙要',
  bleach_luchou: '戮仇',
  bleach_luchou_info: '出牌阶段开始时,你可以展示任意张伤害牌并摸等量张牌.出牌阶段结束时,若你本回合造成伤害值小于以此法摸牌数,你受到1点雷电伤害.',
  bleach_yuanque: '圆缺',
  bleach_yuanque_info: '锁定技,当你每回合首次造成或受到伤害后,你摸X张牌(X为你使用过的技能数)并弃置已损失体力张手牌.你可以使用【虚闪】.',
  bleach_kuangjia: '狂枷',
  bleach_kuangjia_info: '限定技,结束阶段,你可以加1点体力上限并回复X点体力(X为你本回合造成伤害值),获得【百式】.',
  bleach_baishi: '百式',
  bleach_baishi_info: "锁定技,出牌阶段结束时,你失去1点体力或一个技能视为使用一张无视距离的<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>【杀】.",
  bleach_maozhihuabaqianliu: '卯之花八千流',
  bleach_jianliu: '剑流',
  bleach_jianliu_info: '锁定技,你始终装备【肉雫霎】,你可以将武器牌当未以此法使用过的伤害牌使用(【杀】每种属性限一次)并弃置一名目标角色区域内一张牌;你每回合内首次使用【杀】指定目标,或成为其他角色使用【杀】的目标后,你与其各摸一张牌.当你死亡时,可以令一名其他角色获得你武器栏的牌.',
  bleach_jianliu1: '修改一',
  bleach_jianliu1_info: '锁定技,你始终装备【肉雫霎】且可以将♦️️牌或武器牌当未以此法使用过的伤害牌使用(【杀】每种属性限一次)并弃置一名目标角色区域内一张牌;你每回合内首次使用【杀】指定目标,或成为其他角色使用【杀】的目标后,你与其各摸一张牌.当你死亡时,可以令一名其他角色获得你武器栏的牌.',
  bleach_jiejin: '皆尽',
  bleach_jiejin_info: '限定技,回合开始时,若场上角色均已受伤,你可以减少1点体力上限,回复1点体力,修改并复原【剑流】,直到有角色死亡前:一名角色进入濒死状态时,其减少1点体力上限,将体力值回复至2并重铸所有牌;当你造成伤害后,其失去1点体力(有概率即死).',
  bleach_zhulian: '朱莲',
  bleach_yehuo: '业火',
  bleach_yehuo_info: '当你需要使用或打出火【杀】时,你可以横置一名本回合未以此法选择过的角色视为使用或打出之.你防止传导的火焰伤害并摸一张牌.',
  bleach_liaoyuan: '燎原',
  bleach_liaoyuan_info: "当你的非黑色牌被响应后,你可以对一名与其距离1以内的其他角色施加1层<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>.",
  bleach_sazayelaporro: '萨尔阿波罗·古兰兹',
  bleach_sazayelaporro_ab: '萨尔阿波罗',
  bleach_luling: '录灵',
  bleach_luling_info: '当你受到伤害或当前回合角色第二次造成伤害后,你可以弃置其一张牌或令其锁定技失效至其下回合开始.',
  bleach_yaoxu: '药虚',
  bleach_yaoxu_info: '出牌阶段限一次,你可以与一名其他角色交换一张手牌,若这两张牌花色相同,你对其造成1点伤害或回复1点体力.',
  bleach_xiefei: '邪妃',
  bleach_xiefei_info: '觉醒技,当你脱离受伤状态后,你获得【偶戏】和【受胎】.',
  bleach_ouxi: '偶戏',
  bleach_ouxi_info: '出牌阶段限一次,你可以弃置一张牌并令一名其他角色摸一张牌,对其造成X点伤害(X为其区域内与弃置牌花色相同牌的数量).',
  bleach_shoutai: '受胎',
  bleach_shoutai_info: '限定技,当你处于濒死状态时,你可以弃置一名你对其造成过伤害的其他角色一张牌,若与以此法弃置的上一张牌类型不同,重复此流程,你回复至X点体力(X为弃置牌的类型数).',
  bleach_zommari: '佐马利路鲁',
  bleach_zhouai: '咒爱',
  bleach_zhouai_info: "出牌阶段,你可以声明一种伤害锦囊牌<span class='hrefnode'>并弃置一张非基本牌</span>,将一名其他角色的随机一张牌当声明牌视为由其使用,若目标与使用者相同或其未受到伤害,本回合本技能失效.",
  bleach_sengjia: '僧伽',
  bleach_sengjia_info: '觉醒技,当你使用本轮你使用过的牌后,你回复1点体力或摸两张牌并移去【咒爱】的划线字符.',
  bleach_snxiangzhuan: '响转',
  bleach_snxiangzhuan_info: '「双儿响转」:每轮限一次,当你使用牌时,若你手牌颜色相同,你可以令此牌额外结算一次.若你手牌颜色相同,你使用牌没有距离限制.',
  bleach_tybw_quebu: '雀部长次郎',
  bleach_fuxi: '伏袭',
  bleach_fuxi_info: '每回合限一次,当一名其他角色成为另一名其他角色使用【杀】的唯一目标后,你可以将一张牌当【杀】对其使用,若此牌造成伤害,你弃置其一张牌,否则你成为目标.',
  bleach_zhongxi: '忠息',
  bleach_zhongxi_info: '限定技,回合开始时,你可以选择一名其他角色:本局内你或其一次性获得两张牌后,对方摸一张牌;你或其死亡时,对方视为对伤害来源使用一张【杀】.',
  bleach_ligong: '离宫',
  bleach_ligong_info: '限定技,出牌阶段,你可以将一张牌置于牌堆顶并判定X+1次(X为你装备区的牌数),若判定结果为♠️️,你对一名角色造成1点雷电伤害;你可以视为使用一张无距离限制且伤害为X的雷【杀】(X为黑色判定牌的数量且至少为1).',
  bleach_tybw_shanben: '山本元柳斋重国',
  bleach_tybw_shanben_ab: '山本元柳斋',
  bleach_zhuoren: '灼刃',
  bleach_zhuoren_info: "锁定技,你使用【杀】首次指定目标后,对其与相邻的角色各施加1层<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>,你的烧伤改为抵消等量伤害.每阶段限一次,当你于摸牌阶段外摸牌后,你可以将这些牌当【杀】使用.",
  bleach_jiehuo: '劫火',
  bleach_jiehuo_info: "限定技,出牌阶段,你可以对所有角色施加2层<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>,本局内你使用【杀】时,你可以移去1层烧伤,令伤害值+1.",
  bleach_lushi: '戮实',
  bleach_lushi_info: '主公技,锁定技,场上尸势力角色使用【杀】的限制次数+1.',
  bleach_yibang: '阿兹基尔罗·伊邦',
  bleach_yibang_ab: '伊邦',
  bleach_lingpao: '灵炮',
  bleach_lingpao_info: '出牌阶段,你可以将一张本阶段内未以此法转化过字数的牌当本回合进入弃牌堆的第等量张牌使用.',
  bleach_xingzhang: '星章',
  bleach_xingzhang_info: '限定技,「死神」的回合开始时,你可以令其一个觉醒技或限定技失效至其获得【虚闪】.',
  bleach_wonderweiss: '旺达怀斯·马尔杰拉',
  bleach_wonderweiss_ab: '旺达怀斯',
  bleach_qixi: '奇袭',
  bleach_qixi_info: '每轮限一次,其他角色的回合开始时,你可以弃置一张牌,对其造成1点伤害.',
  bleach_huochu: '火储',
  bleach_huochu_info: '锁定技,当有角色受到火焰伤害后,你加1点体力上限并回复1点体力(至多为游戏人数),你选择是否失去本技能以获得【灭火】.',
  bleach_miehuo: '灭火',
  bleach_miehuo_info: '锁定技,你防止不以此法造成的火焰伤害.当你进入濒死状态时,你对你与任意名其他角色造成1点火焰伤害.',
  bleach_jiaji: '贾姬·特里斯坦',
  bleach_jiaji_ab: '贾姬',
  bleach_zanghun: '葬魂',
  bleach_zanghun_info: '其他角色每回合首次使用与「泥」花色相同的牌时,你可以对其造成1点伤害,你须选择一项:1.用一张与场上「泥」花色均不同的牌替换其的「泥」;2.令其重铸所有「泥」.',
  bleach_jianni: '溅泥',
  bleach_jianni_info: '当你对没有「泥」的角色使用牌生效后,你可以将之置于其武将牌上,称为「泥」.有角色弃置与「泥」花色相同的牌后,你摸一张牌.',
  bleach_xina: '茜雫',
  bleach_juanfeng: '卷枫',
  bleach_juanfeng_info: '每名角色的结束阶段,你可以将此回合内置入弃牌堆的所有♣️️牌当【杀】使用,可以将一张非♣️️牌置于牌堆顶,剩余牌置于牌堆底.每轮限两次.',
  bleach_sanyi: '散忆',
  bleach_sanyi_info: '当你死亡时,你可以令一名其他角色从牌堆顶和牌堆底各摸一张牌,你令其获得一张弃牌堆内的红色牌.',
  bleach_sunsun: '荪荪',
  bleach_xiuwu: '袖舞',
  bleach_xiuwu_info: '每回合限两次,当你成为【杀】的目标后,你可以重铸一张牌,令一名牌数大于你手牌数的角色弃置一张牌,若重铸牌点数大于弃置牌,此牌对你无效.',
  bleach_shejiao: '蛇绞',
  bleach_shejiao_info: '出牌阶段限一次,你可以重复重铸一张牌直至点数不能递增,若你至少重铸三张牌,你令一名其他角色选择一项:1,弃置两张牌;2,你视为对其使用一张无视距离的【杀】.',
  bleach_liuche: '六车拳西',
  bleach_duanfeng: '断风',
  bleach_duanfeng_info: '当你使用「伤害」牌指定其他角色为目标后,若此牌是你本回合使用的第X张牌(X为你的手牌数),你可以对一名目标造成1点伤害并令其随机弃置一张牌.',
  bleach_duanfeng1: '修改一',
  bleach_duanfeng1_info: '当你使用牌指定其他角色为目标后,若此牌是你本回合使用的第X张牌(X为你的手牌数或此牌牌名字数),你可以对一名目标造成1点伤害并令其随机弃置一张牌.',
  bleach_tiequan: '铁拳',
  bleach_tiequan_info: '觉醒技,当你失去4种花色的牌后,你减1点体力上限,回复1点体力或摸两张牌,将【断风】改为其他牌或等于此牌牌名字数也可以发动.',
  bleach_jilian: '基力安',
  bleach_yuanheng: '怨恨',
  bleach_yuanheng_info: '锁定技,摸牌/弃牌阶段,你改为将手牌数摸/弃至体力值/已损体力值.',
  bleach_nianheng: '念恨',
  bleach_nianheng_info: '锁定技,回合结束时,若你本回合弃置过牌,你视为使用一张【虚闪】.',
  bleach_senjumaru: '修多罗千手丸',
  bleach_senjumaru_ab: '千手丸',
  bleach_zhenshang: '臻裳',
  bleach_zhenshang_info: '出牌阶段限一次,你可以检索一张防具并置于一名其他角色的装备区内(替换原装备),根据其区域内能被查看牌面信息的牌的颜色数:红色较多,交给你手牌中颜色较少的所有牌并回复半量体力值(向上取整);黑色较多,其须弃置手牌中颜色较多的牌,否则失去1点体力.',
  bleach_tongci: '恫辞',
  visible_bleach_tongci: '恫辞',
  bleach_tongci_info: '每回合每名角色限一次,当其他角色因响应牌而使用牌时,若其已成为过黑色牌的目标,你可以弃置一张牌令此牌无效,其明置两张手牌并受到你造成的1点伤害.',
  bleach_haishi: '骸辻',
  bleach_haishi_info: '限定技,出牌阶段,若友方有阵亡角色且【臻裳】和【恫辞】发动次数之和与友方阵亡数比值不小于6,你可以为至多6名其他角色编织一个其下回合结束的濒死事件.所有事件结算完毕前,你受到致命伤害时,该伤害-1.当你濒死时,删除未生效的编织事件并将体力回复至2点.',
  bleach_zangetsu: '斩月',
  bleach_yingyu: '影域',
  bleach_yingyu_info: '每轮结束时,你可以令一名本轮体力变化过的角色执行一个额外回合,该回合内,除你和指定目标外均不可被选中,该回合结束时,若其造成过伤害,其摸一张牌或获得一张武器牌且你执行另一项,否则其失去1点体力.',
  bleach_hufeng: '护锋',
  bleach_hufeng_info: '限定技,当一名角色受到伤害时,你可以防止此伤害并令其回复1点体力或摸两张牌,其本局内使用【杀】后摸一张牌.',
  bleach_8th_heiqiyihu: '黑崎一护',
  bleach_daofeng: '刀锋',
  bleach_daofeng_info: '每回合限一次,你可以将重铸两张牌视为使用一张无视防具【杀】,根据两者相同项执行:名称,不计入次数限制;点数,目标技能失效至回合结束.若均为武器牌,你回复1点体力或摸一张牌.',
  bleach_candao: '参道',
  bleach_candao_info: '游戏开始时,你将牌堆中点数最大和最小的随机两张牌置于武将上,称为「道」.你使用点数为「道」之间的即时牌时,你摸一张牌并用该牌替换一张「道」,若两张「道」的点数相邻,你重铸所有「道」.',
  bleach_caolubaqianliu: '草鹿八千流',
  bleach_mujian: '慕剑',
  bleach_mujian_info: '锁定技,每轮你首次使用一种类型的牌后摸1张牌、第三张牌若与此前两张牌的类型皆相同或不同,你摸或多摸3张牌.',
  bleach_driscoll: '多利斯克·贝尔希',
  bleach_driscoll_ab: '多利斯克',
  bleach_nuesha: '虐杀',
  bleach_nuesha_info: '当你:1.获得或弃置其他角色装备牌后;2.击杀一名角色后;3.每造成4点伤害.你摸X张牌(X为序号数)并展示,这些牌无距离和次数限制.',
  bleach_spligong: '离宫',
  bleach_spligong_info: '限定技,出牌阶段,你可以展示牌堆顶你装备区的牌数张牌,对一名其他角色造成X点雷电伤害且叠满<a style="color: #FDF8CC" href=\'javascript:window.bleachIntroduce("bleachThunder");\'>雷蛰</a>值(X为展示的黑色牌数).',
  bleach_jiunanbai: '久南白',
  bleach_feiti: '飞踢',
  bleach_feiti_info: '当你不因本技能使用伤害基本或锦囊牌后,你可以视为执行另一项,选择一项:1.失去1点体力;2.移去1层<a style="color: #808080" href=\'javascript:window.bleachIntroduceBuff("bleachMark_shield");\'>护盾</a>.',
  bleach_chaobai: '超白',
  bleach_chaobai_info: '当你使用【杀】首次指定目标后,你可以弃置至多三张牌并获得等量层<a style="color: #808080" href=\'javascript:window.bleachIntroduceBuff("bleachMark_shield");\'>护盾</a>,你下个回合结束时,你移去所有护盾并摸等量张牌.',
  bleach_bai: '白',
  bleach_tybwbenneng: '本能',
  bleach_tybwbenneng_info: '锁定技,每回合你使用的首张伤害牌无次数限制且伤害值+1.当你进入濒死状态时,你选择是否将牌堆顶的牌当【出其不意】使用,若如此做,你死亡.',
  bleach_baihao: '白嚎',
  bleach_baihao_info: '每回合限一次,当其他角色使用无标签或仅带有锁定技标签的技能后,你可以将一张牌当无距离限制的【杀】对其或其相邻的角色使用,你本回合内下次受到伤害+1.',
  bleach_re_lanran: '蓝染惣右介',
  bleach_rejinghua: '镜花',
  bleach_rejinghua_info: '游戏开始时或洗牌回合结束时,牌堆中随机十三牌称为「镜花」.1.「镜花」不可被响应且不计入你的手牌上限;2.其他角色使用「镜花」时,你可以将目标改为非目标(无目标则此牌无效).',
  bleach_yumou: '预谋',
  bleach_yumou_info: '当你未蓄谋累计使用或打出至少X张牌后(X为你已损失的体力值),你可以摸X张牌并蓄谋.蓄谋【杀】造成伤害后,你可以对另一名角色使用之,蓄谋【闪】可如手牌般使用或打出,蓄谋【桃】【酒】濒死状态使用之.',
  bleach_yuhe: '玉合',
  bleach_yuhe_info: '觉醒技,每名角色的回合结束时,若本回合牌堆进行过洗牌,你获得1层<a style="color: #00FFFF" href=\'javascript:window.bleachIntroduceBuff("bleachMark_up");\'>灵溢</a>和【破茧】,并令【镜花】失效.',
  bleach_pojian: '破茧',
  bleach_pojian_info: '觉醒技,每轮结束时,若你本轮造成与受到伤害值相差至少3点,你减1点体力上限,获得【灵威】并复原【镜花】.',
  bleach_lingwei: '灵威',
  bleach_lingwei_info: '出牌阶段,你可以令一名其他角色失去1点体力,此技能失效至其死亡或回复体力,其因此进入濒死状态后,本技能失效至回合结束.',
  bleach_yihui: '议会',
  bleach_yihui_info: '主公技,出牌阶段限一次,你可以令所有同势力角色选择是否议事,若结果为:红色,你们各摸一张牌.黑色,你可以令一名未参与议事的同势力角色失去1点体力.',
  bleach_tybw_gengmu: '更木剑八',
  bleach_pozhi: '破桎',
  bleach_pozhi_info: '锁定技,当你脱离受伤或濒死状态后,你检索一张伤害牌,重置或回复1点体力上限.',
  bleach_jiangui: '剑鬼',
  bleach_jiangui_info: '锁定技,当你成为或指定伤害牌的目标后,你横置并摸X张牌(X为此牌的牌名字数).',
  bleach_egui: '惡鬼',
  bleach_egui_info: '限定技,当你处于濒死状态时,你可以重置并将体力回复至1,视为对体力值最大的所有角色使用一张不能被响应的【杀】,你不能回复体力至本轮结束.',
  bleach_jiexing: '截星',
  bleach_jiexing_info: '每轮限一次,当其他角色即将造成非牌的伤害时,你可以弃置一张武器牌并摸已损失体力张牌,防止此伤害.',
  bleach_asnodt: '艾斯诺特',
  bleach_kongju: '恐惧',
  bleach_kongju_info: '出牌阶段限一次,你可以观看一名其他角色的手牌并向其以外的角色展示其中一张,其可以弃置至多两张手牌,若其未失去展示牌,你对其造成1点伤害.',
  bleach_yingjing: '樱景',
  bleach_yingjing_info: '限定技,出牌阶段,你可以摸两张牌,可以弃置两张手牌并使用其中一张牌.你以此法使用牌后,本回合结束时重置本技能.',
  bleach_qienuo: '怯懦',
  bleach_qienuo_info: '觉醒技,弃牌阶段结束时,若你本阶段的弃牌数大于体力值,你加1点体力上限,回满体力并失去【樱景】,获得【惶悸】,场上角色不能因牌回复体力直到你死亡.',
  bleach_huangji: '惶悸',
  bleach_huangji_info: '锁定技,当你造成或受到非牌的伤害后,伤害来源回复1点体力或摸一张牌.',
  bleach_sb_lanran: '蓝染惣右介',
  bleach_weiya: '威压',
  bleach_weiya_info: '每轮开始时,若你的手牌数为每轮首次达到,你可以摸三张牌并展示一张手牌,你本轮手牌上限+X(X为此牌牌名字数).每轮结束时,你弃置展示的手牌以令一名其他角色失去1点体力.',
  bleach_cuifeng: '摧锋',
  bleach_cuifeng_info: '每回合结束时,你可以将一张牌当本回合弃牌堆中唯一的普通锦囊牌或伤害牌使用.',
  bleach_royd: '洛伊德罗伊德',
  bleach_duoqu: '夺取',
  bleach_duoqu_info: '出牌阶段限一次,你可以弃置任意张牌并获得等量其他角色各一张牌,若你以此法获得了至少两张牌,你失去1点体力.',
  bleach_shengyu: '圣域',
  bleach_shengyu_info: '限定技,当你成为或指定【杀】的目标后,你可以展示牌堆顶五张牌,可以使用其中任意张(无距离和次数限制).',
  bleach_tybw_pingzi: '平子真子',
  bleach_tybwnifu: '逆抚',
  bleach_tybwnifu_info: '每回合限一次,你可以将一张牌当任意【杀】或【闪】使用或打出,此牌没有距离和次数限制.',
  bleach_daoxuan: '倒悬',
  bleach_daoxuan_info: '每轮开始时,你可以与一名其他角色本轮【杀】【闪】颠倒.每回合首张底牌与牌名不同的牌被使用后,你摸一张牌.',
  bleach_xiesai: '邪塞',
  bleach_xiesai_info: '限定技,出牌阶段,你可以令所有其他角色依次将一张牌当【杀】对其造成伤害最小的另一名角色使用,你可以视为使用一张无距离限制的【杀】.',
  bleach_tybw_liuche: '六车拳西',
  bleach_fengqie: '风切',
  bleach_fengqie_info: '锁定技,每回合限一次,当你的手牌数或体力值首次变化至与另一项相等后,你回复1点体力或对攻击范围内一名角色造成1点伤害.',
  bleach_suzhan: '速战',
  bleach_suzhan_info: '锁定技,回合开始时,你受到1点伤害并摸一张牌,执行一个额外的出牌阶段.',
  bleach_tybwduanfeng: '断风',
  bleach_tybwduanfeng_info: '限定技,出牌阶段,你可以减少1点体力上限且:1.摸三张牌;2.弃置至少半数手牌.并于此阶段结束时执行另一项.',
  bleach_yhwach: '友哈巴赫',
  bleach_shengchang: '圣唱',
  bleach_shengchang_info: '限定技,转换技,出牌阶段,阳:你可以声明一种牌的类别且直到你下回合开始前,当你成为其他角色使用的声明类别牌的目标后,你视为对使用者使用一张【杀】.阴:你可以对自己造成1点伤害,观看牌堆顶的五张牌并使用之.',
  bleach_hunke: '魂刻',
  bleach_hunke_info: '获得或弃置过你牌的角色死亡时,你摸两张牌或回复1点体力;出牌阶段限一次,你可以弃置一张红色牌令一名没有「圣文字」的角色于其下个结束阶段随机获得一个「圣文字」,若其为你,则改为复原你一个其他技能.',
  bleach_shengbie: '圣别',
  bleach_shengbie_info: '限定技,出牌阶段,你可以令任意名「灭却师」或有「圣文字」的角色失去1点体力,你可以将该值再分配.',
  bleach_cuanduo: '篡夺',
  bleach_cuanduo_info: '限定技,出牌阶段,你可以获得一名其他角色的一个技能直到使用后或你死亡(期间其该技能失效).',
  bleach_test: '测试',
  bleach_test_info: '测试',
  bleach_hougyoku_wuerqiaola: '崩乌尔奇奥拉·西法',
  bleach_hougyoku_wuerqiaola_ab: '崩乌尔奇奥拉',
  bleach_hougyoku_wuerqiaola_prefix: '崩',
  bleach_zhousheng: '昼升',
  bleach_zhousheng_info: '每轮限一次,你造成或受到伤害的回合结束后,你可以执行一个仅有对应阶段的回合并摸一张牌.',
  bleach_lanke: '岚刻',
  bleach_lanke_info: '当你每回合体力值首次变化后,你可以弃置其他角色一张牌.',
  bleach_fengbao: '风暴',
  bleach_fengbao_info: "每当你以正面向上失去或弃置其他角色共4种花色的牌后,你可以视为对至多四名角色使用一张附带<a style='color: #800080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_weak');\">虚弱</a>和<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>的【虚闪】.",
  bleach_5th_heiqiyihu: '魂黑崎一护',
  bleach_5th_heiqiyihu_prefix: '魂',
  bleach_jili: '既力',
  bleach_jili_info: '当你造成1点伤害后,你可以重铸一张牌,横置受伤角色并摸一张牌.',
  bleach_suotian: '锁天',
  bleach_suotian_info: "出牌阶段限一次,你可以将任意张牌当无距离和次数限制的且附带等量层<a style='color: #800080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_weak');\">虚弱</a>的<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>【杀】使用.",
  bleach_5th_xiumubaizai: '魂朽木白哉',
  bleach_5th_xiumubaizai_prefix: '魂',
  bleach_dijian: '帝剑',
  bleach_dijian_info: '结束阶段,或当你成为【杀】的目标后,你可以使用一张本回合内进入弃牌堆的牌.每种牌名每回合限一次.',
  bleach_wangjing: '望景',
  bleach_wangjing_info: "准备阶段,你可以与一名其他角色各摸一张牌并弃置一张牌;当一名角色于其回合内首次受到伤害后,你摸一张牌并获得1层<a style='color: #FFFFFF' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_wudi');\">无敌</a>.",
  bleach_us_dongshilang: '魂日番谷冬狮郎',
  bleach_us_dongshilang_ab: '魂冬狮郎',
  bleach_us_dongshilang_prefix: '魂',
  bleach_liaoshuang: '缭霜',
  visible_bleach_liaoshuang: '缭霜',
  bleach_liaoshuang_info: '当你使用牌指定其他角色为唯一目标后,你可以明置其一张手牌,以此法明置的牌本回合不能使用或打出.',
  bleach_shuanghua: '霜华',
  bleach_shuanghua_info: "当你受到1点伤害后,你可以摸一张牌,你可以与伤害来源拼点:若你赢,视为对其使用一张<a style='color: #97CBFF' href=\"javascript:window.bleachIntroduce('bleachIce');\">冰</a>【杀】.",
  burnthewitch_xinqiao: '新桥诺艾尔',
  burnthewitch_linmian: '林冕',
  burnthewitch_linmian_info: '出牌阶段限一次,你可以展示一张牌并置于牌堆顶,展示牌堆顶的十五张牌,将点数相同的牌依次当无距离限制的【杀】使用.',
  burnthewitch_mielong: '減龍',
  burnthewitch_mielong_info: "摸牌阶段,你可以改为对一名其他角色造成1点<a style='color: #FFFF00' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_break');\">破防</a>伤害,若其于本回合内死亡,你于回合结束时摸两张牌.",
  burnthewitch_nini: '妮妮·斯庞柯尔',
  burnthewitch_nini_ab: '妮妮',
  burnthewitch_yulun: '雨轮',
  burnthewitch_yulun_info: '出牌阶段,你可以令本回合的手牌上限-1(至少为0)视为使用一张弃牌堆内有同名牌且洗牌前未以此法使用过即时牌(无距离限制).',
  burnthewitch_guangbi: '光壁',
  burnthewitch_guangbi_info: '每轮限一次,当有角色于你回合外受到伤害时,你可以令当前回合角色摸两张牌,若其手牌数大于你,则防止此伤害,本轮结束时,你摸X张牌(X为你连续发动本技能的轮数).',
  burnthewitch_bruno: '布鲁诺·邦古耐夫',
  burnthewitch_bruno_ab: '布鲁诺',
  burnthewitch_beke: '贝克',
  burnthewitch_beke_info: '准备阶段,你可以猜测牌堆顶的牌的颜色并展示之,若你猜对,你对一名其他角色造成1点雷电伤害.',
  burnthewitch_mozhen: '魔阵',
  burnthewitch_mozhen_info: '转换技,阳:当你于一回合内失去第二张手牌时,你可以视为使用一张基本牌;阴:当你使用与本回合上一张使用的牌颜色相同的手牌后,你可以摸一张牌或随机使用一张装备牌.',
  burnthewitch_shiying: '食影',
  burnthewitch_shiying_info: '限定技,出牌阶段,你可以弃置一张手牌,并令一名手牌数不小于你的其他角色重复随机弃置牌直到与你弃置牌颜色不同,若其的手牌数小于你,你对其造成1~2点随机伤害.',
  bleach_quincy_heiqiyihu: '黑崎一护',
  bleach_newxuezhuang: '血装',
  bleach_newxuezhuang_info: '锁定技,【全力】每有一个技能,你的手牌上限和攻击范围便+1.',
  bleach_quanli: '全力',
  bleach_quanli_info: '回合开始时,你可以视为拥有以下一个技能:【汲灵】/【月冲】/【再生】且你可以使用【虚闪】.当你受到伤害后,你可以失去其中一个技能摸两张牌.',
  bleach_shanguang: '闪光',
  bleach_shanguang_info: "限定技,出牌阶段,若你【全力】的技能数为3,你可以对一名其他角色造成1点伤害并附加1层<a style='color: #AFEEEE' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_qinshi');\">侵食</a>和<a style='color: #800080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_weak');\">虚弱</a>",
  bleach_7th_heiqiyihu: '黑崎一护',
  bleach_dangying: '荡影',
  bleach_dangying_info: '出牌阶段限一次,你可以观看牌堆顶四张牌,你可以使用其中一张牌并横置目标角色.',
  bleach_chiyu: '赤雨',
  bleach_chiyu_info: "出牌阶段,你可以重置一名本阶段未以此法选择过的角色并将其一张牌当附带<a style='color: #800080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_weak');\">虚弱</a>和<a style='color: #FDF8CC' href=\"javascript:window.bleachIntroduceBuff('bleachMark_leizhe');\">雷蛰</a>的【杀】使用.",
  bleach_7th_shitianyulong: '石田雨龙',
  bleach_cheshan: '澈閃',
  bleach_cheshan_info: '摸牌阶段,你可以选择一项视为使用一张无距离限制的【杀】:1.多摸一张牌并于出牌阶段开始时弃置一张牌;2.少摸一张牌并于出牌阶段结束时摸两张牌.',
  bleach_qingguang: '晴光',
  bleach_qingguang_info: "转换技,每当你以正面向上失去了4种花色的牌后,你可以对一名其他角色造成1点伤害并施加1层:阳:<a style='color: #800080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_weak');\">虚弱</a>;阴:<a style='color: #AFEEEE' href=\"javascript:window.bleachIntroduceBuff('bleachEffect_qinshi');\">侵食</a>.你下次使用【澈闪】的伤害+1或你下次受到的伤害-1.",
  bleach_yk_grimmjow: '鬼葛力姆乔·贾卡杰克',
  bleach_yk_grimmjow_ab: '鬼葛力姆乔',
  bleach_yk_grimmjow_prefix: '鬼',
  bleach_yushou: '狱手',
  bleach_yushou_info: "锁定技,你使用的伤害牌没有距离限制且附带1层随机<font color='red'>异常</font>.",
  bleach_luosheng: '罗生',
  bleach_luosheng_info: "当有<font color='red'>异常</font>状态的角色使用牌指定你为目标后,你可以移去其1层异常状态令此牌对你无效.",
  bleach_yk_shiwanyin: '鬼市丸银',
  bleach_yk_shiwanyin_prefix: '鬼',
  bleach_huanyu: '幻愈',
  bleach_huanyu_info: '结束阶段或当你成为【杀】的目标后,你可以令一名其他角色交给你一张牌.',
  bleach_huhuo: '狐火',
  bleach_huhuo_info: "限定技,出牌阶段,你可以对任意名角色施加2层<a style='color: #FF3333' href=\"javascript:window.bleachIntroduceBuff('bleachMark_fire');\">烧伤</a>,并对随机一名目标造成1点火焰伤害.",
  bleach_yk_baiyihu: '鬼白一护',
  bleach_yk_baiyihu_prefix: '鬼',
  bleach_qiannu: '迁怒',
  bleach_qiannu_info: '当你不因本技能击杀一名角色后,你可以对场上所有其他角色造成1点伤害;你于回合内使用第二张牌时,你可以令此牌额外结算一次.',
  bleach_zhenmie: '真灭',
  bleach_zhenmie_info: "限定技,出牌阶段,你可以弃置任意张牌对等量其他角色施加1层<a style='color: #800080' href=\"javascript:window.bleachIntroduceBuff('bleachMark_weak');\">虚弱</a>并令这些角色技能失效至回合结束,你对这些角色首次造成伤害后施加1层<a style='color: #A67D3D' href=\"javascript:window.bleachIntroduceBuff('bleachMark_zhongshang');\">重伤</a>.",
  bleach_cacao_wuerqiaola: '可乌尔奇奥拉·西法',
  bleach_cacao_wuerqiaola_ab: '可乌尔奇奥拉',
  bleach_cacao_wuerqiaola_prefix: '可',
  bleach_shenyuan: '深渊',
  bleach_shenyuan_info: '当你造成伤害后,你可以依次亮出牌堆顶X张牌并使用直到你无法使用(X为伤害值),这些牌不能指定你和其以外的角色为目标.',
  bleach_machine_jiliang: '机吉良伊鹤',
  bleach_machine_jiliang_prefix: '机',
  bleach_lundu: '轮赌',
  bleach_lundu_info: '出牌阶段限一次,你可以选择一名其他角色,你与其轮流翻开检索的六张牌并获得其中一张直到一方亮出红牌(先手可设置红牌的数量),其受到2点伤害,若不为你,此技能视为未发动过,另一名角色摸两张牌.',
  bleach_swimsuit_jiadisi: '泳嘉蒂丝·卡特尼普',
  bleach_swimsuit_jiadisi_ab: '泳嘉蒂丝',
  bleach_swimsuit_jiadisi_prefix: '泳',
  bleach_ganong: '伽农',
  bleach_ganong_info: '当你使用或打出一张本轮未使用过的基本牌或伤害牌后,你可以摸一张牌.',
  bleach_miexing: '灭刑',
  bleach_miexing_info: '每轮结束时,你可以令一名其他角色判定(目标不得与上轮相同),若结果为黑色,你视为对其依次使用两张雷【杀】.',
  bleach_future_nnoitra: '诺伊特拉·吉尔加',
  bleach_future_nnoitra_ab: '诺伊特拉',
  bleach_yinyi: '银翼',
  bleach_yinyi_info: '锁定技,转换技,阳:当你造成牌的伤害后;阴:当你响应其他角色使用的牌后.你获得该牌,并将一张牌置于武将牌上,称为「翼」.周始:你摸一张牌.',
  bleach_fensui: '粉碎',
  bleach_fensui_info: '当你每回合使用的第一张【杀】指定唯一目标后,你可以弃置你或其一张牌,若以此法弃置了♣️️牌,你将之置入「翼」.',
  bleach_sitan: '斯坦',
  bleach_sitan_info: '每轮限一次,每回合结束时,你可移去三至五张「翼」并执行一个额外的回合,该回合内你使用第X张牌后结束出牌阶段且【杀】没有距离和次数限制(X为你移去的「翼」数).',
  soul_johnwick: '约翰威克',
  soul_shashen: '杀神',
  soul_shashen_info: '出牌阶段限两次,你可以重铸至少两张相同类型的牌并令一名其他角色选择一项:1.交给你等量张相同类型的牌;2.受到1点斩杀伤害.',
  soul_zhuisha: '追杀',
  soul_zhuisha_info: '锁定技,当与你相邻的友方受到敌方的伤害后(包含自己),伤害来源下次受到你造成的伤害+1.',
  soul_dukemon: '红莲骑士兽',
  soul_honglian: '红莲',
  soul_honglian_info: '锁定技,回合开始时,你获得一个额外的武器栏(每局限一次),你将【冈尼尔】或【布尔特根】置入装备区.',
  soul_junxiang: '君向',
  soul_junxiang_info: '限定技,出牌阶段,若你装备区有【冈尼尔】,你可以令任意名其他角色依次须打出一张【闪】,否则你对其造成1点伤害,因此受到伤害的角色下三回合结束时失去1点体力.',
  soul_jijian: '极剑',
  soul_jijian_info: '出牌阶段限一次,若你装备区有【布尔特根】,你可以弃置一张装备牌对一名其他角色造成1点伤害.',
  soul_luohou: '罗睺',
  soul_fenghuan: '奉还',
  soul_fenghuan_info: '锁定技,当你成为或指定【杀】的目标后,你获得1枚「战意」标记.当你的「战意」标记数不小于12时,你移去所有「战意」标记并对所有敌方角色造成1~4点随机伤害.',
  soul_biri: '蔽日',
  soul_biri_info: '转换技,出牌阶段,你可以:阳:失去1点体力,可以视为使用一张无距离和次数限制的【杀】;阴:回复1点体力,可以代替一名其他角色下次成为【杀】的目标.',
  soul_yeyu: '夜雨',
  soul_yeyu_info: '锁定技,当你失去体力,或受到伤害后,你获得1枚「战意」标记并摸等量张牌.当你回复体力后,若你体力值不大于2,你获得1层<a style="color: #808080" href=\'javascript:window.bleachIntroduceBuff("bleachMark_shield");\'>护盾</a>.',
  soul_erlangshen: '二郎显圣真君',
  soul_liangyi: '两仪',
  soul_liangyi_info: '持恒技,你不能成为延时锦囊牌的目标;当你获得异常状态时,改为附加至你的下两张伤害牌.',
  soul_fengmu: '凤目',
  soul_fengmu_info: '当你成为【杀】或普通锦囊牌的目标后,你可以弃置一张装备牌令此牌对你无效,你摸一张牌.',
  soul_wufeng: '舞凤',
  soul_wufeng_info: '限定技,出牌阶段,你可以依次使用牌堆前4X张牌中所有【杀】(不能超过游戏人数,X为你本阶段造成伤害数).',
  soul_shenfeng: '神锋',
  soul_shenfeng_info: '持恒技,若你的装备区里没有武器牌/防具牌/坐骑牌,你视为装备着【三尖两刃刀】/【青釭剑】/【贯石斧】.',
  soul_agentsmith: '特工史密斯',
  soul_tonghua: '同化',
  soul_tonghua_info: '锁定技,当你即将造成的伤害大于等于该角色的体力值,你防止此伤害并令其将阵营和武将替换至与你一致.',
  soul_quanxian: '权限',
  soul_quanxian_info: '你可以将牌堆顶的两张牌如手牌般使用或打出.',
  image_aizen: '*蓝染惣右介 立于天上*',
  image_aizen2: '*蓝染惣右介 第一融合阶段*',
  image_aizen3: '*蓝染惣右介 第四融合阶段*',
  image_ichigo: '*黑崎一护 卍解*',
  image_ichigo2: '*黑崎一护 半虚化*',
  image_ichigo3: '*黑崎一护 面具碎裂*',
  image_ichigo4: '*黑崎一护 虚化*',
  image_yamamoto: '山本元柳斋 流刃若火',
  image_burnthewitch: '*龙与魔女*',
  image_furoufushi: '*斋藤不老不死*',
  image_rukia: '*朽木露琪亚卍解*',
  image_yhwach: '*友哈巴赫灵王*',
  image_xiaohujing: '*小虎鲸*',
  image_yinlianhua: '*温热的银莲花*',
  image_baihehua: '*百合花*',
  image_constantine: '*康斯坦丁*',
  image_constantine2: '*地狱神探*',
  image_johnwick: '*约翰威克*',
  image_izayoisakuya: '*十六夜·咲夜*',
  image_theamazingspiderman: '*超凡蜘蛛侠*',
  image_spidermanvenomsuit: '*蜘蛛侠毒液战衣*',
  image_theshawshankredemption: '*肖申克的救赎*',
  image_vladimir: '*弗拉基米尔*',
  image_brucelee: '*李小龙*',
  image_kamennaite: '*卡门奈特*',
  tuidilichang: '退敌立场',
  tuidilichang_info: '<a style="color: rgba(225,245,245,1)">当你体力扣减至1时,结束当前回合敌方角色当前阶段.</a>',
  duoluoshengdun: '堕落圣盾',
  duoluoshengdun_info: '<a style="color: rgba(225,245,245,1)">当你获得不可叠加异常状态或受到非卡牌伤害时,防止之(1局限1次).</a>',
  lingqiao: '灵巧',
  lingqiao_info: '<a style="color: rgba(225,245,245,1)">使用【杀】的限制次数+1.</a>',
  dali: '大力',
  dali_info: '<a style="color: rgba(225,245,245,1)">获得*攻击*.</a>',
  soulziyu: '自愈',
  soulziyu_info: '<a style="color: rgba(225,245,245,1)">你的回复和护盾值35%几率+1.</a>',
  yisun: '易损',
  yisun_info: '<a style="color: rgba(225,245,245,1)">你使用普通锦囊牌的结算次数可以被会心.获得5%会心几率.</a>',
  huixinfangshou: '会心防守',
  huixinfangshou_info: '<a style="color: rgba(225,245,245,1)">你可以使用会心几率(至多60%几率)来进行会心防御,使你所受伤害-1.获得5%会心几率.</a>',
  taifeng: '台风',
  taifeng_info: '<a style="color: rgba(225,245,245,1)">你使用【杀】有50%概率随机指定一名敌方为额外目标.</a>',
  tianyinbao: '天音爆',
  tianyinbao_info: '<a style="color: rgba(225,245,245,1)">当你令友方获得护盾或回复体力后,对其的邻家敌方1点破防伤害.</a>',
  zengyixiongdi: '增益兄弟',
  zengyixiongdi_info: '<a style="color: rgba(225,245,245,1)">你的手牌上限与攻击范围+1.</a>',
  zhiyeshashou: '职业杀手',
  zhiyeshashou_info: '<a style="color: rgba(225,245,245,1)">每轮开始时,随机标记一个敌方角色至该轮结束:其本轮首次进入濒死状态时,友方各摸两张牌.</a>',
  equwei: '恶趣味',
  equwei_info: '<a style="color: rgba(225,245,245,1)">施加异常状态后35%概率回复1点体力.</a>',
  huolihuanfa: '活力焕发',
  huolihuanfa_info: '<a style="color: rgba(225,245,245,1)">你可以跳过出牌阶段和弃牌阶段并回复2点体力(15回合冷却).</a>',
  soulbaoshi: '暴食',
  soulbaoshi_info: '<a style="color: rgba(225,245,245,1)">获得2点体力上限.</a>',
  soulqinshi: '侵蚀',
  soulqinshi_info: '<a style="color: rgba(225,245,245,1)">你的【杀】无视防具.</a>',
  soulbingfeng: '冰封',
  soulbingfeng_info: '<a style="color: rgba(225,245,245,1)">出牌阶段限一次,你可以拼点:若你赢,对其施加1层冻伤.</a>',
  youling: '幽灵',
  youling_info: '<a style="color: rgba(225,245,245,1)">你每失去7张牌,你对本回合最后一个出牌的敌方角色施加1层冻结.</a>',
  lingyabaofa: '灵压爆发',
  lingyabaofa_info: '<a style="color: rgba(225,245,245,1)">获得1层灵溢.</a>',
  binghan: '冰寒',
  binghan_info: '<a style="color: rgba(225,245,245,1)">其他角色计算与你的距离时+1.</a>',
  dianliangtamen: '点亮他们',
  dianliangtamen_info: '<a style="color: rgba(225,245,245,1)">每使用四张基本或装备牌,你摸一张牌.</a>',
  reshendongzuo: '热身动作',
  reshendongzuo_info: '<a style="color: rgba(225,245,245,1)">结束阶段,你可以重铸牌并重复此流程直到点数不能递增,每重铸3张牌,你下等量次造成伤害+1.</a>',
  haiyanglonghun: '海洋龙魂',
  haiyanglonghun_info: '<a style="color: rgba(225,245,245,1)">当你造成伤害后,有15%概率回复1点体力.</a>',
  xueqiaozhanshu: '雪橇战术',
  xueqiaozhanshu_info: '<a style="color: rgba(225,245,245,1)">回合开始时,你从牌堆中获得一张坐骑牌.</a>',
  caijueshi: '裁决使',
  caijueshi_info: '<a style="color: rgba(225,245,245,1)">每轮首次对体力值半数取下的敌方造成伤害+1.参与击杀后重置你的基础技能.</a>',
  mingdaosiming: '名刀司命',
  mingdaosiming_info: '<a style="color: rgba(225,245,245,1)">当你受到致命伤害时,防止此伤害(1局限1次).</a>',
  qiangyuzhihu: '强欲之壶',
  qiangyuzhihu_info: '<a style="color: rgba(225,245,245,1)">摸两张牌.</a>',
  jingjiyi: '荆棘Ⅰ',
  jingjiyi_info: '<a style="color: rgba(225,245,245,1)">当你受到敌方造成的伤害后,对伤害来源造成1点伤害(1轮冷却).</a>',
  zhuanshenti: '转神体',
  zhuanshenti_info: '<a style="color: rgba(225,245,245,1)">你选择一个未发动的觉醒技,使之无视发动条件.</a>',
  tuisheng: '蜕生',
  tuisheng_info: '<a style="color: rgba(225,245,245,1)">本轮参与击杀敌方后,随机治疗两名友军.</a>',
  liziqiu: '栗子球',
  liziqiu_info: '<a style="color: rgba(225,245,245,1)">为友方抵挡下次伤害(1副牌堆冷却).</a>',
  xiangsiersheng: '向死而生',
  xiangsiersheng_info: '<a style="color: rgba(225,245,245,1)">你的会心几率提升(+5%*已损失体力值).</a>',
  wuxiuhuifu: '无休回复',
  wuxiuhuifu_info: '<a style="color: rgba(225,245,245,1)">你每使用或打出十张牌,回复1点体力.</a>',
  soulshouhu: '守护',
  soulshouhu_info: '<a style="color: rgba(225,245,245,1)">获得*防御*.</a>',
  soulwanmei: '完美',
  soulwanmei_info: '<a style="color: rgba(225,245,245,1)">每轮结束时,若你本轮使用过三种类型/四种花色的牌,则你摸满足项张数的牌.</a>',
  jiankang: '健康',
  jiankang_info: '<a style="color: rgba(225,245,245,1)">获得*体力*',
  huiwan: '会玩',
  huiwan_info: '<a style="color: rgba(225,245,245,1)">当你使用<出牌阶段限一次>的技能后,你令此技能视为未发动(1回合冷却).',
  jinghuashuiyue: '镜花水月',
  jinghuashuiyue_info: '<a style="color: rgba(225,245,245,1)">当你成为伤害牌的目标后,若你体力为1,你可以将之转移给其他角色(1局限1次).',
  chaoyuesiwang: '超越死亡',
  chaoyuesiwang_info: '<a style="color: rgba(225,245,245,1)">当你进入濒死状态时,你将体力回复至4,每回合结束时失去1点体力直到与击杀角色(1局限1次).',
  kexue: '渴血',
  kexue_info: '<a style="color: rgba(225,245,245,1)">你造成的伤害后,回复1点体力(5回合冷却).',
  fuchoutianshi: '复仇天使',
  fuchoutianshi_info: '<a style="color: rgba(225,245,245,1)"><li>任务:为队友回复或提供共4点体力/护盾.<li>奖励:使用【杀】次数限制和伤害+1.',
  weikuaibupo: '唯快不破',
  weikuaibupo_info: '<a style="color: rgba(225,245,245,1)">你所有牌的点数比目标越大,则对其造成越多的伤害.',
  soulsiyi: '死疫',
  soulsiyi_info: '<a style="color: rgba(225,245,245,1)">本轮参与击杀后,获得20层诅咒能量.<li>每20层诅咒能量,摸牌数便+1.',
  xieduzhe: '亵渎者',
  xieduzhe_info: '<a style="color: rgba(225,245,245,1)">弃置敌方装备牌后对其施加1层5回合的诅咒.<li>诅咒:每回合从敌方诅咒中获得等量诅咒能量.<li>根据诅咒能量获得概率减伤.',
  fushiji: '腐蚀剂',
  fushiji_info: '<a style="color: rgba(225,245,245,1)">对敌方造成属性伤害后施加1层5回合的诅咒.<li>诅咒:每回合从敌方诅咒中获得等量诅咒能量.<li>每回合首次造成伤害施加12.5%诅咒能量的中毒.',
  xuriren: '旭日刃',
  xuriren_info: '<a style="color: rgba(225,245,245,1)">【杀】即将造成的伤害改为扣减体力.',
  faze: '法则',
  faze_info: '<a style="color: rgba(225,245,245,1)">获得*灵压*.',
  jiuzhulingren: '救主灵刃',
  jiuzhulingren_info: '<a style="color: rgba(225,245,245,1)">当你体力值即将扣减至半数取下时,你获得2层护盾(1局限1次).',
  naijiu: '耐久',
  naijiu_info: '<a style="color: rgba(225,245,245,1)">当你受到伤害后,你回复1点体力(8回合冷却).',
  lianyulonghun: '炼狱龙魂',
  lianyulonghun_info: '<a style="color: rgba(225,245,245,1)">当你造成伤害后,有15%概率对其造成1点火焰伤害.',
  shunshen: '瞬神',
  shunshen_info: '<a style="color: rgba(225,245,245,1)">你不能成为延时锦囊牌的目标.',
  shizuizhe: '食罪者',
  shizuizhe_info: '<a style="color: rgba(225,245,245,1)">友方获得异常状态时,改为你获得之.',
  zhongjishou: '重击手',
  zhongjishou_info: '<a style="color: rgba(225,245,245,1)">你造成的伤害有体力上限*6%概率+1.',
  shanmailonghun: '山脉龙魂',
  shanmailonghun_info: '<a style="color: rgba(225,245,245,1)">每轮开始时,若你没有护盾且上轮没有造成或受到过伤害,你获得1层护盾.',
  zhipaimoshu: '纸牌魔术',
  zhipaimoshu_info: '<a style="color: rgba(225,245,245,1)">当你使用【杀】时,不公开指定目标,你令一名角色选择是否打出一张基本牌.若其为目标且未打出牌,则其不能响应此牌;若其不为目标且打出了牌,你摸两张牌(1回合冷却).',
  ziwohuimie: '自我毁灭',
  ziwohuimie_info: '<a style="color: rgba(225,245,245,1)">十个回合后,对你和与你距离为1的敌方造成2点破防伤害.',
  shoumingyutian: '受命于天',
  shoumingyutian_info: '<a style="color: rgba(225,245,245,1)">获得你武将牌上的主公技.',
  lianjinlonghun: '炼金龙魂',
  lianjinlonghun_info: '<a style="color: rgba(225,245,245,1)">半数取下体力时获得10%概率增减伤1点.',
  jifenglonghun: '疾风龙魂',
  jifenglonghun_info: '<a style="color: rgba(225,245,245,1)">你计算与其他角色距离时-1.',
  fuchouzhexunzhang: '复仇者勋章',
  fuchouzhexunzhang_info: '<a style="color: rgba(225,245,245,1)">造成的每点伤害有12%概率+1.',
  bengyuyizhi: '崩玉意志',
  bengyuyizhi_info: '<a style="color: rgba(235,210,128,1)">你拥有【崩玉】的装备效果.</a>',
  gushijialiang: '古式佳酿',
  gushijialiang_info: '<a style="color: rgba(235,210,128,1)">你在使用技能后有20%概率回复1点体力.</a>',
  moguizhiwu: '魔鬼之舞',
  moguizhiwu_info: '<a style="color: rgba(235,210,128,1)">获得*灵压*与*体力*.</a>',
  xiangong: '先攻',
  xiangong_info: '<a style="color: rgba(235,210,128,1)">你进入战斗阶段结束时,若你造成过伤害,你摸两张牌且本回合手牌上限+2(4回合冷却).</a>',
  linghunranshao: '灵魂燃烧',
  linghunranshao_info: '<a style="color: rgba(235,210,128,1)">获得*攻击*和*会心*.</a>',
  wangdezhizi: '王的资质',
  wangdezhizi_info: '<a style="color: rgba(235,210,128,1)">获得1点额外体力,且你可以使用【虚闪】.</a>',
  soulkuwei: '枯萎',
  soulkuwei_info: '<a style="color: rgba(235,210,128,1)">对敌方造成的伤害会施加4回合的35%(+5%*其已损失体力值)概率伤害削减1点.</a>',
  jurendeyoubi: '巨人的右臂',
  jurendeyoubi_info: '<a style="color: rgba(235,210,128,1)">你或你队友受到的伤害会被格挡(8回合冷却).</a>',
  emodezuobi: '恶魔的左臂',
  emodezuobi_info: '<a style="color: rgba(235,210,128,1)">你使用【杀】的伤害值+1(1回合冷却).</a>',
  huoshangjiaoyou: '火上浇油',
  huoshangjiaoyou_info: '<a style="color: rgba(235,210,128,1)">你使用牌造成的伤害会施加1层烧伤.</a>',
  shengdongjixi: '声东击西',
  shengdongjixi_info: '<a style="color: rgba(235,210,128,1)">出牌阶段限一次,你可以交给一名其他角色一张牌,其交给你队友两张牌.</a>',
  souljianren: '坚韧',
  souljianren_info: '<a style="color: rgba(235,210,128,1)">每名角色的回合开始时,你都有20%概率回复1点体力.</a>',
  linghunhongxi: '灵魂虹吸',
  linghunhongxi_info: '<a style="color: rgba(235,210,128,1)">获得5%会心几率和作用于会心的1点吸血.</a>',
  guanjianhuixin: '关键会心',
  guanjianhuixin_info: '<a style="color: rgba(235,210,128,1)">获得15%会心几率.</a>',
  roubaodan: '肉爆弹',
  roubaodan_info: '<a style="color: rgba(235,210,128,1)">出牌阶段,你可以对一名友方和一名敌方各造成2点伤害(1局限1次).</a>',
  soulfuchou: '复仇',
  soulfuchou_info: '<a style="color: rgba(235,210,128,1)">每名阵亡队友提供造成伤害35%+1与35%吸血1点.</a>',
  ziwogongku: '自我巩固',
  ziwogongku_info: '<a style="color: rgba(235,210,128,1)">手牌上限+4.</a>',
  haoling: '号令',
  haoling_info: '<a style="color: rgba(235,210,128,1)">出牌阶段,令你的队友回复1点体力且下回合摸牌阶段摸牌数和使用【杀】的次数+1(1局限1次).</a>',
  soulcanren: '残忍',
  soulcanren_info: '<a style="color: rgba(235,210,128,1)">获得1点*攻击*.</a>',
  chaofanxiee: '超凡邪恶',
  chaofanxiee_info: '<a style="color: rgba(235,210,128,1)">你对敌方使用技能后,摸一张牌.</a>',
  chaoyuezhe: '超越者',
  chaoyuezhe_info: '<a style="color: rgba(235,210,128,1)">当你使用非手牌后,你摸一张牌.</a>',
  soulxisheng: '牺牲',
  soulxisheng_info: '<a style="color: rgba(235,210,128,1)">当你队友每轮第一次受到伤害后,你失去1点体力为其提供2层护盾.</a>',
  chilieliming: '炽烈黎明',
  chilieliming_info: '<a style="color: rgba(235,210,128,1)">你的技能会标记敌方目标,使友方对其造成伤害+1.',
  jianjue: '坚决',
  jianjue_info: '<a style="color: rgba(235,210,128,1)">当你的体力值扣减至一半及以下时(向下取整),你回复2点体力(1局限1次).</a>',
  tianfa: '天罚',
  tianfa_info: '<a style="color: rgba(235,210,128,1)">准备阶段,你可以令一名敌方进行【闪电】判定.</a>',
  wangjian: '王键',
  wangjian_info: '<a style="color: rgba(235,210,128,1)">你免疫异常状态(1回合冷却).</a>',
  chaozhongliwang: '超重力网',
  chaozhongliwang_info: '<a style="color: rgba(235,210,128,1)">场上角色每回合至多使用一张【杀】.</a>',
  jingjier: '荆棘Ⅱ',
  jingjier_info: '<a style="color: rgba(235,210,128,1)">当你受到敌方造成的伤害后,对伤害来源造成1点伤害(1回合冷却).</a>',
  yonggandelinghun: '勇敢的灵魂',
  yonggandelinghun_info: '<a style="color: rgba(235,210,128,1)">额外会心几率提升至5%.获得5%会心几率.</a>',
  chongfenghao: '冲锋号',
  chongfenghao_info: '<a style="color: rgba(235,210,128,1)">出牌阶段,你可以令所有友方角色各摸三张牌(1局限1次).</a>',
  shouhutianshi: '守护天使',
  shouhutianshi_info: '<a style="color: rgba(235,210,128,1)">当你即将死亡时,你改为休整状态至4回合后,回复2点体力并摸三张牌(1局限1次).</a>',
  soulgongshoujianbei: '攻守兼备',
  soulgongshoujianbei_info: '<a style="color: rgba(235,210,128,1)">获得*攻击*和*防御*灵魂.</a>',
  jianduanfamingjia: '尖端发明家',
  jianduanfamingjia_info: '<a style="color: rgba(235,210,128,1)">当你使用装备牌后,你摸一张牌.',
  shushangkaihua: '树上开花',
  shushangkaihua_info: '<a style="color: rgba(235,210,128,1)">出牌阶段限一次,你可以弃置至多两张牌并摸等量牌,若你以此法弃置了装备牌,则多摸一张牌.',
  shenshengzhijian: '神圣之剑',
  shenshengzhijian_info: '<a style="color: rgba(235,210,128,1)">获得5%会心.<br>会心时:<li>随机弃置其一张牌.',
  yigongdaishou: '以攻代守',
  yigongdaishou_info: '<a style="color: rgba(235,210,128,1)">你可以使用满层*攻击*进行化劲,使伤害-1.',
  shenghuo: '圣火',
  shenghuo_info: '<a style="color: rgba(235,210,128,1)">你回复体力或获得护盾后,对最近的邻家施加2层烧伤.',
  toujizhe: '投机者',
  toujizhe_info: '<a style="color: rgba(235,210,128,1)">你使用【杀】或技能有15%概率获得1-5枚「牌」,有敌方死亡后,你提现之.进入濒死状态时,损失25%的「牌」.',
  jieerliansan: '接二连三',
  jieerliansan_info: '<a style="color: rgba(235,210,128,1)">你的每第三张【杀】会结算两次.',
  huixinzhiliao: '会心治疗',
  huixinzhiliao_info: '<a style="color: rgba(235,210,128,1)">你的回复值和护盾可以被会心,使此值+1.获得5%会心几率.',
  chuanzhenyinxian: '穿针引线',
  chuanzhenyinxian_info: '<a style="color: rgba(235,210,128,1)">获得*破防*.',
  mofafeidan: '魔法飞弹',
  mofafeidan_info: '<a style="color: rgba(235,210,128,1)">对敌方使用技能后,随机弃置其一张牌.',
  shenshefashi: '神射法师',
  shenshefashi_info: '<a style="color: rgba(235,210,128,1)">每张手牌都有10%概率使你【杀】的伤害+1.',
  xingyedoupeng: '星夜斗篷',
  xingyedoupeng_info: '<a style="color: rgba(235,210,128,1)">使你受到伤害时有35%(+5%*装备牌数)概率-1.',
  anganglizhua: '暗纲利爪',
  anganglizhua_info: '<a style="color: rgba(235,210,128,1)">你【杀】造成伤害后,随机施加1-2层裂伤.',
  shandiandaji: '闪电打击',
  shandiandaji_info: '<a style="color: rgba(235,210,128,1)">出牌阶段开始时,若你手牌中没有【杀】,则你本回合下次造成伤害前,使用【杀】不需要手牌.',
  heiyueshengqi: '黑月升起',
  heiyueshengqi_info: '<a style="color: rgba(235,210,128,1)">你于出牌阶段内使用首张【杀】不能被响应.',
  jishengguanxi: '寄生关系',
  jishengguanxi_info: '<a style="color: rgba(235,210,128,1)">队友造成的伤害后,你有15%概率回复1点体力.',
  huoliquankai: '火力全开',
  huoliquankai_info: '<a style="color: rgba(235,210,128,1)"><li>任务:本局造成10点伤害.<li>奖励:20%基础*灵魂*.',
  siwangzhiren: '死亡之刃',
  siwangzhiren_info: '<a style="color: rgba(235,210,128,1)">如果你造成的伤害会令其进入濒死状态,则处决其.',
  jujishou: '狙击手',
  jujishou_info: '<a style="color: rgba(235,210,128,1)">你对距离1以外的角色造成伤害后,你摸一张牌.',
  pojing: '破镜',
  pojing_info: '<a style="color: rgba(235,210,128,1)">你的【杀】会使敌方目标非锁定技失效至回合结束.',
  duanjinzhe: '断筋者',
  duanjinzhe_info: '<a style="color: rgba(235,210,128,1)">获得5%会心.<br>会心时:<li>施加1层烧伤.',
  quanxinweini: '全心为你',
  quanxinweini_info: '<a style="color: rgba(235,210,128,1)">你对队友的治疗/护盾+1.',
  shijieliefeng: '实界裂缝',
  shijieliefeng_info: '<a style="color: rgba(235,210,128,1)">造成【杀】或非卡牌伤害后,你展示牌堆顶一张牌并使用(不能指定你和其以外的角色为目标).',
  siwangchumo: '死亡触摸',
  siwangchumo_info: '<a style="color: rgba(235,210,128,1)">你的【杀】会对敌方施加1层5回合的诅咒.<li>诅咒:每回合从敌方诅咒中获得等量诅咒能量.<li>每12层诅咒能量,你的【杀】便有24%概率+1.',
  heranliaobang: '核燃料棒',
  heranliaobang_info: '<a style="color: rgba(235,210,128,1)">施加异常会对敌方目标施加1层5回合的诅咒.<li>诅咒:每回合从敌方诅咒中获得等量诅咒能量.<li>诅咒能量十位数变化时,场上敌方角色各失去1点体力.',
  shuruiyadezhange: '舒瑞娅的战歌',
  shuruiyadezhange_info: '<a style="color: rgba(235,210,128,1)">你的手牌上限+1.友方使用的首张牌没有距离限制.',
  bingdonghudun: '冰冻护盾',
  bingdonghudun_info: '<a style="color: rgba(235,210,128,1)">获得2点*防御*.<li>免疫以下异常:冻伤,冻结.',
  shengqishihudun: '圣骑士护盾',
  shengqishihudun_info: '<a style="color: rgba(235,210,128,1)">获得2点*防御*.<li>免疫以下异常:雷蛰、侵食.',
  heiyaoshihudun: '黑曜石护盾',
  heiyaoshihudun_info: '<a style="color: rgba(235,210,128,1)">获得2点*防御*.<li>免疫以下异常:火焚、烧伤.',
  yingxionghudun: '英雄护盾',
  yingxionghudun_info: '<a style="color: rgba(235,210,128,1)">获得4点*防御*.<li>攻击距离含有你的敌方只能对你使用【杀】.',
  haikesilonghun: '海克斯龙魂',
  haikesilonghun_info: '<a style="color: rgba(235,210,128,1)">你对敌方造成伤害后,对其的随机友方造成1点雷电伤害(1回合冷却).',
  xueqinxiongdi: '血亲兄弟',
  xueqinxiongdi_info: '<a style="color: rgba(235,210,128,1)">获得「伊尔弗特」.',
  huangliang: '荒凉',
  huangliang_info: '<a style="color: rgba(0,255,255,1)">随机获得【离宫】【劫火】【皆尽】之一.</a>',
  shengjizhanfang: '生机绽放',
  shengjizhanfang_info: '<a style="color: rgba(0,255,255,1)">回复体力后对距离最近的敌方造成1点伤害.</a>',
  burucandao: '不入参道',
  burucandao_info: '<a style="color: rgba(0,255,255,1)">每回合开始时,你有5%概率获得1层灵溢.</a>',
  ganshouranshao: '感受燃烧',
  ganshouranshao_info: '<a style="color: rgba(0,255,255,1)">出牌阶段限一次,你可以令随机两名距离1以内的敌方获得2层烧伤.</a>',
  fashusuxing: '法术苏醒',
  fashusuxing_info: '<a style="color: rgba(0,255,255,1)">对敌方使用技能后,视为对其使用一张【杀】.</a>',
  lingwangdeyoushou: '灵王的右手',
  lingwangdeyoushou_info: '<a style="color: rgba(0,255,255,1)">当你或队友即将进入濒死状态时,防止你和队友扣减体力直到回合开始(1局限1次).</a>',
  mandun: '慢炖',
  mandun_info: '<a style="color: rgba(0,255,255,1)">回合开始时,对所有敌方施加1层烧伤.</a>',
  soulqiji: '奇迹',
  soulqiji_info: '<a style="color: rgba(0,255,255,1)">当你受到有来源的伤害后,你加1点体力上限并回复1点体力(体力上限+3回合冷却).</a>',
  zhipeizhemianju: '支配者面具',
  zhipeizhemianju_info: '<a style="color: rgba(0,255,255,1)">其他角色的手牌对你可见.</a>',
  ganjueburujiequan: '感觉不如界权',
  ganjueburujiequan_info: '<a style="color: rgba(0,255,255,1)">获得【制衡】.</a>',
  chaoyueciyuan: '超越次元',
  chaoyueciyuan_info: '<a style="color: rgba(0,255,255,1)">获得2层灵溢.</a>',
  zhuguanghushou: '珠光护手',
  zhuguanghushou_info: '<a style="color: rgba(0,255,255,1)">你会心伤害提升至200%.获得20%会心几率.</a>',
  yongqi: '勇气',
  yongqi_info: '<a style="color: rgba(0,255,255,1)">当你施加异常状态后,获得1层护盾.</a>',
  weizhideshouduan: '未知的手段',
  weizhideshouduan_info: '<a style="color: rgba(0,255,255,1)">回合开始时移除你当前技能,获得随机2-3个技能作为替代.</a>',
  duankaishengyi: '断铠绳衣',
  duankaishengyi_info: '<a style="color: rgba(0,255,255,1)">出牌阶段,你可以令你本回合使用牌无距离和次数限制且【杀】的伤害值+1(1局限1次).</a>',
  lingyaniansuijike: '灵压碾碎即可',
  lingyaniansuijike_info: '<a style="color: rgba(0,255,255,1)">回合结束时,你摸场上敌方数张牌.</a>',
  quannenglonghun: '全能龙魂',
  quannenglonghun_info: '<a style="color: rgba(0,255,255,1)">获得3个随机龙魂.</a>',
  niqujidianleba: '你去祭典了吧',
  niqujidianleba_info: '<a style="color: rgba(0,255,255,1)">每轮开始时,你失去上次以此法获得的技能并获得队友随机一个技能.</a>',
  huhuanjunzhiming: '呼唤君之名',
  huhuanjunzhiming_info: '<a style="color: rgba(0,255,255,1)">获得【切忆】.</a>',
  jingjisan: '荆棘Ⅲ',
  jingjisan_info: '<a style="color: rgba(0,255,255,1)">当你受到敌方造成的伤害后,对伤害来源造成1点伤害.</a>',
  soulganlu: '甘露',
  soulganlu_info: '<a style="color: rgba(0,255,255,1)">出牌阶段,你可以随机复活一个阵亡队友至3血4牌状态(1局限1次).</a>',
  jisubeizhan: '极速备战',
  jisubeizhan_info: '<a style="color: rgba(0,255,255,1)">每轮都会进行灵魂选取.</a>',
  zhongzhuangshangzhen: '重装上阵',
  zhongzhuangshangzhen_info: '<a style="color: rgba(0,255,255,1)">获得4层护盾.</a>',
  iamtheedge: '我是剑八',
  iamtheedge_info: '<a style="color: rgba(0,255,255,1)">获得2点*攻击*.</a>',
  kuangwang: '狂妄',
  kuangwang_info: '<a style="color: rgba(0,255,255,1)">当你本轮参与击杀后,你摸三张牌.</a>',
  qiezeishoutao: '窃贼手套',
  qiezeishoutao_info: '<a style="color: rgba(0,255,255,1)">对敌方造成伤害后,获得其一张牌.</a>',
  liansuoshandian: '连锁闪电',
  liansuoshandian_info: '<a style="color: rgba(0,255,255,1)">你对敌方造成的伤害后有50%概率对其最近的队友造成1点破防伤害.',
  taowa: '套娃',
  taowa_info: '<a style="color: rgba(0,255,255,1)">获得两次复活次数,但复活后将手牌数摸至2和体力上限调整至2.',
  fengbaokuangyong: '风暴狂涌',
  fengbaokuangyong_info: '<a style="color: rgba(0,255,255,1)">结束阶段,若你本回合至少造成了3点伤害,你对本回合受到过伤害的敌方角色造成1点雷电伤害.',
  yibingshizhe: '疫病使者',
  yibingshizhe_info: '<a style="color: rgba(0,255,255,1)">回合开始时,对距离2以内的敌方角色施加1层5回合的诅咒.<li>诅咒:每回合从敌方诅咒中获得等量诅咒能量.<li>每20层诅咒能量,获得1点额外体力.',
  moriyuyanzhe: '末日预言者',
  moriyuyanzhe_info: '<a style="color: rgba(0,255,255,1)">当你对敌方使用技能后,施加1层5回合的诅咒.<li>诅咒:每回合从敌方诅咒中获得等量诅咒能量.<li>每15层诅咒能量,你的非卡牌伤害+1.',
  jianruopanshi: '坚若磐石',
  jianruopanshi_info: '<a style="color: rgba(0,255,255,1)">受到至少2点或触发会心的伤害-1.',
  soulfentian: '焚天',
  soulfentian_info: '<a style="color: rgba(0,255,255,1)">你对敌方造成的第一次伤害必定翻倍并回复1点体力(8回合冷却)',
  linghunjiban: '灵魂羁绊',
  linghunjiban_info: '<a style="color: rgba(0,255,255,1)">当你队友受到至少2点伤害时,你替其承受大于1的伤害(不得大于你的体力值).队友回复体力后,你有75%概率回复1点体力.',
  rongshizhidun: '熔石之盾',
  rongshizhidun_info: '<a style="color: rgba(0,255,255,1)">使你受到伤害时有35%(+5%*装备牌数)概率防止伤害.',
  tiandihuijin: '天地灰尽',
  tiandihuijin_info: '<a style="color: rgba(0,255,255,1)">每回合限一次,你可以将一张牌当火【杀】使用,此牌目标的技能失效至回合结束.',
  beishuiyizhan: '背水一战',
  beishuiyizhan_info: '<a style="color: rgba(0,255,255,1)">当你首次受到致命伤害时,改为回复1点体力并摸两张牌,你每次选魂都会提供2次免费刷新.',
  tianyaruobilin: '天涯若比邻',
  tianyaruobilin_info: '<a style="color: rgba(0,255,255,1)">每名邻家队友提供25%增伤和减伤1点.',
  lianhedikang: '联合抵抗',
  lianhedikang_info: '<a style="color: rgba(0,255,255,1)">为友方提供其(+20%*与其连座友方数)概率的减伤1点.',
  souljuejing: '绝境',
  souljuejing_info: '<a style="color: rgba(0,255,255,1)">进入濒死状态后,将手牌数摸至4.',
  bawangxuejia: '霸王血甲',
  bawangxuejia_info: '<a style="color: rgba(0,255,255,1)">获得1点额外体力.你使用【杀】的伤害+X(X为你已损失体力值的半数取下).',
  fangshouyibo: '放手一搏',
  fangshouyibo_info: '<a style="color: rgba(0,255,255,1)">你有30%概率摸15张牌,70%概率失去全部体力.',
  mowangzhimian: '魔王之冕',
  mowangzhimian_info: '<a style="color: rgba(0,255,255,1)">你配的上吗？<li>随机分配5点数值给首次加伤/首次减伤/额定摸牌/手牌上限/【杀】限制次数.<li>每轮结束时,若你本轮造成的伤害大于每名敌方角色的伤害,则随机一个数值+1,否则随机两次数值-1.',
  longxin: '龙心',
  longxin_info: '<a style="color: rgba(0,255,255,1)">每轮都会获得1个龙魂.若你已经有了每一种龙魂,那么体内就会觉醒一股上古威能...',
  shangzhili: '熵之力',
  shangzhili_info: '<a style="color: rgba(0,255,255,1)">你施加的可叠加异常状态翻倍.获得20%会心几率.',
  feishenghufu: '飞升护符',
  feishenghufu_info: '<a style="color: rgba(0,255,255,1)">出牌阶段,你可以刷新【飞升护符】的属性.你每次这样做,这些属性都会变得更强.每回合两次(在有【尖端发明家】时改为三次)',
  yuehuazhouren: '月华咒刃',
  yuehuazhouren_info: '<a style="color: rgba(0,255,255,1)">当你于回合内使用技能后,重置【杀】的使用次数且本回合下两张【杀】不计入次数限制.',
  canriyuyi: '残日狱衣',
  canriyuyi_info: '<a style="color: rgba(0,255,255,1)">你的烧伤改为抵挡等量伤害.',
  yajiapopo: '雅加婆婆',
  yajiapopo_info: '<a style="color: rgba(255,128,104,1)">‘Guns.Lots of guns.’</a>',
  jiuchuwodesuoai: '救出我的所爱',
  jiuchuwodesuoai_info: '<a style="color: rgba(255,128,104,1)">‘你想要飞翔吗’</a>',
  wanjiebufu: '万劫不复',
  wanjiebufu_info: '<a style="color: rgba(255,128,104,1)"><于我而言,一切都在那天坠入了深渊.></a>',
  zhaohuilingxianwang: '昭惠灵显王',
  zhaohuilingxianwang_info: '<a style="color: rgba(255,128,104,1)">仪容清俊貌堂堂,两耳垂肩目有光.<br>头戴三山飞凤帽,身穿一领淡鹅黄.<br>缕金靴衬盘龙袜,玉带团花八宝妆.<br>腰挎弹弓新月样,手执三尖两刃枪.</a>'
};
export default translates;