game.buffPack = {
    buff_txhj_aozhan: {
        name: '鏖战',
        info: '对局结束时,你的体力和体力上限不回复',
        rank: 2,
        value: 999,
        store: false,
        skills: ['buff_txhj_yanhuo'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yanhuo: {
        name: '焱火',
        info: '你造成的火焰伤害+1',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_yanhuo'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jinglei: {
        name: '惊雷',
        info: '你造成的雷电伤害+1',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_jinglei'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xihuo: {
        name: '熄火',
        info: '你受到的火焰伤害-1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_xihuo'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_dinglei: {
        name: '定雷',
        info: '你受到的雷电伤害-1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_dinglei'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wuzhongshengsha: {
        name: '无中生杀',
        info: '准备阶段,你从牌堆或弃牌堆中获得一张[杀]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_wuzhongshengsha'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wuzhongshengshan: {
        name: '无中生闪',
        info: '结束阶段,你从牌堆或弃牌堆中获得一张[闪]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_wuzhongshengshan'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_fengyushengcai: {
        name: '丰裕生财',
        info: '每轮开始时,若你未受伤,你摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_fengyushengcai'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jipodizhen: {
        name: '击破敌阵',
        info: '你造成伤害后,随机弃置受伤角色区域内的一张牌',
        rank: 3,
        value: 400,
        store: true,
        skills: ['buff_txhj_jipodizhen'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wenhezhenlue: {
        name: '文和缜略',
        info: '你是用的锦囊牌不能被[无懈可击]响应',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_wenhezhenlue'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wenhejibei: {
        name: '文和计备',
        info: '你不能成为延时锦囊牌的目标',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_wenhejibei'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yueyingdezhihui: {
        name: '月英的智慧',
        info: '你使用锦囊牌无距离限制',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_yueyingdezhihui'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_changbingguangren: {
        name: '长兵广刃',
        info: '你的攻击范围+3',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_changbingguangren'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_fuzu: {
        name: '富足',
        info: '游戏开始时,你的初始手牌数等于你的体力上限(至多30)',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_fuzu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xiaojideyongwu: {
        name: '枭姬的勇武',
        info: '当你失去装备区内的牌时,摸两张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_xiaojideyongwu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xiongziyingfa: {
        name: '雄姿英发',
        info: '摸牌阶段,你多摸一张牌.',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_xiongziyingfa'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wuxiangdexinxue: {
        name: '吴相的心血',
        info: '你的手牌上限+3',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_wuxiangdexinxue'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_juguzhidao: {
        name: '巨贾之道',
        info: '商店刷新费用减半',
        rank: 1,
        value: 1500,
        store: true,
        skills: ['buff_txhj_juguzhidao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_pozhenzhifeng: {
        name: '破阵之锋',
        info: '出牌阶段,若你的装备区内有武器牌,敌方角色的防具失效',
        rank: 2,
        value: 200,
        store: true,
        skills: ['buff_txhj_pozhenzhifeng'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yanrenzhinu: {
        name: '燕人之怒',
        info: '若你的装备区内有武器牌,你每阶段使用的第二张[杀]不能被响应',
        rank: 2,
        value: 200,
        store: true,
        skills: ['buff_txhj_yanrenzhinu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_dunjiazhoufa: {
        name: '遁甲咒法',
        info: '若你的装备区内有武器牌,你的属性[杀]不能被响应',
        rank: 1,
        value: 400,
        store: true,
        skills: ['buff_txhj_dunjiazhoufa'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_ziyideyongzhan: {
        name: '子义的勇战',
        info: '若你的装备区内有武器牌,你每阶段第二张[杀]造成的伤害+1',
        rank: 2,
        value: 200,
        store: true,
        skills: ['buff_txhj_ziyideyongzhan'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yanhuozhiren: {
        name: '焱火之刃',
        info: '若你的装备区内有武器牌,你造成的火焰伤害+1',
        rank: 2,
        value: 200,
        store: true,
        skills: ['buff_txhj_yanhuozhiren'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jingleizhiren: {
        name: '惊雷之刃',
        info: '若你的装备区内有武器牌,你造成的雷电伤害+1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_jingleizhiren'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yingjicuoshijia: {
        name: '应急措施甲',
        info: '当你失去防具时,回复1点体力',
        rank: 1,
        value: 400,
        store: true,
        skills: ['buff_txhj_yingjicuoshijia'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yingjicuoshiyi: {
        name: '应急措施乙',
        info: '当你失去防具时,摸两张牌',
        rank: 1,
        value: 400,
        store: true,
        skills: ['buff_txhj_yingjicuoshiyi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xihuozhikai: {
        name: '熄火之铠',
        info: '若你的装备区内有防具牌,你受到的火焰伤害-1',
        rank: 1,
        value: 600,
        store: true,
        skills: ['buff_txhj_xihuozhikai'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_dingleizhikai: {
        name: '定雷之铠',
        info: '若你的装备区内有防具牌,你受到的雷电伤害-1',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_dingleizhikai'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yueyingdejiqiao: {
        name: '月英的机巧',
        info: '你的判定牌生效后,若你装备区内有牌,你摸一张牌',
        rank: 3,
        value: 200,
        store: true,
        skills: ['buff_txhj_yueyingdejiqiao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_taipingzhoufa: {
        name: '太平咒法',
        info: '你使用属性[杀]造成的伤害+1',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_taipingzhoufa'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_baijujianchu: {
        name: '白驹鞬出',
        info: '当你使用普通[杀]造成伤害后,随机弃置目标角色的一张牌',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_baijujianchu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_juejingzhice: {
        name: '绝境之策',
        info: '当你使用[闪]后,若你没有手牌,你摸两张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_juejingzhice'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xumingshenyao: {
        name: '续命神药',
        info: '你的[桃]濒死回复量+1',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_xumingshenyao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wuweizhile: {
        name: '无为之乐',
        info: '场上其他角色的[乐不思蜀]生效后,其本局手牌上限-1',
        rank: 1,
        value: 400,
        store: true,
        skills: ['buff_txhj_wuweizhile'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yuanduandilue: {
        name: '远断敌略',
        info: '你使用[兵粮寸断]无距离限制',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_yuanduandilue'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jiezizhidao: {
        name: '截辎之道',
        info: '场上的[兵粮寸断]生效后,你摸一张牌',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_jiezizhidao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_huangtiannizhuan: {
        name: '黄天逆转',
        info: '敌方角色的[闪电]判定效果反转',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_huangtiannizhuan'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_dongchazhiyan: {
        name: '洞察之眼',
        info: '你使用[顺手牵羊]时,目标角色的手牌对你可见',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_dongchazhiyan'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_mingjingzhiyan: {
        name: '明镜之眼',
        info: '你使用[过河拆桥]时,目标角色的手牌对你可见',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_mingjingzhiyan'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_juxiangzhifeng: {
        name: '巨象之锋',
        info: '你使用的[南蛮入侵]需额外弃置一张牌才能响应',
        rank: 1,
        value: 400,
        store: true,
        skills: ['buff_txhj_juxiangzhifeng'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_luanjifengshi: {
        name: '乱击锋矢',
        info: '你使用的[万箭齐发]需额外弃置一张牌才能响应',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_luanjifengshi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_taoyuanyishi: {
        name: '桃园义誓',
        info: '你使用的[桃园结义]对己方角色的回复量+1',
        rank: 2,
        value: 200,
        store: true,
        skills: ['buff_txhj_taoyuanyishi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_haoshidebaochao: {
        name: '好施的报偿',
        info: '你使用[五谷丰登]后摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_haoshidebaochang'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_duocejiyong: {
        name: '夺策己用',
        info: '你使用[无懈可击]生效时,你获得被抵消的牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_duocejiyong'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wolongmice: {
        name: '卧龙秘策',
        info: '你使用[火攻]可以弃置同颜色的牌',
        rank: 1,
        value: 400,
        store: true,
        skills: ['buff_txhj_wolongmice'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_fenchengluetu: {
        name: '焚城掠土',
        info: '你使用[火攻]造成伤害时,获得目标角色展示的牌',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_fenchengluetu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_bowenqiangzhi: {
        name: '博闻强识',
        info: '答题事件自动为你排除所有错误答案',
        rank: 3,
        value: 200,
        store: true,
        skills: ['buff_txhj_bowenqiangzhi'],
        sort: 'ChongYingChuLin',
    },
    /* buff_txhj_jufuxionghao: {
           name: '巨富雄豪',
           info: '装备宝物时,你使用与宝物花色相同的牌时摸一张牌(每回合每种花色限一次)',
           rank: 3,
           value: 600,
           store: true,
           skills: [
               'buff_txhj_jufuxionghao'
           ],
           sort: 'ChongYingChuLin'
       },*/
    buff_txhj_majundegaizao: {
        name: '马钧的改造',
        info: '当你获得装备牌后,若此牌可以进化为精械,进化之',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_majundegaizao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xianhujiqu: {
        name: '仙葫汲取',
        info: '战斗胜利后,若你的体力上限大于战斗前的体力上限,继承结束后的体力上限',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_xianhujiqu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_fuchendangmo: {
        name: '拂尘荡魔',
        info: '当你因武器效果令其他角色弃牌时,弃牌数+1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_fuchendangmo'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shenfuhuaxie: {
        name: '神符化邪',
        info: '当你受到伤害后,你获得造成伤害的牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_shenfuhuaxie'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_gongzhibaowu: {
        name: '攻之宝物',
        info: '当你的装备区内有宝物牌,准备阶段,你从牌堆或弃牌堆中获得一张[杀]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_gongzhibaowu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_fangzhibaowu: {
        name: '防之宝物',
        info: '若你的装备区内有宝物牌,结束阶段,你从牌堆或弃牌堆中获得一张[闪]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_fangzhibaowu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_suikuiliejia: {
        name: '碎盔裂甲',
        info: '若你的装备区内有武器牌,你使用[杀]造成伤害后,你弃置目标角色的防具牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_suikuiliejia'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yiguzuoqi: {
        name: '一鼓作气',
        info: '若你的装备区内有武器牌,你每阶段使用第二张[杀]时,你摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_yiguzuoqi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shangjiangdelvli: {
        name: '上将的膂力',
        info: '若你的装备区有武器牌,若你发动武器效果需要弃置牌,弃牌数-1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_shangjiangdelvli'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shenhanxueyin: {
        name: '深寒雪饮',
        info: '若你的装备区内有武器牌,若你发动武器效果弃置了其他角色牌,改为获得之',
        rank: 2,
        store: true,
        value: 400,
        skills: ['buff_txhj_shenhanxueyin'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xiuluodebeimin: {
        name: '修罗的悲悯',
        info: '若你装备区内有武器牌,你令一名角色回复体力后,你摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_xiuluodebeimin'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_cebeibuyu: {
        name: '策备不虞',
        info: '若你的装备区内有防具牌,你受到的锦囊伤害-1',
        rank: 2,
        store: true,
        value: 400,
        skills: ['buff_txhj_cebeibuyu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_gongtaizhizhi: {
        name: '公台之智',
        info: '若你的装备区内有防具牌,且你每轮未受到伤害,你摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_gongtaizhizhi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_tianxiawushuang: {
        name: '天下无双',
        info: '你的普通[杀]造成的伤害+1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_tianxiawushaung'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jijianchangge: {
        name: '击剑长歌',
        info: '当你于回合外使用或打出一张[杀]后,你摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_jijianchangge'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_huangtianzhinu: {
        name: '黄天之怒',
        info: '当你造成属性伤害后,随机弃置目标角色的一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_huangtianzhinu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_luoshenjuezhang: {
        name: '洛神绝章',
        info: '每轮限一次,你使用[闪]后摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_luoshenjuezhang'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shenyizhidao: {
        name: '神医之道',
        info: '你的[桃]正常回复量+1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_shenyizhidao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_mowangdejianiang: {
        name: '魔王的佳酿',
        info: '你的[酒]增加伤害效果持续至回合结束',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_mowangdejianiang'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_hannu: {
        name: '酣怒',
        info: '当你使用[酒]后,你获得牌堆中的一张[杀]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_hannu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_gusoejueyan: {
        name: '国色绝艳',
        info: '场上的[乐不思蜀]生效后,你摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_guosejueyan'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_mingyundezhiyi: {
        name: '命运的旨意',
        info: '当你使用[闪电]后,横置场上所有敌方角色',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_mingyundezhiyi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_ximengzhili: {
        name: '系盟之利',
        info: '你使用[远交近攻]多摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_ximengzhili'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_hengxingwuji: {
        name: '横行无忌',
        info: '你使用[过河拆桥]后摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_hengxingwuji'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shierqicejin: {
        name: '十二奇策进',
        info: '你使用的[南蛮入侵]和[万箭齐发]对己方角色无效(仍成为目标)',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_shierqicejin'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shierqicetui: {
        name: '十二奇策退',
        info: '你使用的[桃园结义]和[五谷丰登]对敌方角色无效(仍成为目标)',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_shierqicetui'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_pofuchenzhou: {
        name: '破釜沉舟',
        info: '你的初始手牌数为1,准备阶段和结束阶段,你摸一张牌,优先级高于(富足)',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_pofuchenzhou'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_huangtianyili: {
        name: '黄天已立',
        info: '你的判定结果花色视为♠️️.',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_huangtianyili'],
        sort: 'HuanTianZhiNu',
    },
    buff_txhj_huangtianzhizu: {
        name: '黄天之诅',
        info: '你的判定结果视为♠️️ 5 .',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_huangtianzhizu'],
        sort: 'HuanTianZhiNu',
    },
    buff_txhj_huangtianzhimin: {
        name: '黄天之悯',
        info: '你的判定牌生效后,你可以摸一张牌.',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_huangtianzhimin'],
        sort: 'HuanTianZhiNu',
    },
    buff_txhj_tiangongdeyouhu: {
        name: '天公的佑护',
        info: '若你在施法技能选择的 X 大于 1 ,你在(X-1)的结束阶段即可触发效果.',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_tiangongdeyouhu'],
        sort: 'HuanTianZhiNu',
    },
    buff_txhj_digongdeyouhu: {
        name: '地公的佑护',
        info: '你的施法技能 X 上限+1.',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_digongdeyouhu'],
        sort: 'HuanTianZhiNu',
    },
    buff_txhj_renigongdeyouhu: {
        name: '人公的佑护',
        info: '你使用施法技能后,可以摸一张牌.',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_rengongdeyouhu'],
        sort: 'HuanTianZhiNu',
    },
    //魔改buff
    buff_txhj_yanlihongyan: {
        name: '艳丽红颜',
        info: '你的判定结果花色视为♥️️.',
        rank: 2,
        value: 370,
        store: true,
        skills: ['buff_txhj_yanlihongyan'],
        sort: 'MGBaWangZhengCheng',
    },
    buff_txhj_moqiyangwei: {
        name: '魔骑的扬威',
        info: '当你使用普通[杀]造成伤害后,你立即摸两张牌',
        rank: 3,
        value: 720,
        store: true,
        skills: ['buff_txhj_moqiyangwei'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_kuanglangzhishi: {
        name: '狂狼之噬',
        info: '你造成伤害后,你回复1点体力值',
        rank: 3,
        value: 550,
        store: true,
        skills: ['buff_txhj_kuanglangzhishi'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_liangyongzhixiao: {
        name: '凉勇之骁',
        info: '你使用的黑色【杀】不可被响应',
        rank: 3,
        value: 720,
        store: true,
        skills: ['buff_txhj_liangyongzhixiao'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_hanshishuaiwei: {
        name: '汉室衰微',
        info: '其他角色的结束阶段开始时,若其体力值为全场最小,则其失去1点体力',
        rank: 2,
        value: 380,
        store: true,
        skills: ['buff_txhj_hanshishuaiwei'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_fanjianzhiji: {
        name: '反间之计',
        info: '其他角色获得你的牌时,你对其造成1点伤害',
        rank: 3,
        value: 660,
        store: true,
        skills: ['buff_txhj_fanjianzhiji'],
        sort: 'MGBaWangZhengCheng',
    },
    /*  buff_txhj_bushizhigong: {
            name: '不世之功',
            info: '你拼点的红色牌点数视为K',
            rank: 2,
            value: 360,
            store: true,
            skills: [
                'buff_txhj_bushizhigong'
            ],
            sort: 'MGBaWangZhengCheng'
        },*/
    buff_txhj_baibuchuanyang: {
        name: '百步穿杨',
        info: '你对攻击范围内没有你的角色造成的伤害+1',
        rank: 3,
        value: 800,
        store: true,
        skills: ['buff_txhj_baibuchuanyang'],
        sort: 'MGBaWangZhengCheng',
    },
    buff_txhj_guosetianxiang: {
        name: '国色天香',
        info: '每回合限一次,当你于回合外失去牌时,你摸两张牌',
        rank: 2,
        value: 620,
        store: true,
        skills: ['buff_txhj_guosetianxiang'],
        sort: 'MGBaWangZhengCheng',
    },
    buff_txhj_yongguansanjun: {
        name: '勇冠三军',
        info: '每当你使用基本牌后,从牌堆中随机获得一张锦囊牌',
        rank: 3,
        value: 900,
        store: true,
        skills: ['buff_txhj_yongguansanjun'],
        sort: 'MGBaWangZhengCheng',
    },
    buff_txhj_huangtianyisi: {
        name: '黄天也死了',
        info: '你的判定牌生效后,你流失1点体力',
        rank: 1,
        value: 140,
        store: true,
        skills: ['buff_txhj_huangtianyisi'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_weifengcainiang: {
        name: '尾蜂的采酿',
        info: '当你使用[桃]后,你获得牌堆中的一张[闪]',
        rank: 2,
        value: 390,
        store: true,
        skills: ['buff_txhj_weifengcainiang'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_laozhedezhutuo: {
        name: '老者的嘱托',
        info: '当你于回合外使用或打出一张[闪]后,你摸一张牌',
        rank: 2,
        value: 360,
        store: true,
        skills: ['buff_txhj_laozhedezhutuo'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_yinghuoshouxin: {
        name: '荧惑兽心',
        info: '若你的装备区内有防具牌,且你每轮未受到伤害,你增加1点体力上限',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_yinghuoshouxin'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_zhedaoduanqi: {
        name: '折刀断器',
        info: '若你的装备区内有武器牌,你使用[杀]造成伤害后,你弃置目标角色的武器牌',
        rank: 2,
        value: 380,
        store: true,
        skills: ['buff_txhj_zhedaoduanqi'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_huoshinifeng: {
        name: '火势逆风',
        info: '敌方角色的[火山]判定效果反转',
        rank: 2,
        value: 470,
        store: true,
        skills: ['buff_txhj_huoshinifeng'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_bingfeng: {
        name: '冰封',
        info: '你造成的寒冰伤害+1',
        rank: 2,
        value: 420,
        store: true,
        skills: ['buff_txhj_bingfeng'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_shanluwushe: {
        name: '杀戮无赦',
        info: '你使用[杀]结算后摸一张牌',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_shanluwushe'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_dushidemiyan: {
        name: '毒仕的迷烟',
        info: '你的判定结果视为♣️️4 .',
        rank: 1,
        value: 200,
        store: true,
        skills: ['buff_txhj_dushidemiyan'],
        sort: 'LiGuoZhiLuan',
    },
    buff_txhj_chenxverru: {
        name: '趁虚而入',
        info: '当你的装备区内有宝物牌,准备阶段,你从牌堆或弃牌堆中获得一张[逐近弃远]',
        rank: 1,
        value: 250,
        store: true,
        skills: ['buff_txhj_chenxverru'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_taozeifengshi: {
        name: '讨贼锋矢',
        info: '你使用的[杀]需额外弃置一张牌才能闪避',
        rank: 2,
        value: 450,
        store: true,
        skills: ['buff_txhj_taozeifengshi'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_bailitoujie: {
        name: '百里偷劫',
        info: '你使用[顺手牵羊]无距离限制',
        rank: 2,
        value: 380,
        store: true,
        skills: ['buff_txhj_bailitoujie'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_hubaochongsha: {
        name: '虎豹冲杀',
        info: '你使用基本牌无距离限制',
        rank: 1,
        value: 250,
        store: true,
        skills: ['buff_txhj_hubaochongsha'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_huangjinfushen: {
        name: '黄巾符身',
        info: '你不能成为普通锦囊牌的目标',
        rank: 3,
        value: 700,
        store: true,
        skills: ['buff_txhj_huangjinfushen'],
        sort: 'GFHuangJinZhiLuan',
    },
    buff_txhj_anjianzhicui: {
        name: '暗箭之摧',
        info: '你使用的基本牌不能被[闪]响应',
        rank: 3,
        value: 650,
        store: true,
        skills: ['buff_txhj_anjianzhicui'],
        sort: 'MGBaWangZhengCheng',
    },
    buff_txhj_manzuzaoluan: {
        name: '蛮族造乱',
        info: '准备阶段,你从牌堆或弃牌堆中获得一张[南蛮入侵]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_manzuzaoluan'],
        sort: 'GFQiQinMengHuo',
    },
    buff_txhj_zhengjunjingwu: {
        name: '整军经武',
        info: '你造成的伤害+x(x为目标角色满足以下条件的项数:1:手牌数为0;2:装备区的牌数为0;3:未受伤)',
        rank: 4,
        value: 1000,
        store: true,
        skills: ['buff_txhj_zhengjunjingwu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jueyijinguo: {
        name: '决意巾帼',
        info: '当你失去体力后,你加一点体力上限',
        rank: 3,
        value: 800,
        store: true,
        skills: ['buff_txhj_jueyijinguo'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_luanshiyingjie: {
        name: '乱世英杰',
        info: '当你的手牌数小于x时,你将手牌补至x(x为4-你装备区的牌数)',
        rank: 4,
        value: 1000,
        store: true,
        skills: ['buff_txhj_luanshiyingjie'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yanranyixiao: {
        name: '嫣然一笑',
        info: '每轮限一次,当你进入濒死状态时,若当前回合角色已受伤,你与其共同回满体力值.',
        rank: 3,
        value: 1800,
        store: true,
        skills: ['buff_txhj_yanranyixiao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_tianmingmichang: {
        name: '天命靡常',
        info: '当你的体力上限增加后,你回复等量体力;当你的体力上限减少前,你受到等量伤害.',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_tianmingmichang'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_mingliangqiangu: {
        name: '明良千古',
        info: '当你使用[杀]指定目标后,你令其锁定技失效且此[杀]伤害+1',
        rank: 4,
        value: 2000,
        store: true,
        skills: ['buff_txhj_mingliangqiangu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jieqiaoxianden: {
        name: '界桥先登',
        info: '出牌阶段开始时,你视为对所有敌方角色依次使用一张[决斗]',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_jieqiaoxianden'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_linjunduizhen: {
        name: '临军对阵',
        info: '若你本回合使用过[杀],你的[杀]均视为k点,你的k点[杀]伤害+1',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_linjunduizhen'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shiguanjianshi: {
        name: '矢贯坚石',
        info: '你造成的伤害+x(x为目标角色手牌中[闪]的数量)',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_shiguanjianshi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xiongjuyizhou: {
        name: '雄踞益州',
        info: '若你未受伤,你的[闪]均视为[万箭齐发]',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_xiongjuyizhou'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_bianruxuanhe: {
        name: '辨如悬河',
        info: '你使用[酒]无次数限制,若你处于[酒]状态,你使用[杀]无次数限制',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_bianruxuanhe'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_ziwuqimou: {
        name: '子午奇谋',
        info: '若你不处于濒死状态,你回复体力的效果改为获得等量护甲并摸两倍数量的牌',
        rank: 3,
        value: 800,
        store: true,
        skills: ['buff_txhj_ziwuqimou'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_weizhenhuaxia: {
        name: '威震华夏',
        info: '当你使用有花色的[杀]指定目标后,你令其弃置所有该花色的牌,若其依此法弃置了牌,此[杀]不计入次数.',
        rank: 4,
        value: 1000,
        store: true,
        skills: ['buff_txhj_weizhenhuaxia'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_xunyuliangjie: {
        name: '巡域两界',
        info: '出牌阶段开始时,你视为使用一张[酒],你对处于[酒]状态的角色造成的伤害+1',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_xunyuliangjie'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_ligunligunli: {
        name: '利滚利滚利',
        info: '战斗结束时,你每有10金币,便获得1金币',
        rank: 4,
        value: 400,
        store: true,
        skills: ['buff_txhj_ligunligunli'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_mizhixianren: {
        name: '迷之仙人',
        info: '每场战斗结束时,你获得一个随机技能',
        rank: 4,
        value: 400,
        store: true,
        skills: ['buff_txhj_mizhixianren'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wumouyizongheng: {
        name: '无谋亦纵横',
        info: '你的回合内,其他角色的手牌均视为[无懈可击]',
        rank: 4,
        value: 1000,
        store: true,
        skills: ['buff_txhj_wumouyizongheng'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_zhougongtupu: {
        name: '周公吐哺',
        info: '当你使用[五谷丰登]结算后,你受到一点伤害并摸x张牌(x为4+攻击范围内没有你的角色数)',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_zhougongtupu'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jigumacao: {
        name: '击鼓骂曹',
        info: '当你连续对一名其他角色使用牌时,你令其失去一点体力',
        rank: 2,
        value: 800,
        store: true,
        skills: ['buff_txhj_jigumacao'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_dushangweilou: {
        name: '独上危楼',
        info: '一名其他角色的武将牌翻至背面时,若此时为其的出牌阶段,立即结束之',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_dushangweilou'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jingfengpiaobairi: {
        name: '惊风飘白日',
        info: '当你的武将牌翻至正面时,你插入一个额外回合',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_jingfengpiaobairi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_biyuexiuhua: {
        name: '闭月羞花',
        info: '若你的武将牌背面朝上,你造成的伤害+1',
        rank: 2,
        value: 600,
        store: true,
        skills: ['buff_txhj_biyuexiuhua'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_hunyoujiangtong: {
        name: '魂佑江东',
        info: '一名角色的准备阶段内,其体力值暂时为1',
        rank: 2,
        value: 1000,
        store: true,
        skills: ['buff_txhj_hunyoujiangtong'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_wotazhice: {
        name: '卧榻之侧',
        info: '敌方角色的准备阶段,若其体力值不小于你,你对其使用一张[决斗]',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_wotazhice'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yizhenqingmeng: {
        name: '一枕清梦',
        info: '若你没有手牌,你受到非[决斗]的伤害-1',
        rank: 3,
        value: 800,
        store: true,
        skills: ['buff_txhj_yizhenqingmeng'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jiejiashichou: {
        name: '解甲事仇',
        info: '弃牌阶段,你弃置所有手牌并获得等量护甲(至多5点)',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_jiejiashichou'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_zuoshanguanhudou: {
        name: '坐山观虎斗',
        info: '其他角色的回合开始时,若你未记录该角色,你暂时移出游戏;否则删除该记录',
        rank: 4,
        value: 2500,
        store: true,
        skills: ['buff_txhj_zuoshanguanhudou'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_yunchouweiwo: {
        name: '运筹帷幄',
        info: '你的手牌数始终为0,你可以将牌堆顶x张牌如手牌般使用或打出(x为牌堆剩余牌数的1/7)',
        rank: 4,
        value: 2500,
        store: true,
        skills: ['buff_txhj_yunchouweiwo'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_qiqiaolinglong: {
        name: '七窍玲珑',
        info: '扩充牌堆中的锦囊牌',
        rank: 2,
        value: 200,
        store: true,
        skills: ['buff_txhj_qiqiaolinglong'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_shengmingbaoshi: {
        name: '生命宝石',
        info: '每有一颗该宝石,体力上限+1',
        rank: 5,
        value: 77,
        store: false,
        restore: true,
        health: 1,
        skills: ['buff_txhj_shengmingbaoshi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jianyanbaoshi: {
        name: '坚岩宝石',
        info: '每有一颗该宝石,受到的伤害-1',
        rank: 5,
        value: 7777,
        store: false,
        restore: true,
        skills: ['buff_txhj_jianyanbaoshi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_qingquanbaoshi: {
        name: '清泉宝石',
        info: '每有一颗该宝石,摸牌阶段摸牌数+1',
        rank: 5,
        value: 777,
        store: false,
        restore: true,
        skills: ['buff_txhj_qingquanbaoshi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_huimiebaoshi: {
        name: '毁灭宝石',
        info: '每有一颗该宝石,造成的伤害+1',
        rank: 5,
        value: 7777,
        store: false,
        restore: true,
        skills: ['buff_txhj_huimiebaoshi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_cijidaifa: {
        name: '伺机待发',
        info: '你于一回合内使用的前x张[杀]伤害+1(x为游戏轮数)',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_cijidaifa'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_tongqiangtiebi: {
        name: '铜墙铁壁',
        info: '你受到基本牌的伤害-1,但受到锦囊牌的伤害+1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_tongqiangtiebi'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_guzhielai: {
        name: '古之恶来',
        info: '当你造成伤害时,你失去一点体力令此伤害+1',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_guzhielai'],
        sort: 'ChongYingChuLin',
    },
    buff_txhj_jigongsuzhan: {
        name: '急攻速战',
        info: '准备阶段,你从牌堆或弃牌堆中获得一张伤害类锦囊牌',
        rank: 3,
        value: 600,
        store: true,
        skills: ['buff_txhj_jigongsuzhan'],
        sort: 'MGGuanDuZhiZhan',
    },
    buff_txhj_qiaojieyongmeng: {
        name: '趫捷勇猛',
        info: '结束阶段,你摸X张牌(X为你装备区的牌数+1)',
        rank: 2,
        value: 400,
        store: true,
        skills: ['buff_txhj_qiaojieyongmeng'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_yishaoshengduo: {
        name: '以少胜多',
        info: '你使用[杀]造成伤害后,若指定目标的手牌数大于你,该伤害+2',
        rank: 3,
        value: 450,
        store: true,
        skills: ['buff_txhj_yishaoshengduo'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_cuifengwuxie: {
        name: '摧封无懈',
        info: '结束阶段,你从牌堆或弃牌堆中获得一张[无懈可击]',
        rank: 2,
        value: 300,
        store: true,
        skills: ['buff_txhj_cuifengwuxie'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_jianzhichongzu: {
        name: '箭支充足',
        info: '你使用[万箭齐发]后摸一张牌',
        rank: 2,
        value: 300,
        store: true,
        skills: ['buff_txhj_jianzhichongzu'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_choudaosidong: {
        name: '抽刀伺动',
        info: '你的回合外,你使用[闪]生效时,你获得被抵消的[杀]',
        rank: 2,
        value: 300,
        store: true,
        skills: ['buff_txhj_choudaosidong'],
        sort: 'HaiWaiFengHe',
    },
    buff_txhj_xuweidezunwei: {
        name: '虚伪的尊威',
        info: '你使用[无中生有]多摸一张牌',
        rank: 3,
        value: 500,
        store: true,
        skills: ['buff_txhj_xuweidezunwei'],
        sort: 'HaiWaiFengHe',
    },
    /*分界线——*/
    txhj_dundunSkill1: {
        name: '勇往直前',
        info: '当你使用【杀】指定目标后,你有10/20/40/60/80/100%的概率摸一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_dundunSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_dundunSkill2: {
        name: '忠誌',
        info: '当你受到伤害时,若此伤害值大于1,令该伤害-1.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_dundunSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_jiuweiSkill1: {
        name: '狐火灵气',
        info: '其他角色回合开始时,你有10/20/40/60/80/100%的概率使其本回合以你为唯一目标的所有锦囊牌失效.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_jiuweiSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_jiuweiSkill2: {
        name: '秘思',
        info: '你的回合内,其他角色使用或打出的第一张非锦囊牌失效.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_jiuweiSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_jiuweiSkill3: {
        name: '九尾之命',
        info: '当你受到1点伤害后,你摸x张牌(x为9-此技能发动次数,当x为0时,此技能失效).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_jiuweiSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_tengsheSkill1: {
        name: '雷奔云谲',
        info: '每回合限一次,当你在回合外受到非属性伤害时20/30/40/60/80/100%对伤害来源使用一张雷属性的杀.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_tengsheSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_tengsheSkill2: {
        name: '紫电',
        info: '你的回合结束时对所有已受伤的敌方角色造成1点雷电伤害,如果仅有1名满足条件的敌方角色,则改为造成2点雷电伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_tengsheSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_tengsheSkill3: {
        name: '迅雷风烈',
        info: '每回合限一次,当其他角色受到雷属性伤害时,你回复1点体力并摸两张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_tengsheSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_ditingSkill1: {
        name: '披坚执锐',
        info: '当你造成伤害后,你有10/20/40/60/80/100%的概率回复1点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_ditingSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_ditingSkill2: {
        name: '轻健',
        info: '当你受到伤害后,增加一点体力上限.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_ditingSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_ditingSkill3: {
        name: '巧捷万端',
        info: '回合结束时,你摸x张牌,并对x名敌方角色造成1点伤害(x为本回合使用不同点数的牌的数量).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_ditingSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_qilinSkill1: {
        name: '麒麟之姿',
        info: '摸牌阶段结束时,你有20/30/40/60/80/100%的概率摸x张牌(x为你摸牌阶段的摸牌数)',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_qilinSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_qilinSkill2: {
        name: '掌火',
        info: '每回合限两次,你造成火焰伤害后,你回复1点体力并获得该受伤角色的1张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_qilinSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_qilinSkill3: {
        name: '腾焰飞芒',
        info: '出牌阶段开始时和结束时,你视为对一名随机敌方角色使用一张【火攻】.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_qilinSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_youyouSkill1: {
        name: '承天之佑',
        info: '每回合限一次,当你于回合外受到伤害后,你有20/30/40/60/80/100%的概率摸两张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_youyouSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_youyouSkill2: {
        name: '守护',
        info: '每回合限一次,当你在摸牌阶段外一次性获得大于一张牌后,你随机令一名已受伤的友方角色回复1点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_youyouSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_minminSkill1: {
        name: '娉婷万種',
        info: '每回合限一次,当你受到伤害后,你有10/20/40/60/80/100%的概率摸x张牌(x为本次伤害值).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_minminSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_minminSkill2: {
        name: '依人',
        info: '每回合限两次,当你一次性摸不小于2张牌后,你令一名随机友方已受伤角色回复一点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_minminSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_qiaoqiaoSkill1: {
        name: '慧心巧思',
        info: '每当延时类锦囊牌进入其他角色判定区时,你有20/30/40/60/80/100%的概率随机令一名敌方角色失去一点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_qiaoqiaoSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_qiaoqiaoSkill2: {
        name: '清婉',
        info: '回合结束时,你将手牌数摸至体力值.(至多为5)',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_qiaoqiaoSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_yayaSkill1: {
        name: '慷慨鸭昂',
        info: '每回合限四次,当你使用红色牌或被其他角色的红色牌指定为目标时,你有20/30/40/60/80/100%的概率摸一张牌;你每通过此技能获得4张牌,你对一名随机敌方角色造成1点伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yayaSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_yayaSkill2: {
        name: '鸭立',
        info: '每局对局限一次,当你进入濒死状态时,你将体力回复至1点,并在你受到伤害、流失体力、回复体力时防止之,直到你的下个回合开始.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yayaSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_datongSkill1: {
        name: '金鸡独立',
        info: '当你进入濒死状态时,你回复体力至1点 (每次对局限至多触发一次).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_datongSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_luluSkill1: {
        name: '如虎添翼',
        info: '出牌阶段开始时,你摸两张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_luluSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_luluSkill2: {
        name: '虎威',
        info: '你于回合内使用第一张[杀]时,若你本回合获得牌数不小于x (x为你的当前体力值),则你此[杀]不可响应且伤害+1.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_luluSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_aleSkill1: {
        name: '乐不可支',
        info: '当你于一个回合第一次成为一张基本牌的目标后,若此牌未对你造成伤害,你摸一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_aleSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_aleSkill2: {
        name: '饞嘴王',
        info: '准备阶段,若你已受伤且体力值不是全场最高,你回复1点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_aleSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_ruiSkill1: {
        name: '祥云瑞气',
        info: '出牌阶段结束时,你对手牌数小于你的敌方角色造成1点火焰伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_ruiSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_ruiSkill2: {
        name: '神妙',
        info: '准备阶段和结束阶段,若你的手牌数为奇数,你令随机一个我方角色摸一张牌;若手牌数为偶数,你令随机一个敌方角色随机弃一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_ruiSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_ruiSkill3: {
        name: '洞若观火',
        info: '当你成为其他角色使用的普通锦囊牌的目标时,你进行判定:若为红色,则此锦囊无效且你获得之.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_ruiSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_yueerSkill1: {
        name: '花容月貌',
        info: '每轮限一次,当男性角色受到伤害后,你回复一点体力并摸一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yueerSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_yueerSkill2: {
        name: '娇面',
        info: '弃牌阶段结束时,你摸两张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yueerSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_yanSkill1: {
        name: '神鬼不测',
        info: '当你成为其他角色使用的普通锦囊的唯一目标时,你进行判定:若为黑色,则改为你对使用者使用该锦囊.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yanSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_yanSkill2: {
        name: '反计',
        info: '每回合限一次,当你受到其他角色的伤害后,你视为对伤害来源使用一张杀,若该杀造成伤害,则你回复1点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yanSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_yanSkill3: {
        name: '天外之火',
        info: '每回合限一次,当你对其他角色造成伤害后,进行一次判定:黑色你获得其一张牌,红色你摸两张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_yanSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_liuliSkill1: {
        name: '墨玉点雪',
        info: '其他角色的回合限一次,当你失去牌时,对当前回合角色造成1点伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_liuliSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_liuliSkill2: {
        name: '伶俐',
        info: '每回合限一次,其他角色在弃牌阶段弃牌后,你从弃牌堆获得一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_liuliSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_manmanSkill1: {
        name: '弄鬼掉猴',
        info: '回合开始时,你视为使用一张【南蛮入侵】;【南蛮入侵】每造成1点伤害你摸1张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_manmanSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_manmanSkill2: {
        name: '捣蛋',
        info: '每回合限一次,当你对其他角色造成伤害后,你随机获得其一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_manmanSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_xiaoxiaoSkill1: {
        name: '矢无虚发',
        info: '每回合限一次,当你成为其他角色使用普通锦囊牌的目标后,若你没有受到伤害,则你回复1点体力(若体力已满则改为摸一张牌).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_xiaoxiaoSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_xiaoxiaoSkill2: {
        name: '弓上弦',
        info: '弃牌阶段结束时,你从每名装备区装备数不大于你的其他角色处随机获得1张手牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_xiaoxiaoSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_xuerenSkill1: {
        name: '轻舞飞扬',
        info: '回合结束时,若你本回合造成过伤害,你摸一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_xuerenSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_xuanwuSkill1: {
        name: '倚天拔地',
        info: '当其他角色回复体力时,你回复1点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_xuanwuSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_xuanwuSkill2: {
        name: '蛇影',
        info: '每回合限一次,当你弃置手牌或手牌被弃置时,你随机对X名敌方角色造成1点伤害并摸X张牌.(X为你本次弃置手牌数除以2向上取整)',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_xuanwuSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_xuanwuSkill3: {
        name: '玄冥真主',
        info: '当其他角色使用锦囊牌指定你为目标时,若该牌点数小于等于你的手牌数,则该锦囊无效.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_xuanwuSkill3'],
        sort: 'ChongYingChuLin',
    },
    diychunxiao: {
        name: '春晓',
        info: '游戏开始时,你摸四张牌并率先行动.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diychunxiao'],
        sort: 'ChongYingChuLin',
    },
    diyzhuiling: {
        name: '追灵',
        info: '你受到<中毒>角色的伤害-1.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diyzhuiling'],
        sort: 'ChongYingChuLin',
    },
    diycuidu: {
        name: '淬毒',
        info: '你对一名其他角色造成伤害后:若其没有<中毒>,你令其获得<中毒>;否则你摸一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diycuidu'],
        sort: 'ChongYingChuLin',
    },
    diyfeihua: {
        name: '飞花',
        info: '当你不因<飞花>使用或打出牌时,若你没有<花>,本回合你记录此牌名的<花>,你可以移去<花>将一张牌当做记录的牌名使用或打出.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diyfeihua'],
        sort: 'ChongYingChuLin',
    },
    //以下侍灵全部搬运自K佬的【EpicFX】扩展,再次感谢K佬的侍灵素材和技能代码提供!
    txhj_jinwuSkill1: {
        name: '永恒烈日',
        info: '当你第一次进入濒死状态时,你有20/30/40/60/80/100%的概率体力回复至体力上限.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_jinwuSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_jinwuSkill2: {
        name: '三足',
        info: '你的手牌上限等于体力上限.每回合每种类型限一次,当你使用牌后,你失去1点体力,摸X张牌.(X为你已损失的体力值且最大为9).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_jinwuSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_jinwuSkill3: {
        name: '赤地千里',
        info: '每个回合结束后,若本回合你在弃牌阶段外弃置的牌数大于体力值,则摸等同于弃置牌数的牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_jinwuSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_canglongSkill1: {
        name: '风云变色',
        info: '其他角色的准备阶段,你有20/30/40/60/80/100%的概率视为对其使用一张无距离限制的【杀】(你可选择是否执行).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_canglongSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_canglongSkill2: {
        name: '鸣嗷',
        info: '每回合你使用的第一张【杀】伤害 +1.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_canglongSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_canglongSkill3: {
        name: '披星戴月',
        info: '你的回合内,当你使用【杀】造成伤害后,你摸X张牌(X为本回合你使用【杀】的次数且上限为5),该效果每回合限触发5次.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_canglongSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_kangkangSkill1: {
        name: '丰收瑞鸣',
        info: '每轮限两次,你造成或受到伤害后有20/30/40/60/80/100%的概率摸1张牌.你每通过<丰收瑞鸣>摸2张牌时,你回复一点体力.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_kangkangSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_kangkangSkill2: {
        name: '安康',
        info: '准备阶段,你摸2张牌,若你未受伤,你弃置你判定区内的所有牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_kangkangSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_niuniuSkill1: {
        name: '巧拙守真',
        info: '每回合限两次,当你于回合外失去牌后,你有20/30/40/60/80/100%的概率随机获得当前回合角色一张牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_niuniuSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_niuniuSkill2: {
        name: '兕袭',
        info: '每回合限一次,当你获得其他角色的牌时进行判定:若为♥️️,你回复一点体力并获得判定牌;不为♥️️,你对其造成1点伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_niuniuSkill2'],
        sort: 'ChongYingChuLin',
    },
    diy_xiongshiSkill1: {
        name: '霸体',
        info: '锁定技,当你受到雷电伤害后,你摸X张牌(X为你的体力上限);当你受到火焰伤害后,你将一张【兵粮寸断】置入伤害来源判定区内并从牌堆中获得一张【杀】.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diy_xiongshiSkill1'],
        sort: 'ChongYingChuLin',
    },
    diy_xiongshiSkill2: {
        name: '兽噬',
        info: '每当你造成一次伤害后,你可以对一名不为此目标的其他角色造成1点伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diy_xiongshiSkill2'],
        sort: 'ChongYingChuLin',
    },
    diy_xiongshiSkill3: {
        name: '狂狮愤戾',
        info: '当你使用牌时,其他角色不能使用或打出牌响应;你使用牌指定唯一目标造成伤害时,若你的手牌数大于其则你从牌堆中随机获得一张基本牌.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['diy_xiongshiSkill3'],
        sort: 'ChongYingChuLin',
    },
    txhj_aHaoSkill1: {
        name: '豪门贵胄',
        info: '每场战斗结束时,你获得一件随机装备.',
        rank: 4,
        value: 400,
        store: true,
        skills: ['txhj_aHaoSkill1'],
        sort: 'ChongYingChuLin',
    },
    txhj_aHaoSkill2: {
        name: '神勇',
        info: '每当你在牌局内失去装备时对所有敌人造成1点伤害.',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_aHaoSkill2'],
        sort: 'ChongYingChuLin',
    },
    txhj_aHaoSkill3: {
        name: '攫戾執猛',
        info: '回合开始时,你摸牌阶段摸牌数、出杀次数、手牌上限+x (x为装备区的装备数).',
        rank: 3,
        value: 999,
        store: false,
        skills: ['txhj_aHaoSkill3'],
        sort: 'ChongYingChuLin',
    },
};
