game.import('character', function (lib, game, ui, get, ai, _status) {
	const scqh = {
		name: 'scqh',
		connect: true,
		characterSort: {
			scqh: {
				scqhBasic: ['scqh_shenchunqianhe', 'scqh_tanyuan'],
				scqhDiy: ['scqhDiy_jiu', 'scqhDiy_jiutiaoaili', 'scqhDiy_jiushizhengjin'],
				scqhKoihime: ['scqhKoihime_weiyan', 'scqhKoihime_zhangzhao', 'scqhKoihime_lusu', 'scqhKoihime_zhangliao', 'scqhKoihime_hejin', 'scqhKoihime_chengong', 'scqhKoihime_luxun', 'scqhKoihime_chengpu', 'scqhKoihime_caochun', 'scqhKoihime_yanyan', 'scqhKoihime_dianwei', 'scqhKoihime_gongsunzan', 'scqhKoihime_liuxie', 'scqhKoihime_zhaozhong', 'scqhKoihime_jiaxu', 'scqhKoihime_huanggai', 'scqhKoihime_huangfusong', 'scqhKoihime_zhangxun', 'scqhKoihime_luzhi', 'scqhKoihime_lejin', 'scqhKoihime_taishici', 'scqhKoihime_lidian', 'scqhKoihime_mizhu', 'scqhKoihime_mifang', 'scqhKoihime_hetaihou', 'scqhKoihime_sunqian', 'scqhKoihime_tianfeng', 'scqhKoihime_chendeng', 'scqhKoihime_xuhuang', 'scqhKoihime_yujin', 'scqhKoihime_chengyu', 'scqhKoihime_machao', 'scqhKoihime_madai', 'scqhKoihime_dongzhuo', 'scqhKoihime_zhouyu', 'scqhKoihime_yuanshu', 'scqhKoihime_zhangjiao', 'scqhKoihime_zhangbao', 'scqhKoihime_zhangliang', 'scqhKoihime_caohong', 'scqhKoihime_xiahouyuan', 'scqhKoihime_xiahoudun', 'scqhKoihime_liuhong', 'scqhKoihime_lvmeng', 'scqhKoihime_menghuo', 'scqhKoihime_xunyu', 'scqhKoihime_guojia', 'scqhKoihime_yuanshao', 'scqhKoihime_caocao', 'scqhKoihime_caoren', 'scqhKoihime_sunquan', 'scqhKoihime_sunshangxiang', 'scqhKoihime_huaxiong', 'scqhKoihime_liubei', 'scqhKoihime_zhaoyun', 'scqhKoihime_zhangfei', 'scqhKoihime_guanyu', 'scqhKoihime_huangzhong', 'scqhKoihime_sunce', 'scqhKoihime_sunjian', 'scqhKoihime_lvbu', 'scqhKoihime_zhoutai', 'scqhKoihime_zhugeliang', 'scqhKoihime_pangtong'],
				scqhPcr: ['scqhPcr_linai', 'scqhPcr_xue', 'scqhPcr_peikelimu', 'scqhPcr_xuefei', 'scqhPcr_aimeisi', 'scqhPcr_zhenna', 'scqhPcr_zhuxi', 'scqhPcr_jita', 'scqhPcr_jitasix', 'scqhPcr_yiliya', 'scqhPcr_yiliya2', 'scqhPcr_qiunai', 'scqhPcr_kelisitina', 'scqhPcr_youjiali', 'scqhPcr_lingnai', 'scqhPcr_chun'],
				scqhMiao: ['scqhMiao_caiwenji', 'scqhMiao_zhangchunhua', 'scqhMiao_zhangxingcai', 'scqhMiao_diaochan', 'scqhMiao_wangyi', 'scqhMiao_zhenji', 'scqhMiao_zhurong', 'scqhMiao_huangyueying'],
				scqhLOL: ['scqhLOL_kaiyin', 'scqhLOL_kaiyinred', 'scqhLOL_kaiyinblack', 'scqhLOL_xiweier', 'scqhLOL_delaiwen', 'scqhLOL_feiaona', 'scqhLOL_akali', 'scqhLOL_gailun', 'scqhLOL_yatuokesi', 'scqhLOL_delaiesi', 'scqhLOL_mofeite', 'scqhLOL_seti', 'scqhLOL_yasuo'],
				scqhFgo: ['scqhFgo_aertuoliya', 'scqhFgo_bawanxi', 'scqhFgo_modeleide', 'scqhFgo_lansiluote', 'scqhFgo_gaowen'],
				scqhJojo: ['scqhJojo_jiliangjiying', 'scqhJojo_dio', 'scqhJojo_kongtiaochengtailang', 'scqhJojo_shashouhuanghou', 'scqhJojo_baijinzhixing', 'scqhJojo_shijie'],
				scqhReZero: ['scqhReZero_lamu', 'scqhReZero_leimu', 'scqhReZero_lamuleimu'],
				scqhGameLife: ['scqhGameLife_kong', 'scqhGameLife_bai'],
				scqhFivesec: ['scqhFivesec_duoduolianglinqin', 'scqhFivesec_meiyin', 'scqhFivesec_yangtingting', 'scqhFivesec_xiongqiezhen', 'scqhFivesec_xingyewangzi', 'scqhFivesec_tianxiangyouli', 'scqhFivesec_wuqiyuan', 'scqhFivesec_bailiuqi', 'scqhFivesec_heiyanyaye', 'scqhFivesec_xiangzhuiling', 'scqhFivesec_wannianqingyizhi', 'scqhFivesec_shaonianx'],
				scqhAcg: ['scqhAcg_aigenisi', 'scqhAcg_xuenaishendong', 'scqhAcg_renzheshashou', 'scqhAcg_feiduan', 'scqhAcg_cangyue', 'scqhAcg_cangyue2', 'scqhMagia_lumuyuan', 'scqhAcg_gula'],
				scqhGu: ['scqhGu_bainingbing'],
				scqhZhinv: ['scqhZhinv_caoang', 'scqhZhinv_luotong', 'scqhZhinv_xiahoushi', 'scqhZhinv_liuqi', 'scqhZhinv_zhonghui', 'scqhZhinv_wusong', 'scqhZhinv_xiaoqiao', 'scqhZhinv_guanyu', 'scqhZhinv_zhangsong', 'scqhZhinv_ganning', 'scqhZhinv_liubei', 'scqhZhinv_guanyingping', 'scqhZhinv_zhangjiao', 'scqhZhinv_simayi', 'scqhZhinv_zhouchu', 'scqhZhinv_xusheng', 'scqhZhinv_baosanniang', 'scqhZhinv_zhangsanfeng', 'scqhZhinv_chensheng', 'scqhZhinv_dengai'],
			},
		},
		character: {
			scqh_tanyuan: ['female', 'western', 4, ['scqhAdd_addSkill'], []],
			scqh_shenchunqianhe: ['female', 'western', 4, ['scqhBasic_huanbian', 'scqhBasic_luanjiao', 'scqhBasic_fenyin', 'scqhBasic_zhajing'], []],
			scqhGu_bainingbing: ['female', 'qun', 4, ['scqhGu_gushi', 'scqhGu_lengyan', 'scqhGu_chebing', 'scqhGu_baixiang'], []],
			scqhJojo_dio: ['male', 'western', 8, ['scqhJojo_shijie', 'scqhJojo_kuanggu'], ['zhu']],
			scqhJojo_kongtiaochengtailang: ['male', 'western', 4, ['scqhJojo_baijinzhixing'], []],
			scqhJojo_jiliangjiying: ['male', 'western', 4, ['scqhJojo_shashouhuanghou', 'scqhJojo_kuweichuanxin'], []],
			scqhJojo_shijie: ['none', 'western', Infinity, ['scqhJojo_shijie'], []],
			scqhJojo_baijinzhixing: ['none', 'western', Infinity, ['scqhJojo_baijinzhixing'], []],
			scqhJojo_shashouhuanghou: ['none', 'western', Infinity, ['scqhJojo_shashouhuanghou'], []],
			scqhPcr_kelisitina: ['female', 'western', 5, ['scqhPcr_shuyu', 'scqhPcr_shuanggou', 'scqhPcr_qinghai'], []],
			scqhPcr_lingnai: ['female', 'western', 5, ['scqhPcr_chuanxin', 'scqhPcr_shuchi', 'scqhPcr_liegong'], []],
			scqhPcr_peikelimu: ['female', 'western', 5, ['scqhPcr_yongxi', 'scqhPcr_shengyan', 'scqhPcr_kongfu'], []],
			scqhPcr_linai: ['female', 'western', 5, ['scqhPcr_rimian', 'scqhPcr_huixin', 'scqhPcr_wencai'], []],
			scqhPcr_xuefei: ['female', 'western', 5, ['scqhPcr_wuzhan', 'scqhPcr_eryu', 'scqhPcr_tabing', 'scqhPcr_juebing'], []],
			scqhPcr_xue: ['male', 'western', 5, ['scqhPcr_mihun', 'scqhPcr_xuanmu', 'scqhPcr_qiaozhuang'], []],
			scqhPcr_chun: ['female', 'western', 5, ['scqhPcr_biyu', 'scqhPcr_qiyu', 'scqhPcr_kuijia'], []],
			scqhPcr_yiliya: ['female', 'western', 5, ['scqhPcr_gouyue', 'scqhPcr_hongxing', 'scqhPcr_xueshi', 'scqhPcr_youtai'], ['clan:血族']],
			scqhPcr_yiliya2: ['female', 'western', 5, ['scqhPcr_gouyue', 'scqhPcr_hongxing', 'scqhPcr_xueshi', 'scqhPcr_tongye'], ['clan:血族']],
			scqhPcr_zhenna: ['female', 'western', 5, ['scqhPcr_mieguang', 'scqhPcr_weixiang', 'scqhPcr_jianzang', 'scqhPcr_huangcai'], ['zhu']],
			scqhPcr_qiunai: ['female', 'western', 5, ['scqhPcr_chixin', 'scqhPcr_xuanxiao', 'scqhPcr_qianjin'], []],
			scqhPcr_jita: ['female', 'western', 5, ['scqhPcr_jifeng', 'scqhPcr_jianyi', 'scqhPcr_qiling'], []],
			scqhPcr_jitasix: ['female', 'western', 5, ['scqhPcr_xinghe', 'scqhPcr_yaoguang', 'scqhPcr_dielang'], []],
			scqhPcr_youjiali: ['female', 'western', 5, ['scqhPcr_shahu', 'scqhPcr_duzhuo', 'scqhPcr_jili'], []],
			scqhPcr_zhuxi: ['female', 'western', 5, ['scqhPcr_juesheng', 'scqhPcr_jipin', 'scqhPcr_lueying'], []],
			scqhLOL_yasuo: ['male', 'western', 4, ['scqhLOL_zhanfeng', 'scqhLOL_tafeng', 'scqhLOL_juexi'], []],
			scqhLOL_kaiyin: ['male', 'western', 4, ['scqhLOL_zhiyi', 'scqhLOL_lueying', 'scqhLOL_sheying'], []],
			scqhLOL_kaiyinred: ['male', 'western', 4, ['scqhLOL_kaiyinkuanggu', 'scqhLOL_lueying', 'scqhLOL_sheying'], []],
			scqhLOL_kaiyinblack: ['male', 'western', 4, ['scqhLOL_lueying', 'scqhLOL_sheying'], []],
			scqhLOL_xiweier: ['female', 'western', 4, ['scqhLOL_xuanren', 'scqhLOL_tanshe', 'scqhLOL_shoulie'], []],
			scqhLOL_seti: ['male', 'western', 4, ['scqhLOL_haoqing', 'scqhLOL_lielu', 'scqhLOL_hongquan'], []],
			scqhLOL_gailun: ['male', 'western', 4, ['scqhLOL_guyong', 'scqhLOL_wuwei', 'scqhLOL_shenpan', 'scqhLOL_caijue'], []],
			scqhLOL_feiaona: ['female', 'western', 4, ['scqhLOL_xinyan', 'scqhLOL_pokong', 'scqhLOL_jianwu'], []],
			scqhLOL_delaiwen: ['male', 'western', 4, ['scqhLOL_rongyao', 'scqhLOL_huiren', 'scqhLOL_kaidao'], []],
			scqhLOL_akali: ['female', 'western', 4, ['scqhLOL_qianlong', 'scqhLOL_hanying', 'scqhLOL_xiazhen', 'scqhLOL_sunwu'], []],
			scqhLOL_delaiesi: ['male', 'western', 4, ['scqhLOL_zhican', 'scqhLOL_chongwu', 'scqhLOL_chuwang'], []],
			scqhLOL_yatuokesi: ['male', 'western', 4, ['scqhLOL_cisi', 'scqhLOL_chongjue', 'scqhLOL_damie'], []],
			scqhLOL_mofeite: ['male', 'western', 5, ['scqhLOL_fuyan', 'scqhLOL_dizhen'], []],
			scqhMiao_huangyueying: ['female', 'shu', 3, ['scqhMiao_jizhi', 'scqhMiao_qicai'], []],
			scqhMiao_zhangxingcai: ['female', 'shu', 4, ['scqhMiao_shenxian', 'scqhMiao_qiangwu'], []],
			scqhMiao_zhurong: ['female', 'shu', 4, ['scqhMiao_jvxiang', 'scqhMiao_lieren', 'scqhMiao_changbiao'], ['clan:喵蛮族']],
			scqhMiao_wangyi: ['female', 'wei', 4, ['scqhMiao_zhenlie', 'scqhMiao_miji'], []],
			scqhMiao_zhenji: ['female', 'wei', 3, ['scqhMiao_luoshen', 'scqhMiao_qingguo'], []],
			scqhMiao_diaochan: ['female', 'qun', 3, ['scqhMiao_lijian', 'scqhMiao_biyue'], []],
			scqhMiao_zhangchunhua: ['female', 'wei', 4, ['scqhMiao_jueqing', 'scqhMiao_shangshi'], []],
			scqhMiao_caiwenji: ['female', 'qun', 3, ['scqhMiao_mozhi', 'scqhMiao_beige'], []],
			scqhZhinv_zhangsanfeng: ['male', 'qun', 4, ['scqhZhinv_budao', 'scqhZhinv_taiji'], []],
			scqhZhinv_ganning: ['male', 'wu', 4, ['scqhZhinv_qixi', 'scqhZhinv_jieying', 'scqhZhinv_jinfan'], []],
			scqhZhinv_simayi: ['male', 'jin', 4, ['scqhZhinv_renjie', 'scqhZhinv_baiyin', 'scqhZhinv_lianpo'], []],
			scqhZhinv_zhouchu: ['male', 'wu', 4, ['scqhZhinv_xianghai', 'scqhZhinv_chuhai'], []],
			scqhZhinv_chensheng: ['male', 'qun', 4, ['scqhZhinv_qiyi'], []],
			scqhZhinv_zhonghui: ['female', 'wei', 4, ['scqhZhinv_quanji', 'scqhZhinv_paiyi'], []],
			scqhZhinv_caoang: ['male', 'wei', 4, ['scqhZhinv_kangkai', 'mashu'], []],
			scqhZhinv_luotong: ['male', 'wu', 4, ['scqhZhinv_qinzheng'], []],
			scqhZhinv_xiahoushi: ['female', 'shu', 3, ['scqhZhinv_yanyu', 'scqhZhinv_qiaoshi'], []],
			scqhZhinv_liuqi: ['female', 'qun', 4, ['scqhZhinv_wenji', 'scqhZhinv_tunjiang'], []],
			scqhZhinv_wusong: ['male', 'qun', 4, ['scqhZhinv_tanbei', 'scqhZhinv_zuijiu'], []],
			scqhZhinv_guanyu: ['male', 'shu', 4, ['scqhZhinv_wusheng', 'scqhZhinv_guanjue', 'scqhZhinv_zhuihun', 'hongyan'], []],
			scqhZhinv_zhangsong: ['male', 'shu', 3, ['scqhZhinv_qiangzhi', 'scqhZhinv_xiantu'], []],
			scqhZhinv_liubei: ['male', 'shu', '6/6', ['scqhZhinv_longnu', 'scqhZhinv_jieyingliubei'], []],
			scqhZhinv_zhangjiao: ['female', 'qun', 4, ['scqhZhinv_guidao', 'scqhZhinv_leijie', 'scqhZhinv_fubing'], []],
			scqhZhinv_xiaoqiao: ['female', 'wu', 3, ['scqhZhinv_hongyan', 'scqhZhinv_huimou'], []],
			scqhZhinv_baosanniang: ['female', 'shu', 3, ['scqhZhinv_jiaoniang', 'scqhZhinv_xushen'], []],
			scqhZhinv_guanyingping: ['female', 'shu', 4, ['scqhZhinv_xueji', 'scqhZhinv_wuji'], []],
			scqhZhinv_dengai: ['male', 'wei', 4, ['scqhZhinv_qizhi', 'scqhZhinv_tuntian', 'scqhZhinv_zaoxian'], []],
			scqhZhinv_xusheng: ['male', 'wu', 4, ['scqhZhinv_pojun', 'scqhZhinv_yicheng', 'scqhZhinv_huiwanxusheng'], []],
			scqhKoihime_lvbu: ['female', 'qun', 5, ['scqhKoihime_jidao', 'scqhKoihime_baguan', 'scqhKoihime_liyu'], []],
			scqhKoihime_weiyan: ['female', 'shu', 4, ['scqhKoihime_kuanggu', 'scqhKoihime_aosi'], []],
			scqhKoihime_lejin: ['female', 'wei', 4, ['scqhKoihime_xiaoguo', 'scqhKoihime_xiandeng'], []],
			scqhKoihime_zhangliao: ['female', 'qun', 4, ['scqhKoihime_tuxi', 'scqhKoihime_dengfeng', 'scqhKoihime_zhengbing'], []],
			scqhKoihime_luzhi: ['female', 'qun', 4, ['scqhKoihime_zhuyan', 'scqhKoihime_yaoyi'], []],
			scqhKoihime_caochun: ['female', 'wei', 4, ['scqhKoihime_shanjia', 'scqhKoihime_yanjun'], []],
			scqhKoihime_zhangxun: ['female', 'qun', 4, ['scqhKoihime_suizheng'], []],
			scqhKoihime_huangfusong: ['female', 'qun', 4, ['scqhKoihime_chaozhen', 'scqhKoihime_guanhuo', 'scqhKoihime_jvxia'], []],
			scqhKoihime_taishici: ['female', 'wu', 4, ['scqhKoihime_yaodou', 'scqhKoihime_hanzhan'], []],
			scqhKoihime_lidian: ['female', 'wei', 4, ['scqhKoihime_wangxi', 'scqhKoihime_xunxun'], []],
			scqhKoihime_hetaihou: ['female', 'qun', 4, ['scqhKoihime_zhendu', 'scqhKoihime_qiluan'], []],
			scqhKoihime_hejin: ['female', 'qun', 4, ['scqhKoihime_zhaobing', 'scqhKoihime_mouzhu', 'scqhKoihime_yanhuo', 'scqhKoihime_nidang'], []],
			scqhKoihime_luxun: ['female', 'wu', 4, ['scqhKoihime_zuishu', 'scqhKoihime_dushi', 'scqhKoihime_qianxun'], []],
			scqhKoihime_chengong: ['female', 'qun', 3, ['scqhKoihime_mingce', 'scqhKoihime_zhichi', 'scqhKoihime_feita'], []],
			scqhKoihime_jiaxu: ['female', 'qun', 4, ['scqhKoihime_zhenlue', 'scqhKoihime_jianshu', 'scqhKoihime_luanwu'], []],
			scqhKoihime_zhaozhong: ['female', 'qun', 4, ['scqhKoihime_chiyan', 'scqhKoihime_huangkong'], []],
			scqhKoihime_huanggai: ['female', 'wu', 4, ['scqhKoihime_kurou', 'scqhKoihime_zhaxiang'], []],
			scqhKoihime_mizhu: ['female', 'shu', 4, ['scqhKoihime_ziyuan', 'scqhKoihime_jvjia'], []],
			scqhKoihime_mifang: ['female', 'shu', 4, ['scqhKoihime_fengshi', 'scqhKoihime_yongjue'], []],
			scqhKoihime_sunqian: ['female', 'shu', 4, ['scqhKoihime_qianya', 'scqhKoihime_shidao'], []],
			scqhKoihime_dongzhuo: ['female', 'qun', 4, ['scqhKoihime_wuwang', 'scqhKoihime_xiahui', 'scqhKoihime_lianzhu'], []],
			scqhKoihime_machao: ['female', 'shu', 4, ['scqhKoihime_tieqi', 'scqhKoihime_fuchou'], []],
			scqhKoihime_madai: ['female', 'shu', 4, ['scqhKoihime_qianxi', 'scqhKoihime_fuchou'], []],
			scqhKoihime_tianfeng: ['female', 'qun', 4, ['scqhKoihime_sijian', 'scqhKoihime_luoyu', 'scqhKoihime_suishi'], []],
			scqhKoihime_chendeng: ['female', 'qun', 4, ['scqhKoihime_tuntian', 'scqhKoihime_ziliang'], []],
			scqhKoihime_caohong: ['female', 'wei', 4, ['scqhKoihime_kangkai', 'scqhKoihime_jvzi', 'scqhKoihime_xiaozhang'], []],
			scqhKoihime_chengyu: ['female', 'wei', 3, ['scqhKoihime_yiyi', 'scqhKoihime_danshou'], []],
			scqhKoihime_lusu: ['female', 'wu', 4, ['scqhKoihime_kaizeng', 'scqhKoihime_dimeng'], []],
			scqhKoihime_zhangzhao: ['female', 'wu', 4, ['scqhKoihime_zhenggu', 'scqhKoihime_lijian'], []],
			scqhKoihime_xuhuang: ['female', 'wei', 4, ['scqhKoihime_zhiyan', 'scqhKoihime_shipo'], []],
			scqhKoihime_yujin: ['female', 'wei', 4, ['scqhKoihime_zhenjun', 'scqhKoihime_yizhong', 'scqhKoihime_meizhuang'], []],
			scqhKoihime_zhangjiao: ['female', 'qun', 4, ['scqhKoihime_tianlai', 'scqhKoihime_dianmou', 'scqhKoihime_shengge'], []],
			scqhKoihime_zhangbao: ['female', 'qun', 4, ['scqhKoihime_guhuo', 'scqhKoihime_ezhao', 'scqhKoihime_zhoufu'], []],
			scqhKoihime_zhangliang: ['female', 'qun', 4, ['scqhKoihime_choubing', 'scqhKoihime_binghuo'], []],
			scqhKoihime_yuanshao: ['female', 'qun', 4, ['scqhKoihime_luanji', 'scqhKoihime_tushe'], ['zhu']],
			scqhKoihime_yuanshu: ['female', 'qun', 3, ['scqhKoihime_manchong', 'scqhKoihime_jiaoheng', 'scqhKoihime_miyi'], []],
			scqhKoihime_huaxiong: ['female', 'qun', 4, ['scqhKoihime_yaowu', 'scqhKoihime_yangwei'], []],
			scqhKoihime_menghuo: ['female', 'qun', 4, ['scqhKoihime_xizhan', 'scqhKoihime_miaobian'], ['zhu', 'clan:喵蛮族']],
			scqhKoihime_liuhong: ['female', 'qun', '4/12', ['scqhKoihime_nishi', 'scqhKoihime_shuzheng', 'scqhKoihime_mengbi'], ['zhu']],
			scqhKoihime_liuxie: ['female', 'qun', 3, ['scqhKoihime_tianming', 'scqhKoihime_shouxi', 'scqhKoihime_mizhao'], ['zhu']],
			scqhKoihime_gongsunzan: ['female', 'qun', 4, ['scqhKoihime_yicong', 'scqhKoihime_jiaomeng'], []],
			scqhKoihime_yanyan: ['female', 'shu', 4, ['scqhKoihime_jvzhan', 'scqhKoihime_jiuhao'], []],
			scqhKoihime_chengpu: ['female', 'wu', 4, ['scqhKoihime_pinchun', 'scqhKoihime_yuancong'], []],
			scqhKoihime_dianwei: ['female', 'wei', 4, ['scqhKoihime_qiangxi', 'scqhKoihime_ninge'], []],
			scqhKoihime_zhugeliang: ['female', 'shu', 3, ['scqhKoihime_kanpo', 'scqhKoihime_miaoji', 'scqhKoihime_cangzhuo'], []],
			scqhKoihime_pangtong: ['female', 'shu', 3, ['scqhKoihime_manjuan', 'scqhKoihime_yangming', 'scqhKoihime_zhanji'], []],
			scqhKoihime_liubei: ['female', 'shu', 4, ['scqhKoihime_rende', 'scqhKoihime_jishan'], ['zhu']],
			scqhKoihime_guanyu: ['female', 'shu', 4, ['scqhKoihime_zhuizhan', 'scqhKoihime_qingwu'], []],
			scqhKoihime_huangzhong: ['female', 'shu', 4, ['scqhKoihime_lueying', 'scqhKoihime_yingwu', 'scqhKoihime_shuangrui'], []],
			scqhKoihime_zhangfei: ['female', 'shu', 4, ['scqhKoihime_paoxiao', 'scqhKoihime_lihu'], []],
			scqhKoihime_caoren: ['female', 'wei', 4, ['scqhKoihime_lifeng', 'scqhKoihime_sujun'], []],
			scqhKoihime_zhaoyun: ['female', 'shu', 4, ['scqhKoihime_gudan', 'scqhKoihime_longyou'], []],
			scqhKoihime_sunjian: ['female', 'wu', 5, ['scqhKoihime_hupo', 'scqhKoihime_yingsa', 'scqhKoihime_pojun'], ['zhu']],
			scqhKoihime_sunce: ['female', 'wu', 4, ['scqhKoihime_jiang', 'scqhKoihime_yingyang', 'scqhKoihime_zhiba'], ['zhu']],
			scqhKoihime_sunquan: ['female', 'wu', 4, ['scqhKoihime_zhiheng', 'scqhKoihime_bingxin', 'scqhKoihime_chengye'], ['zhu']],
			scqhKoihime_sunshangxiang: ['female', 'wu', 3, ['scqhKoihime_jieyi', 'scqhKoihime_xiaoji', 'scqhKoihime_banhu'], []],
			scqhKoihime_zhouyu: ['female', 'wu', 4, ['scqhKoihime_yingzi', 'scqhKoihime_liangfen', 'scqhKoihime_lingren'], []],
			scqhKoihime_zhoutai: ['female', 'wu', 4, ['scqhKoihime_buqv', 'scqhKoihime_youzhu'], []],
			scqhKoihime_lvmeng: ['female', 'wu', 4, ['scqhKoihime_qinxue', 'scqhKoihime_botu', 'scqhKoihime_limou'], []],
			scqhKoihime_caocao: ['female', 'wei', 4, ['scqhKoihime_xieling', 'scqhKoihime_shanyu', 'scqhKoihime_jiaozi'], []],
			scqhKoihime_xunyu: ['female', 'wei', 4, ['scqhKoihime_qvhu', 'scqhKoihime_jieming', 'scqhKoihime_xianfu'], []],
			scqhKoihime_guojia: ['female', 'wei', 4, ['scqhKoihime_tiandu', 'scqhKoihime_guicai', 'scqhKoihime_chouce'], []],
			scqhKoihime_xiahouyuan: ['female', 'wei', 4, ['scqhKoihime_shensu', 'scqhKoihime_qingxi'], []],
			scqhKoihime_xiahoudun: ['female', 'wei', 4, ['scqhKoihime_ganglie', 'scqhKoihime_xuehen'], []],
			scqhAcg_feiduan: ['male', 'western', 4, ['scqhAcg_sixue', 'scqhAcg_tongming', 'scqhAcg_xietu'], []],
			scqhGameLife_kong: ['male', 'western', 4, ['scqhGameLife_kong', 'scqhGameLife_shekong', 'scqhGameLife_shimeng'], ['zhu', 'hiddenSkill']],
			scqhGameLife_bai: ['female', 'western', 3, ['scqhGameLife_bai', 'scqhGameLife_shekong', 'scqhGameLife_aizhidan'], ['zhu', 'hiddenSkill']],
			scqhReZero_lamu: ['female', 'western', 4, ['scqhReZero_xiamu', 'scqhReZero_weifeng'], []],
			scqhReZero_leimu: ['female', 'western', 4, ['scqhReZero_guibian'], []],
			scqhReZero_lamuleimu: ['female', 'western', 7, ['scqhReZero_guibian2', 'scqhReZero_xiamu'], []],
			scqhAcg_aigenisi: ['female', 'western', 5, ['scqhAcg_guishen', 'scqhAcg_jianmie', 'scqhAcg_yinmo'], []],
			scqhAcg_xuenaishendong: ['female', 'western', 4, ['scqhAcg_moxue', 'scqhAcg_tunke', 'scqhAcg_xiongsha'], []],
			scqhAcg_renzheshashou: ['male', 'western', '2/4', ['scqhAcg_kuangchan', 'scqhAcg_juejing'], []],
			scqhAcg_gula: ['female', 'western', 3, ['scqhAcg_anliu'], ['hiddenSkill']],
			scqhAcg_cangyue: ['female', 'western', 4, ['scqhAcg_xuedao', 'scqhAcg_shuangshi'], ['dualside:scqhAcg_cangyue2']],
			scqhAcg_cangyue2: ['female', 'western', 3, ['scqhAcg_qingnang'], ['dualside:scqhAcg_cangyue']],
			scqhMagia_lumuyuan: ['female', 'western', 1, ['scqhMagia_qiyuan', 'scqhMagia_huakai'], []],
			scqhDiy_jiutiaoaili: ['female', 'western', '3/4', ['scqhDiy_guxing', 'scqhDiy_eyu', 'scqhDiy_shanyao'], []],
			scqhDiy_jiushizhengjin: ['male', 'western', '3/4', ['scqhDiy_guxin', 'scqhDiy_tongxiao', 'scqhDiy_chongjing'], []],
			scqhDiy_jiu: ['female', 'wu', '3/4', ['scqhDiy_jiwang', 'scqhDiy_qifeng'], []],
			scqhFivesec_tianxiangyouli: ['female', 'western', '3/4', ['scqhFivesec_wubei'], []],
			scqhFivesec_wuqiyuan: ['male', 'western', 4, ['scqhFivesec_zhuren', 'scqhFivesec_dengli'], []],
			scqhFivesec_xiongqiezhen: ['male', 'western', 5, ['scqhFivesec_jingang', 'scqhFivesec_zhanjue'], []],
			scqhFivesec_meiyin: ['female', 'western', 4, ['scqhFivesec_xifa'], []],
			scqhFivesec_duoduolianglinqin: ['female', 'western', '3/4', ['scqhFivesec_xinzhan'], []],
			scqhFivesec_yangtingting: ['female', 'western', 4, ['scqhFivesec_renran'], []],
			scqhFivesec_bailiuqi: ['male', 'western', '3/4', ['scqhFivesec_guibian', 'scqhFivesec_qicai'], []],
			scqhFivesec_xiangzhuiling: ['female', 'western', 4, ['scqhFivesec_feiqi', 'scqhFivesec_jieshan'], []],
			scqhFivesec_xingyewangzi: ['male', 'western', '3/4', ['scqhFivesec_tiebi', 'scqhFivesec_bihu'], []],
			scqhFivesec_heiyanyaye: ['male', 'western', 4, ['scqhFivesec_jiedai', 'scqhFivesec_shenyi'], []],
			scqhFivesec_wannianqingyizhi: ['male', 'western', 4, ['scqhFivesec_guibian', 'guicai'], []],
			scqhFgo_aertuoliya: ['female', 'qun', 4, ['scqhFgo_qiangyun', 'scqhFgo_shiyue', 'scqhFgo_wangdao'], ['NobleKnight']],
			scqhFgo_modeleide: ['female', 'qun', 4, ['scqhFgo_yangmu', 'scqhFgo_panxi'], ['NobleKnight']],
			scqhFgo_lansiluote: ['male', 'qun', 4, ['scqhFgo_wulian', 'scqhFgo_duofeng'], ['NobleKnight']],
			scqhFgo_bawanxi: ['female', 'qun', 4, ['scqhFgo_huantong', 'scqhFgo_zouku'], []],
			scqhFgo_gaowen: ['male', 'qun', 4, ['scqhFgo_shengke', 'scqhFgo_buye'], ['NobleKnight']],
		},
		characterIntro: {
			scqh_shenchunqianhe: ['神椿千鹤', '</br>【角色形象】', '不老不死的魅魔,精通变身系魔法,总是以各种美少女的形象出现在人前,而见过她真容的人物早已化作历史的尘埃,其本人也将真实的自己遗忘在了遥远的过去.', '据她自称,幼时的梦想是成为魔族中首屈一指的大魔导师,为此攻读了许多方面的书籍,其中也包括不少色色的书？'].join('</br><br/>'),
			scqhDiy_jiutiaoaili: ['<ul>设计者:周树人', '<br/>【设计描述】', '<br/><li>艾莉表面上是个很高冷的人,而被其他人疏远.', '<br/><li>艾莉对于自己的目标一往无前,打算仅凭自己完成一切达到终点,不需要任何帮助,亦或是对除目标以外的东西不看一眼,也是证明自己一个人什么都做得到,够得到任何目标.', '<br/><li>艾莉有时候会用俄语说一句话,认为旁人不明白自己的意思而偷乐.'].join('</br>'),
			scqhDiy_jiushizhengjin: '设计者:周树人',
			scqhDiy_jiu: '设计者:逢星化云',
			scqhAcg_gula: '噶呜·古拉 < Gawr Gura > <br/><br/><li>叫喊着「海底真是无聊透顶」而来到陆地上的亚特兰蒂斯的后裔. <br/><br/><li>身上穿着的中意的衣服(含鲨鱼头套)是在日本买的.据本人说有空的时候喜欢和海洋生物聊天.',
			scqhMagia_lumuyuan: '鹿目圆<br/><br/><li>就读于市立见泷原中学二年级,性格温柔,很为朋友着想,在朋友间有着很好的品格.家庭由父母和弟弟组成的四人家族.原本过着平凡而安稳的每一天的她,因遇上丘比而陷入一连串事件.某一天,圆遭遇一场不可思议的邂逅,她还不清楚这个相遇究竟是偶然还是必然,但是确定的是那已经改变了自己的生活、改变了自己命运的邂逅.在最终话与丘比定下契约,愿望是让所有魔女消失在诞生之前,由于愿望反叛了整个因果律,制定了新的魔法少女规则,因此圆成为了神,创造了一个魔法少女最后不会变成魔女的世界,这个愿望的结局是所有人看不见她,听不到她的声音,她将没有起始和完结,也等同于从来没有过这个人,但是晓美焰仍保存对她的记忆.<br/><br/><li>变身成魔法少女后粉红色的灵魂宝石(soul gem)悬挂在颈部,配备武器为带著花苞的长弓,拉满弓时花苞会绽放开来并点燃粉色的火焰.漫画版使用的是刻有花纹的一般木弓,动画中可自由创造能量箭矢,可进行散射或连射,在最终的变身衣饰改变,并多了白色的羽翼.在重组后的世界,小圆会在魔法少女们变成魔女前夕将她们接走.这种魔法少女最终必定会凭空消失的「法则」被魔法少女们称为「圆环之理」.',
			scqhFivesec_duoduolianglinqin: ['<ul>多多良林檎', '<br/><li>高中生.18岁.网络游戏world logic play的玩家之一,是KEY的粉丝,一直希望与他见面.知道启是KEY,又被他连续救了两次后喜欢上他.在第三项目加入红队,之后加入绿队.', '<br/><li>能力:复制对手能力的十分之一.', '<br/><li>确认对象并对他使用能力的话,就能得知他的能力,此外还能复制那个能力的十分之一.本人认为劣化复制是没有用的,但是这个能力的真正价值是将能力的优点和缺点全部变为十分之一(例如:复制大炮的十分之一威力,两轮炮击的时间装填时间也是十分之一,所以可以以10倍的速度进行连射),不是劣化复制,而是作为全新的能力使用.'].join('</br>'),
			scqhFivesec_meiyin: ['<ul>魅音', '<br/><li>于动漫、漫画中登场时,魅音有着紫色的短发和眼睛,还有猫耳和尾巴.曾亲自出现在现实世界击杀白柳启,将其带入魅音所属的第五监视人小队.她对于白柳启格外关注,会经常亲切的称他为<我的王子殿下>,对他本人也有超高的自信.魅音有着超强的头脑,和让人摸不通的思维逻辑,实力超强.', '<br/><li>能力:魔术师(未公开).'].join('</br>'),
			scqhFivesec_yangtingting: ['<ul>杨婷婷', '<br/><li>身穿旗袍,闭着眼睛的女性.', '<br/><li>能力:千里眼.', '<br/><li>能将视线之内的事物推移一千年.'].join('</br>'),
			scqhFivesec_tianxiangyouli: ['<ul>天翔优利', '<br/><li>高中生.十七岁.从小开始便有很多不幸的经历,身边的人总会说只是偶然,因此十分讨厌<偶然>这个字.有一个没有血缘关系的妹妹.为人充满正义感,绝不放过欺负弱小的人.', '<br/><li>能力:把身体能力变成五倍.', '<br/><li>身体能力全部变成五倍,包括奔跑速度、弹跳力、腕力、握力,挥拳的力量有着被车撞一样的伤害.弱点是很难适应五倍的身体能力,最初不能正常行动.可是,由于优利的野性不训练也能熟悉使用这个能力.'].join('</br>'),
			scqhFivesec_wuqiyuan: '<ul>雾崎圆<br/><br/><li>高中生.十七岁.在第一项目与启战斗,被打败后对他产生了执著,决心要打败他.在第三项目加入蓝队.在<国王狩猎>中加入红队一方,向启发起挑战,但在战斗途中被龙胆妨碍,因此与启联手将其击败.<br/><br/><li>能力:把树枝变成什么都能斩断的剑.<br/><br/><li>把手里拿着的树枝变成不管什么都能切断的剑.剑的长度是树枝的长度.剑离开身体数秒后自动变回树枝.虽然什么都能斩断,但只有同样能力的剑是不能斩断的.虽然说明写的是树枝,但只要是手可以拿住的木头都可以变成剑来使用,斩断什么可以为雾崎的认知,例如能力.',
			scqhFivesec_bailiuqi: '<ul>白柳启<br/><br/><li>高中生.十六岁.学业成绩优异.好吃金平糖.对现实生活感到无聊,因此追求能随时沉迷其中的游戏.在一次上学途中被怪物袭击,虽然成功将其解决,但最后被魅音击杀.之后参加组织举行的游戏,决定要再一次与魅音战斗,并且摧毁组织.在第三项目加入绿队.起初对任何人都是抱着利用的心态,但与优利相遇后渐渐改变,开始愿意相信他人.<br/><br/><li>能力:使用对方设想的能力.<br/><br/><li>这个能力要发动必须有『对方』,『对方』不仅仅是启指定为能力对象,对方也必须认识到启是自己战斗的对象,也可以是同伴(帮手).即使『对方』认为启拥有两种能力,他也不能同时使用两种能力.',
			scqhFivesec_xiongqiezhen: '<ul>熊切真<br/><br/><li>职业摔跤手.三十三岁.有一个哥哥叫熊切武,在他很小的时候为了保护孩子而卷入事故身亡.在第三项目加入绿队.对组织的行为深感不屑,因此不打算使用他们给予的能力,但在<国王狩猎>中为了保护同队的晴花而决定使用能力.<br/><br/><li>能力:2秒内无敌.<br/><br/><li>发动后变成全身铠甲的姿态,无效化所有攻击.',
			scqhFivesec_xiangzhuiling: '<ul>香椎铃<br/><br/><li>洋红色长发,后挑染黑色.面容锋锐妩媚,丰姿冶丽.身材窈窕,曲线柔美.常穿蝉翼式样的粉色内衣,后外穿长款粉色羽绒服,战斗时会脱掉,目的是受伤出血越多,越能用大量的血液制造出强力武器.<br/><br/><li>能力:将体液转变为拷问刑具.<br/><br/><li>目前已知可生效体液:血液、汗水、唾液、眼泪.',
			scqhFivesec_shaonianx: '<ul><li>能力:把有价值的东西变成炸弹.',
			scqhFivesec_heiyanyaye: '<ul>黑岩雅也<br/><br/><li>第三项目红队的副首领.<br/><br/><li>能力:将自己借出的东西强制索取回来.<br/><br/><li>自己借出东西之后可以以命令和支配的方式强制索要,能够支配的时间长短与可以命令到什么程度是由<所借之物>本身决定的,虽然产生<借贷>的方法很多,但是必须从意识层面和对手形成借贷关系,如果对方完全没有动心的话能力是无法发动的.',
			scqhKoihime_lvbu: ['吕布(真名:恋／字:奉先)', '</br>【角色形象】', '以三国无双的强大夸耀于后世的最强的武人.无口・无表情,很难搞懂她在想什么的角色.因为太过强大,没有人愿意接近吕布身边,总是孤独一人的少女.总是用金银的形式获得赏赐,因而被周围的人暗地里议论为守财奴.不过本人对此毫不在意.偷偷养着弃犬与弃猫,最好的朋友是威尔斯柯基犬的濑人.', '「……反抗的话,杀了你」'].join('</br></br>'),
			scqhKoihime_weiyan: ['魏延(真名:焰耶／字:文长)', '</br>【角色形象】', '迷上了刘备,以与刘备H作为一大目标,却总是被关羽与张飞、诸葛亮她们妨碍. 虽然性格中有着对自己过分自信的一面,但其实是经不起打的类型. 平常虽然口吐强势发言,把别人当笨蛋,但犯了某些错误的时候却会在人迹不至的地方独自沮丧. 讨厌狗.', '「谁能战胜我～!」'].join('</br></br>'),
			scqhKoihime_hetaihou: ['何太后(真名:瑞姬／字:？？？)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_hejin: ['何进(真名:倾／字:遂高)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_chengong: ['陈宫(真名:音音音／字:公台)', '</br>【角色形象】', '被小孩子们嘲笑为<小个小个>欺负时被来到洛阳的吕布所救,从那以后因仰慕吕布而与她一起行动.', '辅佐着天然呆的吕布,向其出谋划策就是陈宫的任务.伴随着<陈宫ー飞ー踢!>的喊叫声随时参上.', '老是踢飞一刀,与其争夺吕布.然而吕布对之则是兴趣全无,仍然一副呆样.好伙伴是吕布的养犬,圣伯纳德犬的张々(ちょうちょう).', '「吕布殿下～!陈宫将追随吕布殿下到天涯海角～」'].join('</br></br>'),
			scqhKoihime_luxun: ['陆逊(真名:稳／字:伯言)', '</br>【角色形象】', '周瑜的爱徒,辅佐周瑜的少女副军师.人格稳重,深受孙权・甘宁・周瑜的信赖.虽然语调思考慢条斯理,但其实是个相当的才能之士.因为性格温柔,对于周瑜采取的冷酷的策略内心里其实是反对的,不过基本上来说坚持了中立的立场.很喜欢看书,令人困扰的是一旦被她发现了美妙的书籍,似乎就会产生性冲动.', '「啊哈哈、你真行啊、小孔明.没想到被这么漂亮地将计就计～」'].join('</br></br>'),
			scqhKoihime_lejin: ['乐进(真名:凪／字:文谦)', '</br>【角色形象】', '与吕布不同,为冷酷系已登峰造极的无口・无表情・无感情的三无角色.有人(主要是李典和于禁)犯傻时,会用冰冷的目光代替吐槽盯着那人来吐槽.与李典、于禁常常一起行动,默默地听着她们两人饶舌.倒也并不是讨厌与她们两人在一起,只不过因为自己说不出什么应景的话,所以考虑着说话就交给她们两人好了.其实对于女孩味心怀憧憬,偷偷练习着料理与裁缝等女红.', '「唯余……前进一途.」'].join('</br></br>'),
			scqhKoihime_zhangliao: ['张辽(真名:霞／字:文远)', '</br>【角色形象】', '看重武与义,充满侠气的性格.但与之相反的是思考方式十分灵活,脑筋转得也很快.不过最讨厌卑鄙的勾当.认为既然要战那就堂堂正正地战,在某个意义上又有着干脆利落的性格.基本上不会在战斗中夹带个人私怨,只是单纯地凭借着想要与强者战斗的欲望来回奔驰于战场的少女.', '「我只是想要与强者战斗,证明自己是最强的而已!」'].join('</br></br>'),
			scqhKoihime_luzhi: ['卢植(真名:风铃／字:子干)', '</br>【角色形象】', '她在当地的寺庙和学校教书育人,但在黄巾起义期间,她被朝廷邀请担任将军.', '她不适合打仗,军事才能也不强,但她凭借自己的知识和智慧打了不少胜仗. 风铃心地善良,活跃在很多地方,因此很多士兵都很喜欢她.', '她对自己的脸有一种情结,因为这让她看起来比同龄人年轻;她对自己的大胸也有一种情结,因为这让她一无是处.', '她是蜀军暗地里的的领军人物,她肯定了桃香的长处,并在她对自己的未来不确定时给了她建议.', '「但你不希望别人这么说你吧？ 但是桃香只要努力就能做到,风铃觉得她甚至能成为英雄,所以继续努力吧!没错!」'].join('</br></br>'),
			scqhKoihime_zhangxun: ['张勋(真名:七乃／字:？？？)', '</br>【角色形象】', '从袁术小时起就侍奉在她身边的保镖兼跑腿兼武将.也是负责吐槽兼激励的角色.袁术之所以性格恶劣在某个意义上说是这个人的责任也并不为过.从小时候开始就对袁术身为太守发挥自己的力量(=对他人落井下石)大加赞美,献上了无数骚扰战术的女子.然而本人对此毫无自觉,只是凭着「为了最爱的袁术大人……」的一心,为了让袁术平步青云而出谋划策.'].join('</br></br>'),
			scqhKoihime_jiaxu: ['贾诩(真名:咏／字:文和)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_zhaozhong: ['赵忠(真名:黄／字:？？？)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_huanggai: ['黄盖(真名:祭／字:公覆)', '</br>【角色形象】', '孙家的老臣,据说为孙家效力多年黄盖小时候用过的马桶还在仓库里放着呢.武官,但是能把身为文官的周瑜耍得团团转.所以这就是周瑜打黄盖的原因？十分宠爱孙尚香传说中的隔代亲？'].join('</br></br>'),
			scqhKoihime_huangfusong: ['皇甫嵩(真名:楼杏／字:义真)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_taishici: ['太史慈(真名:梨晏／字:子义)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_lidian: ['李典(真名:真樱／字:曼成)', '</br>【角色形象】', '乐进的搭档,多嘴欢乐型角色.自犯傻自吐槽说个不亦乐乎.口头禅是「来啦来啦!」、「吵死～了!」(自犯傻自吐槽)等等.魏的前线指挥官兼任兵器采办官.会私吞预算,出于自己的兴趣制作一些莫名其妙的破烂玩意.同时还制作着与曹操同床共寝用的「成人玩具」.', '「我的螺旋不是普通的螺旋!是在曹孟德麾下冲破那天的螺旋!」'].join('</br></br>'),
			scqhKoihime_mizhu: ['糜竺(真名:雷／字:？？？)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_mifang: ['糜芳(真名:电／字:？？？)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_sunqian: ['孙乾(真名:美花／字:公祐)', '</br>【角色形象】', '被盗贼抓住的时候被桃香他们救了,之后担任带桃香的女仆兼从事(像辅佐官一样的).以支撑桃香和一刀为生存意义,家务整体及辅佐的精华.', '不说超出必要的话,一直挂着温柔的笑容.一旦被问到什么问题都能明确回答,头脑清晰.如果被命令的话,无论什么事情都会用爱情来服务的温柔姐姐.', '「呵呵,晚上的照顾也是女仆的职责.请不要客气,请用我的身体.」', '「主人的要求才是我最幸福的吗～」'].join('</br></br>'),
			scqhKoihime_tianfeng: ['田丰(真名:真直／字:元皓)', '</br>【角色形象】', '袁绍军中的首席军师.', '在被逃亡的袁绍--文丑推来推去的同时,他日以继夜地为袁家夺取江山出谋划策.', '他和颜良一起,是袁家的良心.他还要做袁绍--文丑的追随者,卷入袁绍--文丑的抑郁之中,让人忧心忡忡.', '无论她如何运筹帷幄,袁绍的爆发都会让她大发脾气,这些天她常常心灰意冷,但她还是强忍着泪水,努力为袁家做事.', '「毛毛,据说元皓就是袁家的人. 喂,猪若子,叫你不要动! 哦,你怎么也往前走了,刘小姐! 我不是叫你不要动吗？」'].join('</br></br>'),
			scqhKoihime_chendeng: ['陈登(真名:喜雨／字:元龙)', '</br>【角色形象】', '陈珪的女儿,她的头饰与众不同.', '与母亲不同,她在政治的浪潮中遨游,计算着各种力量的强弱,而她却在扎根一地、耕耘土地中找到了乐趣.', '在她这个年纪,她已经是农业政策方面的专家,也是一个受老百姓尊敬的女孩. 然而,她除了和武士们一起修修补补之外,对其他事情太不感兴趣,有时会被误认为是怪人,但她并不介意. 在遇到北乡伊藤之后,孤傲的啸女--如美--会表现出她的真心吗？', '她和美食家华琳是很好的朋友.', '「当没有一个人取笑农民,并坚持认为他们不会因此而吃掉自己的那份食物时,我想他们都有了可以依靠的肩膀,没有什么可说的了」'].join('</br></br>'),
			scqhKoihime_dongzhuo: ['董卓(真名:月／字:仲颖)', '</br>【角色形象】', '将汉王朝追逼至灭亡之境的罪魁祸首、残暴无极限的非人类……虽说她本应是这样的人,不过其实本人性格弱气,有着自责的倾向.总是一副战战兢兢的样子,但对主人公则是拼命努力地侍奉着他.因为基本上来说厌恶战争,加入主人公军门之后作为主人公的专属女仆生活着.', '「讨厌战斗……但是如果非战不足以生存的话,我想唯有努力……」'].join('</br></br>'),
			scqhKoihime_zhaoyun: ['赵云(真名:星／字:子龙)', '</br>【角色形象】', '有着细长而清秀的眼睛,舞动于空中的长发,仿佛舞蹈一般击败敌人的勇者.性格很酷,对于美有着只属于自己的坚持,但因为其之美意识与他人有着相当的偏差,显得很是奇异.<br/><br/>喜欢的食物是笋干与酒.如果酒与笋干被他人横刀夺爱的话,就会发动絮絮叨叨絮絮叨叨絮絮叨叨絮絮叨叨的语言攻势.<br/><br/>爱好是装作「蝴蝶假面」带着一种自认为个性(人人都有不同的观点)的面具以「正义」之名去讨伐一些不良人物.', '「北方常山赵子龙,回应主人的期待,于此参上! 汝等就尽管倒伏在吾枪之前,流淌着擦之不近的鲜血,暴尸于光天化日之下吧!」'].join('</br></br>'),
			scqhKoihime_yuanshao: ['袁绍(真名:丽羽／字:本初)', '</br>【角色形象】', '自信满满的大小姐样.对于自己出身于三国第一的名家感到自豪,将穷人当笨蛋.最喜欢女孩子,角色与曹操无限重叠的人物.本人也深有自觉,对曹操的憎恨在常人以上.总之是个可喜可贺的笨蛋.', '「哦～呵～呵～呵～!身为三国第一的名家的本小姐,怎么可能输给你这样的男人呢!」'].join('</br></br>'),
			scqhKoihime_zhouyu: ['周瑜(真名:冥琳／字:公瑾)', '</br>【角色形象】', '吴国的大军师,也是孙策的好友.', '从<理>与<利>的角度判断事物的现实主义者.不过因为有着能理解幽默的能力,意外地也有着诙谐的一面.', '深爱着孙策、深爱着吴国,胸中暗藏激情的女性.', '在孙策死去后,为了完成吴国的统一大业而作为吴国的军师辅佐孙权,却暗中对不及先王的孙权失望,与孙权实际上处于割裂状态,执行任务时也并不十分尽心尽力.', '一个例子便是孙吴援助进攻魏国的蜀军时暗中影响孙权军的粮草供给,使其不得不提前撤军.', '同时,在与蜀国结盟时,还派出了自己的两个<宠物>、大乔和小乔作为人质,实际上目的是去色诱北乡一刀.', '魏国灭亡后,为了推进吴国统一大业,和找上门来的于吉达成一致,伪造吴军进攻蜀国的假象以挑动蜀军出兵,并借此在吴国内部宣称蜀国进攻,使两国爆发战争.', '在北乡军攻打吴国、俘获吴王孙权后,在吴国剩余的土地上扬起<周>的旗帜,并与北乡军开战.在战斗失败,大势已去时,回到吴都的大殿,与最亲密的朋友孙策所坐过的龙椅共焚自尽,最后一次向孙策、和孙策的统一之梦尽忠.', '「为了实现孙吴的天下,赌上我全部的才能.……伯符.我一定会让你成为天下人」'].join('</br></br>'),
			scqhKoihime_yuanshu: ['袁术(真名:美羽／字:公路)', '</br>【角色形象】', '袁绍的堂妹,荆州太守.讨厌袁绍,在与黄巾党战斗时虽然不情不愿地与之协力战斗,但在反董卓联合军终了的阶段时则与其完全诀别.不愧出生名家,任意妄为.再加上张勋还宠着她使得她娇生惯养,结果变成了更横行霸道的脑残的孩子.', '美羽是个任性傲娇的萝莉公主,跟她的姐姐丽羽一样,对于治理领地方面也是很无能,曾因这一点而被爱纱吐槽,发型也跟丽羽很像,自称在姐姐面前完全变得没有气势,喜欢在被别人夸奖后说<是啊是啊,继续夸我吧>.对唱歌很有天赋,喜欢唱歌后喝蜂蜜水.', '「蜂蜜!妾身想要蜂蜜!」'].join('</br></br>'),
			scqhKoihime_pangtong: ['庞统(真名:雏里／字:士元)', '</br>【角色形象】', '卧龙凤雏中的凤雏.之前隶属于水镜女学院,与好友朱里一起,为了尽量拯救苦于此战乱之世的庶人而离开女学院.相当重度的认生,害羞.因而总是深戴一个大檐帽子.虽然与朱里同样不擅长应付男性,不过对于温柔的一刀则很喜欢.不太会主动向人搭话,而是以目传情.', '「啊哇哇、主人,我们遇到埋伏啦!」'].join('</br></br>'),
			scqhKoihime_liubei: ['刘备(真名:桃香／字:玄德)', '</br>【角色形象】', '桃香是个典型的天然系萌妹,虽然是结义三姐妹中的大姐,但看上去完全不像,笨手笨脚,在国内外一致被评价为「天然」.武器是宝剑【靖王传家】.由于看上去实在能力欠缺,也曾被质疑是否有当王的资质.不过虽是重度天然系,但也有很坚强、甚至很固执的一面.<br/><br/>相比于曹魏靠霸道、孙吴靠血缘建立的势力,桃香的蜀汉则是靠情义招来各地武将和军师.桃香与爱纱、铃铃相遇后,结拜为义姐妹,一同为结束乱世而奔走,日后建立蜀汉王朝,登位为王.'].join('</br></br>'),
			scqhKoihime_guanyu: ['关羽(真名:爱纱／字:云长)', '</br>【角色形象】', '爱纱有傲娇属性,为人认真,不知变通,还有着嫉妒心的一面,对于美女、美少女型的人物多少有些嫉妒.在战斗中,一般是很冷静、严肃的,偶尔也会出现莽夫行为.不知是否因为爱纱的勇猛,她在敌方武将中存在着仰慕者,但爱纱对同性没有兴趣.另外,爱纱作为一名勇将,却还怕怪物、幽灵之类的存在.爱纱的料理水平最初是惨不忍睹,不过随着练习,逐渐像样子了.', '爱纱自幼父母双亡,她还有一个哥哥,但已在战乱中山贼的袭击中去世.爱纱多少有点兄控情结.为了不让自己的悲伤发生生其他人身上,建立一个和平的世界,爱纱踏上了武者修行的旅途.对于从小认识的铃铃,爱纱像妹妹一样对待.'].join('</br></br>'),
			scqhKoihime_zhangfei: ['张飞(真名:铃铃／字:翼德)', '</br>【角色形象】', '双亲被山贼所杀,从小时起就和远离村庄身为猎手的祖父一起生活在山中的小屋里.但自从祖父去世之后就和村里的一帮玩伴一起组了个「铃铃山贼团」,每天都去骚扰山脚下的村庄.第一话遇到关羽后「改邪归正」走上了武者修行之旅,并认关羽为姐姐.年纪虽然很小但力气很大,性格冒冒失失,是个大胃,喜欢再走山路的时候唱避熊歌(虽然不怎么受人欢迎),十分喜欢及依赖关羽这个姐姐,有时也不免很可爱地吃醋,当孔明加入队伍时,会为关羽偏袒她而生气.是个脾气暴躁的女孩,但却不失可爱.口头禅是<～なのだ>.'].join('</br></br>'),
			scqhKoihime_zhoutai: ['周泰(真名:明命／字:幼平)', '<br/>【角色形象】', '原本只是个庶人,在与黄巾党之战时加入吴军一方参战,被孙策看中.也因为与孙权年岁相近,被提拔为孙权护卫队的一员,之后与甘宁一起辅佐着孙权.耿直而纯情.然而对于迷上的他则是无微不至侍奉型的傲娇系大和抚子.感服于孙策的武力,也痴迷于孙权的人性美……而且也开始喜欢上了一刀.'].join('</br></br>'),
			scqhKoihime_sunjian: ['孙坚(真名:炎莲／字:文台)', '<br/>【角色形象】', '孙家之主,孙策之母,东吴的奠基人.'].join('</br></br>'),
			scqhKoihime_sunce: ['孙策(真名:雪莲／字:伯符)', '<br/>【角色形象】', '孙权之姊,东吴之王.吴路线中对突然出现的一刀一个激灵,策划着想让他成为孙权的伴侣,将一刀带回吴国.开朗而平易近人,不过自然也有身为王的威严,对吴国来说正可谓是英雄王般的存在.给予同伴无限的慈悲,给予敌人无情的恐怖.会保持着微笑斩下敌人的首级,在许多意义上都的确是一个可怕的存在.', '「母亲大人……孙吴的宿愿,我一定会完成给您看」'].join('</br></br>'),
			scqhKoihime_sunquan: ['孙权(真名:莲华／字:仲谋)', '<br/>【角色形象】', '吴国君主,孙策的妹妹,孙尚香的姐姐.因为上任君主姐姐孙策的早逝,所以年纪轻轻就当上了君主的少女.由于处与和被誉为名君的孙策相比较的立场,因此经常鞭策自己,说要做个名君,要做一个堂堂正正的名将.', '「为了守护吴国……为了守护美好的吴国百姓,我将要战斗!赌上孙家的尊严与性命!」'].join('</br></br>'),
			scqhKoihime_sunshangxiang: '【姓名】孙尚香(真名:小莲／字:？？)<br/><br/><br/>【身份背景】<br/><br/>孙策与孙权的妹妹,不愧是小妹,二人都很疼爱她.但是小莲自身却想亲自成为再兴孙吴的力量,作为前线指挥官统率军队.然而二人都对小莲踏上战场一事不以为然.天真烂漫的小恶魔.好奇心旺盛,什么事都想插一腿的淘气包.但因为是天然系,就算拼命地出谋划策也会被立刻看穿的类型.<br/><br/><br/>【角色台词】<br/><br/>「胆敢与吴为敌的家伙,本小大人来好好调教你的说!」',
			scqhKoihime_huangzhong: ['黄忠(真名:紫苑／字:汉升)', '<br/>【角色形象】', '拥有能与弓之神·曲张相比的弓技.与温和的外表和用稳重的口调来说话的姿势相反的是,非常喜欢H的事情,经常诱惑一刀,又喜欢妄想,一想象到一刀和其他女子的H事情,就呼吸急促以至于经常被女儿璃璃责备.', '「呵呵,主人的已经变这么大了,让我帮你平息下去好吗？」'].join('</br></br>'),
			scqhKoihime_huaxiong: '【姓名】华雄(真名:猫／字:子健)<br/><br/><br/>【身份背景】<br/><br/>董卓军的猛将,在与反董卓联合的战斗时与张辽一起守护着汜水关.自负自己的武技是天下最强,自尊心很强的性格.也有着为部下着想的侧面,华雄队兵士之间的团结十分牢固.被关羽轻松料理.',
			scqhKoihime_caocao: ['曹操(真名:华琳／字:孟德)', '</br>【角色形象】', '身高只有一米四,却是大陆的霸者、冷酷无比的谋略家和猛将,让人谈虎色变的少女.是讨厌男人的女同性恋.为了把大陆上的女子变成宠物,以称霸大陆为目的地挺身而出.超级虐待狂、超级任性、超级自信的人物.对只看一眼就十分中意的关羽,却侍奉作为男人的一刀而吃不下饭.所以为了得到关羽而发动了战争.', '但在霸气的表面下,内心却是很孤独很寂寞,华琳是高高在上的君主,没有称之为同伴的人来分享自己的内心,在单机游戏中北乡一刀(男主角)和璃璃(黄忠之女)看穿了华琳的内心.', '「这个世上的所有美女,全归我所有.这可是上天安排好的事情呦!」'].join('</br></br>'),
			scqhKoihime_caohong: ['曹洪(真名:荣华／字:子廉)', '</br>【角色形象】', '曹操的表妹,魏军中的金库管理员.她可以在一定程度上领导军队,但她更有能力收钱和管理资产.', '她掌握着魏军的全部辎重.虽然率领军队也能大显身手,但相比之下集资和资产运用的能力更高.', '身边是曹氏一族特有的钻发美女,自己也是一位美女,但也是一个变态,把自己的生命赌在把她们打扮得漂漂亮亮并爱上她们上.', '她比卡琳更毒舌,是一个行动派的年轻女士,如果有什么浪费钱的事情,她就会马上说教.', '「男人又臭又脏...... 离我远点!」', '「我还会在你两腿之间挂上一些烧焦的木棍.」'].join('</br></br>'),
			scqhKoihime_xunyu: ['荀彧(真名:桂花／字:文若)', '</br>【角色形象】', '着迷于曹操身为王的器量・天运・才能,奉献上了一切的少女.虽然是个将辱骂调教当成幸福快乐的超变态,不过其对象仅限于曹操.曹操也宠爱着这样的荀彧——作为军师,也作为夜间的宠物.最讨厌笨蛋,将春兰与一刀当成眼中钉.虽然也有因为他们是笨蛋的关系,不过恐怕更重要的原因是将他们认定为围绕曹操的情敌了吧.', '「啊啊、华琳大人……桂花是华琳大人的狗……请多调教我……」'].join('</br></br>'),
			scqhKoihime_guojia: ['郭嘉(真名:禀／字:奉孝)', '</br>【角色形象】', '只要作为实战时进言战术的军师侍奉在曹操身边.一直很冷静,即使面对曹操也口不择言,用刺耳的语调进言・谏言.然而只是没说出口,其实喜欢曹操喜欢到不得了,常常幻想着被曹操调教的SCENE,狂喷鼻血而倒.性格别扭,在拒绝了曹操的同床共寝的邀请,曹操退步后又会自我沮丧,条件反射型的小古怪.与荀彧的关系不太好.', '「呵呵……如今你们已无法逃出我的手掌心.那么,进行下一步棋吧」'].join('</br></br>'),
			scqhKoihime_menghuo: ['孟获(真名:美以／字:？？)', '</br>【角色形象】', '向着称霸了益州的刘备她们挑战的南蛮之王.带领着数量众多的量产型南蛮兵,品尝着暴君式的女王大人的心情.「领土大增的话,就能吃到许多美味的东西,许多的人都会向我低头哈腰,好像很厉害的样子,我们去战吧!」虽然这样子意气扬扬,结果反而被蜀军抓住了７回.', '「想要让美以投降的话,就抓住美以７回试试喵!」'].join('</br></br>'),
			scqhKoihime_madai: ['马岱(真名:蒲公英／字:？？)', '</br>【角色形象】', '马超的表妹. 尊敬憧憬着表姐马超,想要尽可能地接近她. 马超也很珍惜爱护马岱. 虽然尚称武勇,但也因为体格的关系,比马超她们要低一个等级. 与魏延的关系不是很好.'].join('</br></br>'),
			scqhKoihime_caoren: ['曹仁(真名:华仑／字:子孝)', '</br>【角色形象】', '曹操的表妹.作为曹氏家族的一员,她有着美丽的外表,但其粗鲁、莲花状的行为却是她性格的显著特点.', '她是个行动派,想到什么就做什么,不假思索.然而,她95%的行为都会适得其反或引起一些麻烦,因此她与孪生姐妹的春兰并称为麻烦制造者.', '此外,她对春兰的爱慕仅次于华琳,两人经常在一起,这让秋兰很苦恼.', '因为她是一个内心正直善良的女孩,所以深受魏国的伙伴们的喜爱.', '「我感冒了,如果我不穿衣服,感冒就会痊愈,对吗？」'].join('</br></br>'),
			scqhKoihime_gongsunzan: ['公孙瓒(真名:白莲／字:伯珪)'].join('</br></br>'),
			scqhKoihime_yanyan: ['严颜(真名:桔梗／字:光玉)', '</br>【角色形象】', '痴迷于饮酒的豪爽人物. 与黄忠同样,具有年轻武将人母+义姐属性的淫靡系工口御姐.好战,战时虽然用弓作为武器却喜欢带头冲在前面的类型. ', '「醉心于美酒、醉心于美食、醉心于战斗.人生快哉也!」'].join('</br></br>'),
			scqhKoihime_chengpu: ['程普(真名:粹怜／字:德谋)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_dianwei: ['典韦(真名:流琉／字:恶来)'].join('</br></br>'),
			scqhKoihime_yujin: ['于禁(真名:沙和／字:文则)', '</br>【角色形象】', '与乐进・李典并列曹魏三杰的一人.前线部队的指挥官,新兵的训练教官.', '某天,受到一刀教授的Heart○an军曹式训练的启发,导入了Ame○ca海军部队式训练.', '追求时髦,喜欢衣服与小首饰.一旦发现心水物就会向乐进推荐,被简单的一句<不要>给驳回.对于魅力点的雀斑,则是有点点在意的年龄.', '「曹魏的兵士没有许可可不准死哦～.所以迟钝的家伙都给我切了蛋蛋让废渣的家系绝子绝孙哦～」'].join('</br></br>'),
			scqhKoihime_chengyu: ['程昱(真名:风／字:仲德)', '</br>【角色形象】', '平常看似傻傻的,但出谋划策时则会不含感情、平淡地献上冷酷的策略,有着两幅面孔的类型.老在睡觉,军事会议时也会打瞌睡而被怒骂,但其实内容则是一句不漏地听在耳里,并进一步表达自己对其的意见.与郭嘉和荀彧的关系都不错,是二人发牢骚的共同对象.郭嘉狂喷鼻血失去意识的时候,一直都是程昱在照顾她.最喜欢晒太阳与睡午觉.', '「太阳者,闪耀于此世之英雄.我想要侍奉那位英雄,亲手支撑这轮太阳───」'].join('</br></br>'),
			scqhKoihime_lusu: ['鲁肃(真名:包／字:子敬)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_zhangzhao: ['张昭(真名:雷火／字:子布)', '</br>【角色形象】'].join('</br></br>'),
			scqhKoihime_xuhuang: ['徐晃(真名:香风／字:公明)'].join('</br></br>'),
			scqhKoihime_caochun: ['曹纯(真名:柳琳／字:子和)', '</br>【角色形象】', '曹仁的妹妹,曹操的堂妹. ', '她是曹氏家族中一位谦逊文静的太守,与她的姐姐相比,她是一个喜欢读书的学者型历史学家,而她的姐姐是一个不假思索的持枪太保.', '这并不是说她软弱,曹纯领导的虎豹骑部队虽然人数不多,却是魏军中最精锐的部队,在人数相当的情况下,甚至有能力突破春兰部队.', '「华仑姐,你太鲁莽了.好担心、好担心、好担心」'].join('</br></br>'),
			scqhKoihime_machao: ['马超(真名:翠／字:孟起)', '</br>【角色形象】', '马超,弗兰切斯卡学院2年.关羽军武将.', '直突猛进,一旦看见敌人就会一股劲往前冲,就算前面是陷阱也会凭借着蛮力将其粉碎!', '是个精神十足的女孩,不过因为精神十足过头,同时也是个马大哈的冒失少女.行动先于思考的类型,暴走机车.虽然属于体育会系,其实是最有少女风范的女孩也说不定.', '</br>【角色经历】', '父母双亡后开始武者修行之旅.第三话中在袁绍招募家将的时候与张飞相遇,又在第四话(第二天)与杀父仇人(实则并不是)曹操相遇,因怒气难平便刺杀曹操,后被抓,为关羽所救.知父亲之死与曹操无关后离开张飞等人回到故乡告知乡亲真相.是个很男孩子气的女孩,精神十足,同样冒冒失失.同张飞一样也是个大胃,曾与其一起参加大胃比赛.', '「吾之长枪为刺穿邪恶的白银之枪!　给我像个坏人一般老实点吃上一枪,你个混蛋!」'].join('</br></br>'),
			scqhKoihime_zhangjiao: ['张角(真名:天和／字:？？)', '</br>【角色形象】', '张角,绰号小天,是个超天然的呆～～～～呆的萌妹,也是张家三姐妹中的长女,但是没什么才能,全是靠着妹妹张宝、张梁的帮助.因为贫困而在街头卖艺唱歌,被张宝的有点暴走气质的煽动与张梁的冷静的经营活动,不知不觉间就成为了闻名大陆的偶像,结果误解导致新的误解,最终形成了名为黄巾党的类似粉丝俱乐部的组织.', '虽然是个鼻涕虫,不过一哄就破涕为笑,任性随意的性格.作为偶像积累了不少人气,自然而然地就变得独断专行,一旦不如自己的意就会「讨厌讨厌讨厌!」地发牢骚,张宝的吐槽(被殴)就如期而至,接着向张梁哭诉……这样的相声一次次地重复着.'].join('</br></br>'),
			scqhKoihime_zhangbao: ['张宝(真名:地和／字:？？)', '</br>【角色形象】', '张宝,绰号小地,妖术使(主要在舞台的烟幕演出与聚光灯等方面使用).', '张家三姉妹的次女,暴走煽动家.为了让自家姐妹成为闻名大陆的偶像,在各地举行现场演唱会.可是在煽动粉丝俱乐部时事态发展至无法控制的地步导致了暴走.结果成为了闻名后世的黄巾之乱.', '与姐姐张角不同,热血偶像.被曹操托付负责提高士气,向着偶像之道大步迈进.「绯闻是偶像的基本!」在这个想法的影响下,对一刀恶作剧结果反被推倒,变成了一个很喜欢Ｈ的女孩.', '胸部很贫.三姉妹中最贫.'].join('</br></br>'),
			scqhKoihime_zhangliang: ['张梁(真名:人和／字:？？)', '</br>【角色形象】', '张梁,绰号人炭(レンたん).身为张家三姉妹的三女,作为冷静而且现实的超级经理人兼偶像组合的一人活跃着.', '张梁作为经理人的能力很杰出,也因为三女的功绩,张家三姉妹成为了全大陆具有相当人气的偶像组合.学究眼镜的内部,同居着智慧与奸计(经理)的女子.'].join('</br></br>'),
			scqhKoihime_lvmeng: '【姓名】吕蒙(真名:亚莎／字:子明)<br/><br/><br/>【身份背景】<br/><br/>被孙策相中,加入孙坚幕下的下级士官.用吊眼梢威吓他人一般的锐利眼神,以及冷淡的性格.但其实只是因为眼睛生来不好,不知不觉就会变成凶恶的眼神.不过本人对其则是十分在意,因为太过在意而胆怯于与人进行交流.与周泰关系不错.<br/><br/><br/>【角色台词】<br/><br/>「努力!努力学习!」',
			scqhKoihime_zhugeliang: '【姓名】诸葛亮(真名:朱里／字:孔明)<br/><br/><br/>【身份背景】<br/><br/>与张飞相反的很懂事的好孩子性格,胆小害羞,聪明温柔,虽是内向的性格但具有刀剑近在眼前也不会动摇的胆识.<br/><br/>非常喜欢被人摸头,几乎不会抱怨,最初有将自己的想法藏在内心畏畏缩缩不往前的性格,经常勉强自己的情况,但跟着大家相处后渐渐开始改变.<br/><br/>战斗中经常提出许多出色的计谋.「哈哇哇」是她的口头禅,所以被人称为「哈哇哇军师」.料理技术也非常厉害,在动画中常常担任厨师一职.非常的喜欢书,经常在读书,其中也包括不少色色的书？现在本人似乎是处于思春期的状态..........',
			scqhKoihime_xiahouyuan: '【姓名】夏侯渊(真名:秋兰／字:妙才)<br/><br/><br/>【身份背景】<br/><br/>夏侯惇的双胞胎妹妹、曹操的爱人.也是曹操倚为左右手的武人.与姐姐・夏侯惇一起将其身心都献给了曹操.与姐姐不同,总是能保持冷静沉着.酷酷地辅佐着仿佛坏掉了刹车的卡车一般暴走的夏侯惇.虽然貌似悠然地支援着姐姐,但其实其中辛劳有谁知.然而,从心底里深爱着老是给她添麻烦的姐姐.<br/><br/><br/>【角色台词】<br/><br/>「吾等身家性命,只为献于曹孟德」',
			scqhKoihime_xiahoudun: ['夏侯惇(真名:春兰／字:元让)', '</br>【角色形象】', '曹操的堂妹兼爱人.也是曹操倚为左右手的武人.夏侯渊是她双胞胎的妹妹.心与身体,其之全部都献给了曹操,只要是敢于与曹操为敌者,就算是天王老子也是若不残杀誓不罢休般性格难缠.感情冲动,猪突猛进,天然系笨蛋,体育会系.但是那正是其萌点的女子.', '「吾之大剑乃魏武之剑!不怕夏侯元让的管你几只尽管来战!」'].join('</br></br>'),
			scqhPcr_chun: '<li>【基础信息】<br/>全名:白银纯<br/>公会:王宫骑士团(NIGHTMARE)<br/>种族:人类<br/>兴趣:格斗技、泡澡<br/>简评:不以真面目示人,冷静沉着的女性骑士<br/><br/><li>【背景资料】<br/>王宫骑士团的团长,平时在王宫门口担任守卫,一天24小时都穿着铠甲站在王宫前,因此看不清人脸.<br/><br/>由于身上的铠甲常常被误认为是男性,因自身职责原因会感到寂寞,很羡慕那些盛装打扮的女孩子们,面对突然来访的骑士会感到很警觉和惊讶.<br/><br/>被摘掉头盔后会表现出非常不自然的一面.虽然王宫骑士团规模逐渐缩小,但面对需要帮助的人还是愿意出手相助. <br/><br/>在某次执行任务时受伤晕倒,被骑士所救,带到了咲恋救济院,也借由这个机会,骑士得以摘下纯的头盔(但实际上纯还戴着一张面具).后来向骑士表达了自己的心愿,下定决心,想要无所遮掩地,用原本的样貌与某个人(骑士)去游玩.',
			scqhPcr_zhuxi: '<li>【基础信息】<br/>称号:<font color=violet>幻影猫</font><br/>全名:宫坂珠希<br/>公会:墨丘利财团<br/>种族:兽人族<br/>兴趣:与猫玩耍<br/><br/><li>【背景资料】<br/>猫之兽人,经营着一家售卖鲷鱼烧的店,因店铺被墨丘利财团收购而加入了墨丘利财团. 动作敏捷,可轻易跳上悬崖峭壁,在骑士君将要掉下悬崖时将其救下,并且为骑士君舔舐脸上的伤口来消毒. <br/><br/>由于自身的属性,十分喜欢猫,在兰德索尔的某个地方养了许多只猫,一见到小猫挨饿就会同情心泛滥疯狂买猫食,也因此常常入不敷出.<br/><br/>任性而我行我素,但也非常重视自己的伙伴(骑士君).在自己落入大牢之后,因不想连累骑士君而主动撇清与对方的关系,为了不让他与自己以身犯险,安排了一项<不可能>的测试.会因骑士君被绑架而不顾一切地去救,也会因为骑士君的安危而担心流泪.<br/><br/>在夜间是个义贼,自封<幻影猫>,劫富济贫,曾在一个夜晚洗劫了一家专门放高利贷的机构<恶德伊商会>,骑士君对此一无所知.但她却因此遭到了算计,误接委托进入平民家中盗窃,而被丢入牢中.在骑士君的协助下脱狱,而后才知晓了对方的目的.<br/><br/>最终两人合力击溃恶德伊,将截获的财产发放,也回复了<幻影猫>的名誉.后来却得知因自己将<恶德伊商会>击溃,而导致另一恶党商会兴起,<幻影猫>遭到部分商人的诋毁,她对此感到失落,心生逃避之意.在骑士君的引导下重新振作,决意要将<义贼的惩罚行动>进行到底.',
			scqhPcr_lingnai: '<li>【基础信息】<br/>全名:美波铃奈<br/>公会:月光学院<br/>种族:魔族<br/>兴趣:时尚<br/><br/><li>【背景资料】<br/>美波铃奈,是兰德索尔的模特,人气很高,不管走到哪后面都跟着一群女粉丝,在月光学院上学,但成绩很差,差到连最简单的算术都不会算,只得请骑士君帮忙计算,还把骑士君当做秀才(ヒデサイ),甚至还因为与骑士较为亲近而被粉丝当成情侣.',
			scqhPcr_xiaolian: '<li>【基础信息】<br/>全名:佐佐木咲恋<br/>公会:咲恋救济院<br/>种族:精灵<br/>兴趣:经营、茶会<br/><br/><li>【背景资料】<br/>佑树(骑士君)曾失散多年的青梅竹马.目光长远,平时做事讲究效率,为了能高效完成任务想了许多办法,甚至懂得将在其他国家很平常而在兰德索尔罕见的食材倒卖到兰德索尔来获得暴利.<br/><br/>该作中由于众人在与霸瞳皇帝的战斗中失败,导致游戏世界被重置,所有玩家包括咲恋在内都被困在了游戏世界中并被篡改了记忆,而与霸瞳正面作战的骑士君则失去了所有的记忆.所幸的是,虽然被篡改了部分记忆,咲恋仍然还记得那个让她喜欢上炒面面包的青梅竹马,最后也成功与骑士君相认,尽管骑士君仍然没有回忆起过去曾与咲恋相处时的记忆.<br/><br/>咲恋原本属于<王宫骑士团>,后因不满克莉丝提娜的所作所为愤而退出,买了一座房子成立了咲恋救济院,照顾贵族的小孩与收养无家可归的孤儿,绫音和胡桃很喜欢她,把她叫做<咲恋妈妈>,但咲恋认为自己年龄不足这个称呼不适合她.对经常胡闹的好朋友秋乃非常头疼.',
			scqhPcr_qiunai: '<li>【基础信息】<br/>全名:藤堂秋乃<br/>公会:墨丘利财团<br/>种族:人类<br/>兴趣:慈善事业<br/><br/><li>【背景资料】<br/>出身于阿斯特雷亚大陆最有名的的商人世家紫堂,也是家里唯一的女儿,受到父亲的话语的影响而想要成为一个独当一面的商人.说话有大小姐常见的ですわ的口癖.<br/><br/>平常习惯了大小姐的生活,为了能成为独当一面的商人而以庶民购物的方式进行社会实践,但每次都因为太过兴奋,以及脱离常识的金钱观,搞得店里的其他人很困扰.<br/><br/>路痴,毫无方向感,为了克服这个缺陷特意来到森林里进行特训,结果直到太阳下山也没走出森林.',
			scqhPcr_youjiali: '<li>【基础信息】<br/>全名:绫濑由加莉<br/>公会:墨丘利财团<br/>种族:精灵<br/>兴趣:逛商店<br/><br/><li>【背景资料】<br/>公会<墨丘利财团>的会计,外号<人形计算机>.初次见面就教训了以不合理的售价把创伤药卖给骑士君的商人.表面看上去是可靠的大姐姐,但一喝酒就会破功,而且料理水平很差,会把东西烤成碳.<br/><br/>渴望恋情,但苦于一直找不到自己心仪的对象,又讨厌那些只是为了搭讪的轻浮男子,只得每天借酒浇愁并且极其能喝,每次喝酒必喝得醉倒才罢休.总是希望自己喝醉后被别的男人带回家,但总在半路被放生.<br/><br/>喜欢可爱的东西,看到某件自己很喜欢的东西很想买,但考虑到墨丘利财团的经营状况不得不忍痛放弃.后来总算攒够钱后想去买下来结果却已经被买走了.',
			scqhPcr_yiliya: '<li>【基础信息】<br/>全名:伊莉亚・奥恩斯坦<br/>公会:恶魔伪王国军<br/>种族:魔族<br/>兴趣:征服世界<br/><br/><li>【背景资料】<br/>传说中的吸血鬼,太古之时,曾率领魔族和诸神开战的魔族女王.这是魔族中有名的传说,但鲜少有人相信这位女王是实际存在的.也被称为<传说中的大魔王>、<传说中的魔女>.',
			scqhPcr_kelisitina: ['<li>【基础信息】', '称号:<font color=#D3A4FF>誓约女君</font>', '全名:克莉丝提娜·摩根(Christina Morgan)', '公会:王宫骑士团(NIGHTMARE)', '种族:人类', '兴趣:与强敌斗争', '<br/><li>【背景资料】', '国际组织<七冠>的成员之一,王宫骑士团的副团长,生性好战,同样因为王宫骑士团预算缩减而苦恼,但克莉丝提娜并没有像智一样外出找工作,而是为了满足自己的战争欲望带兵在兰德索尔四处惹事,包括某天晚上主动骚扰自卫团.这次事件使得自卫团和王宫骑士团结下了梁子,也让原本属于王宫骑士团的原副团长咲恋退出了王宫骑士团.后来成为王宫骑士团的副团长,但其行为却不见收敛,屡屡找死对头<自卫团>公会的麻烦.', '<br/><li>【姓氏起源】', '克莉丝提娜的姓氏<摩根(Morgan)>,来源于英格兰传说中的魔女摩根勒菲(Morgan Le Fey),传说中亚瑟王的姐姐以及一夜情情妇,反叛的骑士莫德雷德的生母.'].join('</br>'),
			scqhPcr_peikelimu: ['<li>【基础信息】', '称号:<font color=#ffddb9>失落公主</font>', '全名:尤丝蒂亚娜·冯·阿斯特莱亚', '公会:美食殿堂', '种族:人类', '兴趣:边走边吃、料理', '<br/><li>【背景资料】', '公会【美食殿堂】的创建者,口头禅是「ヤバイですね☆」(牙白嘚死内／厉害了呀／超棒的对吧☆)凯露有一句类似的口头禅「ヤバイわよ!」,但后者的负面色彩更多一些,有时候亦使用「おいっす～☆」作为打招呼用的口头禅.', '<br/>大胃王,兴趣是做饭吃饭,可以把一盘堆得像小山似的炒饭全部吃完并且还能继续吃其他食物.只要是能吃的东西,就算是魔兽也能吃给你看.', '<br/>仔细观察可发现其所持的剑有一个类似齿痕的缺口所以有人调侃佩可不仅胃口好,牙口也好.不过设定集揭示了这个缺口实际上是用来把剑固定在剑鞘上的.', '<br/>故事最初其公主身份被霸瞳皇帝用技术手段夺走并遭到了霸瞳皇帝在阿斯特莱亚全国通缉以灭口.为了避免自己被霸瞳皇帝抓到后牵连他人隐瞒了自己的真实姓名四处流浪.流浪途中饿昏,被骑士与可可萝捡到.惊叹于其食量的可可萝为其起了「肚子空空的佩可莉姆(お腹ペコペコのぺコリーヌ)」这一外号.后为了能吃到东西创建了【美食殿堂】公会,但登记的时候需要委派骑士代为登记而不是亲自去.由于喜欢四处旅行(事实是为了躲避霸瞳皇帝的追捕),所以很缺钱,只能在餐饮店打工(实际上还是为了能方便地吃到东西).', '<br/>主线第一部结尾佩可接受了获得新力量的骑士的强化,显现出了觉醒新的形态的征兆(到第二部第一章完全觉醒,似似花将其命名为高达公主形态),最终打败了霸瞳皇帝并夺回了名字与王国.现以夺回的兰德索尔王女身份居住于兰德索尔王宫.', '<br/>曾在前作的结尾短暂露过一面,当时的名字显示的是【？？？】,整个前作剧情以佩可的一句「我的名字叫……」结束.'].join('</br>'),
			scqhPcr_xuefei: ['<li>【基础信息】', '全名:阿贺斗 紫布菜', '公会:美食殿堂', '种族:龙族', '兴趣:读书、伸展', '<br/><li>【背景资料】'].join('</br>'),
			scqhPcr_xue: ['<li>【基础信息】', '全名:虹村雪', '公会:纯白之翼', '种族:精灵', '兴趣:照镜子', '<br/><li>【背景资料】'].join('</br>'),
			scqhPcr_linai: ['<li>【基础信息】', '全名:衣之咲璃乃', '公会:拉比林斯', '种族:人类', '兴趣:缝纫,制作小饰品', '<br/><li>【背景资料】', '自称是佑树失散多年的妹妹,技术高超的弓箭手,时常使用飞箭传书的方法暗中传递消息.', '<br/>记性不好,经常把成语和熟语说错,因此诞生了不少经典名言,如「油断タイ焼き(大敵)」(大意吃京津粥(失荆州);B站译:大意是大梨(敌))等等.', '<br/>静流各种惩罚式暴力行为首当其冲的受害者.', '<br/>「就算是哥哥也不准去碰头发上的那个圈圈!」'].join('</br>'),
		},
		characterTitle: {
			scqh_shenchunqianhe: '千人千面',
			scqhFgo_aertuoliya: '骑士王',
			scqhFgo_lansiluote: '裁决骑士',
			scqhFgo_modeleide: '叛逆骑士',
			scqhFgo_gaowen: '太阳骑士',
			scqhMiao_zhenji: '薄幸的美人',
			scqhMiao_zhurong: '刺美人',
			scqhPcr_peikelimu: '<font color = #ffddb9 >失落公主</font>',
			scqhPcr_zhenna: '<font color = #98fb98 >霸瞳皇帝</font>',
			scqhPcr_zhuxi: '<font color = violet >幻影猫</font>',
			scqhPcr_kelisitina: '<font color = #D3A4FF >誓约女君</font>',
			scqhPcr_yiliya: '<font color = #D3A4FF >夜之统领</font>',
			scqhPcr_yiliya2: '<font color = #D3A4FF >夜之统领</font>',
			scqhDiy_jiu: '<font color= #90EE90 >浮华逝影</font>',
			scqhAcg_cangyue: '冰之暗面',
			scqhAcg_cangyue2: '冰之善面',
			scqhAcg_aigenisi: '赤发魔神',
			scqhAcg_xuenaishendong: '未亡人雪女',
			scqhJojo_dio: '恶人的救世主',
			scqhJojo_jiliangjiying: '杜王町的普通上班族',
			scqhFivesec_meiyin: '魔术师',
			scqhFivesec_yangtingting: '调整者',
			scqhFivesec_wuqiyuan: '真剑师',
			scqhFivesec_bailiuqi: '诡辩家',
			scqhFivesec_xiangzhuiling: '铁处女',
			scqhFivesec_xiongqiezhen: '金刚手',
			scqhFivesec_tianxiangyouli: '鬼神',
			scqhFivesec_xingyewangzi: '邻居',
			scqhFivesec_heiyanyaye: '高利贷',
			scqhFivesec_duoduolianglinqin: '讽刺家',
			scqhFivesec_wannianqingyizhi: '放荡浪子',
			scqhFivesec_shaonianx: '蝇王',
		},
		translate: {
			scqh_shenchunqianhe: '神椿千鹤',
			scqh_tanyuan: '探员',
			scqhLOL_kaiyin: '凯隐',
			scqhLOL_kaiyinred: '拉亚斯特',
			scqhLOL_kaiyinblack: '凯隐',
			scqhLOL_xiweier: '希维尔',
			scqhLOL_delaiwen: '德莱文',
			scqhLOL_feiaona: '菲奥娜',
			scqhLOL_gailun: '盖伦',
			scqhLOL_seti: '瑟提',
			scqhLOL_yasuo: '亚索',
			scqhLOL_akali: '阿卡丽',
			scqhLOL_mofeite: '墨菲特',
			scqhLOL_delaiesi: '德莱厄斯',
			scqhLOL_yatuokesi: '亚托克斯',
			scqhPcr_kelisitina: '克莉丝提娜',
			scqhPcr_zhenna: '真那',
			scqhPcr_yiliya: '伊莉亚·幼',
			scqhPcr_yiliya2: '伊莉亚·御',
			scqhPcr_youjiali: '由加莉',
			scqhPcr_lingnai: '铃奈',
			scqhPcr_qiunai: '秋乃',
			scqhPcr_xiaolian: '咲恋',
			scqhPcr_jita: '姬塔',
			scqhPcr_jitasix: '姬塔',
			scqhPcr_zhuxi: '珠希',
			scqhPcr_xue: '雪',
			scqhPcr_xuefei: '雪菲',
			scqhPcr_linai: '璃乃',
			scqhPcr_peikelimu: '佩可莉姆',
			scqhPcr_chun: '纯',
			scqhPcr_aimeisi: '爱梅斯',
			scqhPcr_hualin: '花凛',
			scqhMiao_zhurong: '祝融',
			scqhMiao_zhenji: '甄姬',
			scqhMiao_diaochan: '貂蝉',
			scqhMiao_wangyi: '王异',
			scqhMiao_zhangxingcai: '张星彩',
			scqhMiao_caiwenji: '蔡文姬',
			scqhMiao_zhangchunhua: '张春华',
			scqhMiao_huangyueying: '黄月英',
			scqhZhinv_simayi: '司马懿',
			scqhZhinv_zhangsanfeng: '张三丰',
			scqhZhinv_baosanniang: '鲍三娘',
			scqhZhinv_guanyingping: '关银屏',
			scqhZhinv_xiahoushi: '夏侯氏',
			scqhZhinv_liubei: '刘备',
			scqhZhinv_zhouchu: '周处',
			scqhZhinv_ganning: '甘宁',
			scqhZhinv_dengai: '邓艾',
			scqhZhinv_zhangsong: '张松',
			scqhZhinv_liuqi: '刘琦',
			scqhZhinv_luotong: '骆统',
			scqhZhinv_caoang: '曹昂',
			scqhZhinv_machao: '马超',
			scqhZhinv_zhonghui: '钟会',
			scqhZhinv_wusong: '武松',
			scqhZhinv_chensheng: '陈胜',
			scqhZhinv_xiaoqiao: '小乔',
			scqhZhinv_guanyu: '关羽',
			scqhZhinv_xusheng: '徐盛',
			scqhZhinv_zhangjiao: '张角',
			scqhKoihime_lvbu: '吕布',
			scqhKoihime_dongzhuo: '董卓',
			scqhKoihime_zhaoyun: '赵云',
			scqhKoihime_guojia: '郭嘉',
			scqhKoihime_mizhu: '糜竺',
			scqhKoihime_mifang: '糜芳',
			scqhKoihime_lejin: '乐进',
			scqhKoihime_zhangliao: '张辽',
			scqhKoihime_huanggai: '黄盖',
			scqhKoihime_zhaozhong: '赵忠',
			scqhKoihime_jiaxu: '贾诩',
			scqhKoihime_chengyu: '程昱',
			scqhKoihime_lusu: '鲁肃',
			scqhKoihime_zhangzhao: '张昭',
			scqhKoihime_machao: '马超',
			scqhKoihime_madai: '马岱',
			scqhKoihime_caochun: '曹纯',
			scqhKoihime_huaxiong: '华雄',
			scqhKoihime_chendeng: '陈登',
			scqhKoihime_tianfeng: '田丰',
			scqhKoihime_zhouyu: '周瑜',
			scqhKoihime_yuanshu: '袁术',
			scqhKoihime_yuanshao: '袁绍',
			scqhKoihime_zhoutai: '周泰',
			scqhKoihime_zhugeliang: '诸葛亮',
			scqhKoihime_pangtong: '庞统',
			scqhKoihime_guanyu: '关羽',
			scqhKoihime_zhangfei: '张飞',
			scqhKoihime_sunce: '孙策',
			scqhKoihime_sunjian: '孙坚',
			scqhKoihime_sunquan: '孙权',
			scqhKoihime_sunshangxiang: '孙尚香',
			scqhKoihime_liubei: '刘备',
			scqhKoihime_huangzhong: '黄忠',
			scqhKoihime_caocao: '曹操',
			scqhKoihime_caoren: '曹仁',
			scqhKoihime_caohong: '曹洪',
			scqhKoihime_xunyu: '荀彧',
			scqhKoihime_menghuo: '孟获',
			scqhKoihime_yanyan: '严颜',
			scqhKoihime_chengpu: '程普',
			scqhKoihime_dianwei: '典韦',
			scqhKoihime_gongsunzan: '公孙瓒',
			scqhKoihime_liuxie: '刘协',
			scqhKoihime_liuhong: '刘宏',
			scqhKoihime_zhangjiao: '张角',
			scqhKoihime_zhangbao: '张宝',
			scqhKoihime_zhangliang: '张梁',
			scqhKoihime_yujin: '于禁',
			scqhKoihime_lvmeng: '吕蒙',
			scqhKoihime_xiahoudun: '夏侯惇',
			scqhKoihime_xiahouyuan: '夏侯渊',
			scqhKoihime_sunqian: '孙乾',
			scqhKoihime_huangfusong: '皇甫嵩',
			scqhKoihime_zhangxun: '张勋',
			scqhKoihime_luzhi: '卢植',
			scqhKoihime_taishici: '太史慈',
			scqhKoihime_lidian: '李典',
			scqhKoihime_hetaihou: '何太后',
			scqhKoihime_luxun: '陆逊',
			scqhKoihime_chengong: '陈宫',
			scqhKoihime_hejin: '何进',
			scqhKoihime_xuhuang: '徐晃',
			scqhKoihime_weiyan: '魏延',
			scqhReZero_lamu: '拉姆',
			scqhReZero_leimu: '蕾姆',
			scqhReZero_lamuleimu: '拉姆蕾姆',
			scqhGameLife_kong: '空',
			scqhGameLife_bai: '白',
			scqhGameLife_like: '里克',
			scqhGameLife_xiubi: '休比',
			scqhAcg_cangyue: '沧月',
			scqhAcg_cangyue2: '小沧月',
			scqhAcg_feiduan: '飞段',
			scqhAcg_gula: '噶呜古拉',
			scqhAcg_aigenisi: '艾格妮丝',
			scqhAcg_xuenaishendong: '雪乃深冬',
			scqhAcg_renzheshashou: '藤木户健二',
			scqhDiy_jiutiaoaili: '九条艾莉',
			scqhDiy_jiushizhengjin: '久世政近',
			scqhDiy_jiu: '啾',
			scqhGu_bainingbing: '白凝冰',
			scqhMagia_lumuyuan: '鹿目圆',
			scqhFivesec_meiyin: '魅音',
			scqhFivesec_yangtingting: '杨婷婷',
			scqhFivesec_wuqiyuan: '雾崎圆',
			scqhFivesec_bailiuqi: '白柳启',
			scqhFivesec_xiangzhuiling: '香椎铃',
			scqhFivesec_xiongqiezhen: '熊切真',
			scqhFivesec_tianxiangyouli: '天翔优利',
			scqhFivesec_xingyewangzi: '星野王子',
			scqhFivesec_heiyanyaye: '黑岩雅也',
			scqhFivesec_duoduolianglinqin: '多多良林檎',
			scqhFivesec_wannianqingyizhi: '万年青伊织',
			scqhFivesec_shaonianx: '少年X',
			scqhFgo_aertuoliya: '阿尔托莉雅',
			scqhFgo_modeleide: '莫德雷德',
			scqhFgo_lansiluote: '兰斯洛特',
			scqhFgo_gaowen: '高文',
			scqhFgo_bawanxi: '芭万·希',
			scqhJojo_dio: '迪奥',
			scqhJojo_kongtiaochengtailang: '空条承太郎',
			scqhJojo_jiliangjiying: '吉良吉影',
			scqhBasic: '造物主',
			scqhGameLife: '游戏人生',
			scqhPcr: '公主连结',
			scqhReZero: '从零开始的异世界生活',
			scqhKoihime: '恋姬演武',
			scqhMiao: '喵娘乱舞',
			scqhZhinv: '织女杀(缝缝缝)',
			scqhLOL: '英雄联盟',
			scqhAcg: '综漫日刊',
			scqhFgo: '命运冠位指定',
			scqhJojo: 'JOJO的奇妙冒险',
			scqhGu: '蛊真人',
			scqhFivesec: '见面5秒开始战斗',
			scqhDiy: '网友投稿',
			metal: '金',
			wood: '木',
			water: '水',
			fire: '火',
			soil: '土',
			goldColor: 'rgb(236,236,130)',
			woodColor: 'rgb(149,202,147)',
			waterColor: 'rgb(150,88,201)',
			fireColor: 'rgb(236,132,106)',
			soilColor: 'rgb(201,159,98)',
			goldColor2: 'rgba(236,236,57,0.3)',
			woodColor2: 'rgba(33,155,10,0.3)',
			waterColor2: 'rgba(29,156,255,0.3)',
			fireColor2: 'rgba(255,51,0,0.3)',
			soilColor2: 'rgba(163,98,0,0.3)',
		},
		dynamicTranslate: {
			scqh_范例(player) {
				if (player.storage.scqh_范例 == true) return '描述A';
				return '描述B';
			},
		},
		skill: {},
	};
	const secondName = {
		scqhPcr_zhenna: '霸曈皇帝',
		scqhKoihime_weiyan: '焰耶',
		scqhKoihime_lvbu: '恋',
		scqhKoihime_dongzhuo: '月',
		scqhKoihime_zhaoyun: '星',
		scqhKoihime_guojia: '禀',
		scqhKoihime_mizhu: '雷雷',
		scqhKoihime_mifang: '电电',
		scqhKoihime_lejin: '凪',
		scqhKoihime_zhangliao: '霞',
		scqhKoihime_huanggai: '祭',
		scqhKoihime_zhaozhong: '黄',
		scqhKoihime_jiaxu: '咏',
		scqhKoihime_chengyu: '风',
		scqhKoihime_lusu: '包',
		scqhKoihime_zhangzhao: '雷火',
		scqhKoihime_machao: '翠',
		scqhKoihime_madai: '蒲公英',
		scqhKoihime_huaxiong: '猫',
		scqhKoihime_chendeng: '喜雨',
		scqhKoihime_tianfeng: '真直',
		scqhKoihime_zhouyu: '冥琳',
		scqhKoihime_yuanshu: '美羽',
		scqhKoihime_yuanshao: '丽羽',
		scqhKoihime_zhoutai: '明命',
		scqhKoihime_zhugeliang: '朱里',
		scqhKoihime_pangtong: '雏里',
		scqhKoihime_guanyu: '爱纱',
		scqhKoihime_zhangfei: '铃铃',
		scqhKoihime_sunce: '雪莲',
		scqhKoihime_sunjian: '炎莲',
		scqhKoihime_sunquan: '莲华',
		scqhKoihime_sunshangxiang: '小莲',
		scqhKoihime_liubei: '桃香',
		scqhKoihime_huangzhong: '紫苑',
		scqhKoihime_caocao: '华琳',
		scqhKoihime_caoren: '华仑',
		scqhKoihime_caohong: '荣华',
		scqhKoihime_caochun: '柳琳',
		scqhKoihime_xunyu: '桂花',
		scqhKoihime_menghuo: '美以',
		scqhKoihime_yanyan: '桔梗',
		scqhKoihime_chengpu: '粹怜',
		scqhKoihime_dianwei: '流琉',
		scqhKoihime_gongsunzan: '白莲',
		scqhKoihime_liuxie: '白汤',
		scqhKoihime_liuhong: '空丹',
		scqhKoihime_zhangjiao: '天和',
		scqhKoihime_zhangbao: '地和',
		scqhKoihime_zhangliang: '人和',
		scqhKoihime_yujin: '沙和',
		scqhKoihime_lvmeng: '亚莎',
		scqhKoihime_xiahoudun: '春兰',
		scqhKoihime_xiahouyuan: '秋兰',
		scqhKoihime_sunqian: '美花',
		scqhKoihime_huangfusong: '楼杏',
		scqhKoihime_zhangxun: '七乃',
		scqhKoihime_luzhi: '风铃',
		scqhKoihime_taishici: '梨晏',
		scqhKoihime_lidian: '真樱',
		scqhKoihime_hetaihou: '瑞姬',
		scqhKoihime_luxun: '稳',
		scqhKoihime_chengong: '音音音',
		scqhKoihime_hejin: '倾',
		scqhKoihime_xuhuang: '香风',
		scqhLOL_xiweier: '战争女神',
		scqhLOL_kaiyin: '影流之镰',
		scqhLOL_kaiyinred: '暗裔杀手',
		scqhLOL_kaiyinblack: '影流刺客',
		scqhLOL_gailun: '德玛西亚之力',
		scqhLOL_feiaona: '无双剑姬',
		scqhLOL_delaiwen: '荣耀行刑官',
		scqhLOL_seti: '腕豪',
		scqhLOL_yasuo: '疾风剑豪',
		scqhLOL_akali: '离群之刺',
		scqhLOL_mofeite: '熔岩巨兽',
		scqhLOL_delaiesi: '诺克萨斯之手',
		scqhLOL_yatuokesi: '暗裔剑魔',
	};
	const sort = scqh.characterSort.scqh;
	for (const listname in sort) {
		const image = function (lib, character, number, name) {
			if (!number) number = 0;
			character[4].push(`ext:${lib.scqhExtension}/skin/image/${name}/${number}.jpg`);
			return character;
		};
		for (const name of sort[listname]) {
			if (lib.config['extension_' + lib.scqhExtension + '_secondName_' + listname]) {
				if (secondName[name]) scqh.translate[name] = secondName[name];
			}
			if (listname === 'scqhZhinv') {
				scqh.translate[name + '_prefix'] = '织';
				scqh.translate[name] = '织' + scqh.translate[name];
			}
			if (listname == 'scqhMiao') {
				scqh.translate[name + '_prefix'] = '🐱';
				scqh.translate[name] = '🐱' + scqh.translate[name];
			}
			const character = scqh.character[name] || [];
			if (!character || !character.length) continue;
			if (!character[4]) character[4] = [];
			let number = 0;
			if (name === 'scqh_shenchunqianhe') {
				number = get.rand(0, 15);
			}
			scqh.character[name] = image(lib, character, number, name);
		}
	}
	lib.config.all.characters.add('scqh');
	lib.translate.scqh_character_config = lib.scqhExtension;
	lib.config.characters.add('scqh');
	return scqh;
});
